/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/
define(['controller/_unidadDeRedController','delegate/unidadDeRedDelegate'], function() {
    App.Controller.UnidadDeRedController = App.Controller._UnidadDeRedController.extend({
         postInit:function(){
            // Agregar - siguiente linea - "this.currentTemplate" EN EL postInit existente
            this.currentTemplate;
        },
        // start : searchRelated
        setCurrentTemplate:function(templateName){
            var self = this;
            self.currentTemplate = _.template($('#'+templateName).html());
        },
        setVisibility : function(params){
            var txt_id = params.textInputId ;
            var style = $(''+txt_id).attr("style");
            var sp = style.split(": ");
            var btn_id = '#btn_'+(txt_id.split("#")[1]).replace("fg-","");
            if( sp[1] == "hidden" ){
                $(btn_id).attr("class","btn btn-success");
                $(txt_id).attr("style","visibility: visible");
            }
            else{
                $(btn_id).attr("class","btn btn-primary");
                $(txt_id).attr("style","visibility: hidden");
            }
        },
        _render:function(){
            var self = this;
            // Cambiar - siguiente linea : ......currentTemplate({ JSON DE _MiComponenteController }));
            this.$el.slideUp("fast", function() {
                self.$el.html(self.currentTemplate({unidadDeRed: self.currentModel, componentId: self.componentId , showEdit : self.showEdit , showDelete : self.showDelete
 
				    ,encargado: self.encargadoComponent
 
				}));
                self.$el.slideDown("fast");
            });
        },
        search:function(){// Cambiar - en todo el metodo search : Los 'blablabla-<miComponente>-blablabla'
            if (App.Utils.eventExists(this.componentId + '-' +'instead-unidadDeRed-create')) {
                Backbone.trigger(this.componentId + '-' + 'instead-unidadDeRed-create', {view: this});
            } else {
                Backbone.trigger(this.componentId + '-' + 'pre-unidadDeRed-create', {view: this});
                this.currentModel = new this.modelClass({componentId: this.componentId});
                this._render();
                Backbone.trigger(this.componentId + '-' + 'post-unidadDeRed-create', {view: this});
            }
        },
        unidadderedsearch: function(callback,context){
            var self = this;
            var model = $('#' + this.componentId + '-unidadDeRedForm').serializeObject();
            this.currentModel.set(model);
            var delegate = new App.Delegate.UnidadDeRedDelegate();
            delegate.search(self.currentModel, function (data) {
                self.currentList.reset(data.records);
                callback.call(context,{data: self.currentList, page: 1, pages: 1, totalRecords: self.currentList.lenght})
            }, function (data) {
                Backbone.trigger(self.componentId + '-' + 'error', {event: 'unidadDeRed-search', view: self, id: '', data: data, error: 'Error in unidadDeRed search'});
            });
        },
        desactivar: function(context, data){
            console.log("Entró a desactivar en el controller");
            console.log(context);
            var datadef= data.listComponent.listController.model.attributes.data;
            console.log(datadef);
            var self= this;
            var modelo= [];
            
            for(var i=0;i<datadef.length;i++)
            {
                var temp= datadef[i].id;
                console.log(temp);
                if(context.hasOwnProperty(temp))
                {
                    this.agregarArr(modelo,temp);
                }
            }
            console.log(modelo);
            this.currentModel = new this.modelClass({componentId: this.componentId});
            this.currentModel.set(modelo);
            console.log("Estableció el modelo");
            var delegate = new App.Delegate.UnidadDeRedDelegate();
            delegate.desactivar(self.currentModel);
        },
        agregarArr: function(arr,id){
            arr[arr.length]=id;
        }
    });
    return App.Controller.UnidadDeRedController;
}); 