/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.encargado.logic.ejb;
import java.util.List;
import javax.inject.Inject;

import co.edu.uniandes.csw.grupo.encargado.logic.dto.EncargadoDTO;
import co.edu.uniandes.csw.grupo.encargado.logic.dto.EncargadoPageDTO;
import co.edu.uniandes.csw.grupo.encargado.logic.api._IEncargadoLogicService;
import co.edu.uniandes.csw.grupo.encargado.persistence.api.IEncargadoPersistence;

public abstract class _EncargadoLogicService implements _IEncargadoLogicService {

	@Inject
	protected IEncargadoPersistence persistance;

	public EncargadoDTO createEncargado(EncargadoDTO encargado){
		return persistance.createEncargado( encargado); 
    }

	public List<EncargadoDTO> getEncargados(){
		return persistance.getEncargados(); 
	}

	public EncargadoPageDTO getEncargados(Integer page, Integer maxRecords){
		return persistance.getEncargados(page, maxRecords); 
	}

	public EncargadoDTO getEncargado(Long id){
		return persistance.getEncargado(id); 
	}

	public void deleteEncargado(Long id){
	    persistance.deleteEncargado(id); 
	}

	public void updateEncargado(EncargadoDTO encargado){
	    persistance.updateEncargado(encargado); 
	}	
}