/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.paginaweb.service;

import co.edu.uniandes.csw.grupo.maquinavirtual.logic.dto.MaquinaVirtualPageDTO;
import co.edu.uniandes.csw.grupo.paginaweb.logic.dto.PaginaWebDTO;
import co.edu.uniandes.csw.grupo.paginaweb.logic.dto.PaginaWebPageDTO;
import java.util.List;

import javax.ejb.Stateless;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.MultivaluedMap;
import javax.ws.rs.core.UriInfo;

@Path("/PaginaWeb")
@Stateless
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public class PaginaWebService extends _PaginaWebService {

    @Context
    UriInfo uriInfo;
    
    @GET
    @Override
    public PaginaWebPageDTO getPaginaWebs(@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords){
        System.out.println("Acceso!!!!!!!!!!!!!!!!!!");
		return super.getPaginaWebs(page, maxRecords);
    }
    
    @GET
    @Path("/Search")
    public PaginaWebPageDTO searchPaginasWeb(@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords){
        
        MultivaluedMap<String, String> queryParams = uriInfo.getQueryParameters();
        
        System.out.println(queryParams.keySet());
        System.out.println(queryParams.values());
        
        // Estos atributos podran ser vacios o tener valores
        // Si estan vacios no se incluiran en la busqueda
        
        String formato = queryParams.getFirst("formato");
        String url = queryParams.getFirst("url");
        String alias = queryParams.getFirst("alias");        
        String name = queryParams.getFirst("name");
        String descripcion = queryParams.getFirst("descripcion");
        String proposito = queryParams.getFirst("proposito");
        String caracteristicas = queryParams.getFirst("caracteristicas");
        String cmsId = queryParams.getFirst("cmsId");
        String encargadoId = queryParams.getFirst("encargadoId");
       
        // Estos atributos, en cambio, siempre poseeran valores estandar.
        // Se debe aclarar eso en el manual de uso.
                       
        String fechaCreac1 = queryParams.getFirst("fechaCreacion");
        String fechaCreac2 = queryParams.getFirst("fechaCreacion2");
        
        String ultimaFechaMod1 = queryParams.getFirst("ultimaFechaModificacion");
        String ultimaFechaMod2 = queryParams.getFirst("ultimaFechaModificacion2");
        
        String destruido = queryParams.getFirst("destruido");
        
        String estaDestruido = "";

        
        if(formato == null)
            formato = "";
        if(url == null)
            url = "";
        if(alias == null)
            alias = "";
        if(name == null)
            name = "";
        if(descripcion == null)
            descripcion = "";
        if(proposito == null)
            proposito = "";
        if(caracteristicas == null)
            caracteristicas = "";
        if(cmsId == null)
            cmsId = "";
        if(encargadoId == null)
            encargadoId = "";

        if(destruido == null)
            destruido = "";
                       


        

        String fechaCreacion1 = "";
        String fechaCreacion2 = "";
        
        if(!fechaCreac1.isEmpty() && fechaCreac1 != null)
        {
            String[] date1 = fechaCreac1.split("%2F");
            fechaCreacion1 = date1[2] + "-" + date1[1] + "-" + date1[0];
        }       
        
        if(!fechaCreac2.isEmpty() && fechaCreac2 != null)
        {
            String[] date2 = fechaCreac2.split("%2F");            
            fechaCreacion2 = date2[2] + "-" + date2[1] + "-" + date2[0];

        }
        
        String ultimaFechaModificacion1 = "";
        String ultimaFechaModificacion2 = "";
        
        if(!ultimaFechaMod1.isEmpty() && ultimaFechaMod1 != null)
        {
            String[] date1 = ultimaFechaMod1.split("%2F");
            ultimaFechaModificacion1 = date1[2] + "-" + date1[1] + "-" + date1[0];
        }       
        
        if(!ultimaFechaMod2.isEmpty() && ultimaFechaMod2 != null)
        {
            String[] date2 = ultimaFechaMod2.split("%2F");            
            ultimaFechaModificacion2 = date2[2] + "-" + date2[1] + "-" + date2[0];

        }
        
        if(destruido.isEmpty())       
            estaDestruido = "1";
        else
            estaDestruido = "0";   
        
        
        return paginaWebLogicService.getPaginasWebByParameters(formato , url , alias , name , descripcion , proposito , caracteristicas , cmsId , encargadoId , fechaCreacion1, fechaCreacion2, ultimaFechaModificacion1, ultimaFechaModificacion2, estaDestruido);
    }
    
    @GET
    @Path("/Desactivar")
    public PaginaWebPageDTO desactivarPaginas(@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords)
    {
        MultivaluedMap<String, String> queryParams = uriInfo.getQueryParameters();
        System.out.println(queryParams.keySet());
        System.out.println(queryParams.values());
        for(int i=0;i<queryParams.size()-3;i++)
        {
            Long id= Long.parseLong(queryParams.getFirst(i+""));
            paginaWebLogicService.desactivarRecurso(id);   
        }
        return super.getPaginaWebs(page, maxRecords);
    }


}