/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.wiki.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.grupo.wiki.logic.dto.WikiDTO;
import co.edu.uniandes.csw.grupo.wiki.logic.api.IWikiLogicService;
import co.edu.uniandes.csw.grupo.wiki.master.logic.api._IWikiMasterLogicService;
import co.edu.uniandes.csw.grupo.wiki.master.logic.dto.WikiMasterDTO;
import co.edu.uniandes.csw.grupo.problema.logic.api.IProblemaLogicService;
import co.edu.uniandes.csw.grupo.estudiante.logic.api.IEstudianteLogicService;
import co.edu.uniandes.csw.grupo.problema.logic.dto.ProblemaDTO;
import co.edu.uniandes.csw.grupo.estudiante.logic.dto.EstudianteDTO;
import javax.inject.Inject;


public abstract class _WikiMasterMockLogicService implements _IWikiMasterLogicService {

    protected static ArrayList<WikiMasterDTO> wikiMasterDtosList = new ArrayList<WikiMasterDTO>() ;
    @Inject
    protected IProblemaLogicService problemaPersistance;
    @Inject
    protected IEstudianteLogicService estudiantePersistance;
    @Inject
    protected IWikiLogicService wikiPersistance;

    public WikiMasterDTO createMasterWiki(WikiMasterDTO wiki) {

        wikiPersistance.createWiki(wiki.getWikiEntity());
        for (EstudianteDTO dto : wiki.getCreateduenios()) {
            estudiantePersistance.createEstudiante(dto);
        }
        for (ProblemaDTO dto : wiki.getCreateproblema()) {
            problemaPersistance.createProblema(dto);
        }
        wikiMasterDtosList.add(wiki);
        return wiki;
    }

    public WikiMasterDTO getMasterWiki(Long id) {
        for (WikiMasterDTO wikiMasterDTO : wikiMasterDtosList) {
            if (wikiMasterDTO.getWikiEntity().getId() == id) {
                return wikiMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterWiki(Long id) {
        for (WikiMasterDTO wikiMasterDTO : wikiMasterDtosList) {
            if (wikiMasterDTO.getWikiEntity().getId() == id) {

                for (EstudianteDTO dto : wikiMasterDTO.getCreateduenios()) {
                    estudiantePersistance.deleteEstudiante(dto.getId());
                }
                wikiPersistance.deleteWiki(wikiMasterDTO.getId());
                wikiMasterDtosList.remove(wikiMasterDTO);
                for (ProblemaDTO dto : wikiMasterDTO.getCreateproblema()) {
                    problemaPersistance.deleteProblema(dto.getId());
                }
                wikiPersistance.deleteWiki(wikiMasterDTO.getId());
                wikiMasterDtosList.remove(wikiMasterDTO);
            }
        }

    }

    public void updateMasterWiki(WikiMasterDTO wiki) {

        // update Estudiante
        if (wiki.getUpdateduenios() != null) {
            for (EstudianteDTO dto : wiki.getUpdateduenios()) {
                estudiantePersistance.updateEstudiante(dto);
            }
        }
        // persist new Estudiante
        if (wiki.getCreateduenios() != null) {
            for (EstudianteDTO dto : wiki.getCreateduenios()) {
                EstudianteDTO persistedEstudianteDTO = estudiantePersistance.createEstudiante(dto);
                dto = persistedEstudianteDTO;
            }
        }
        // delete Estudiante
        if (wiki.getDeleteduenios() != null) {
            for (EstudianteDTO dto : wiki.getDeleteduenios()) {

                estudiantePersistance.deleteEstudiante(dto.getId());
            }
        }
        // update Problema
        if (wiki.getUpdateproblema() != null) {
            for (ProblemaDTO dto : wiki.getUpdateproblema()) {
                problemaPersistance.updateProblema(dto);
            }
        }
        // persist new Problema
        if (wiki.getCreateproblema() != null) {
            for (ProblemaDTO dto : wiki.getCreateproblema()) {
                ProblemaDTO persistedProblemaDTO = problemaPersistance.createProblema(dto);
                dto = persistedProblemaDTO;
            }
        }
        // delete Problema
        if (wiki.getDeleteproblema() != null) {
            for (ProblemaDTO dto : wiki.getDeleteproblema()) {

                problemaPersistance.deleteProblema(dto.getId());
            }
        }
    }
}