/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.problema.logic.dto;

import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement 
public abstract class _ProblemaDTO {

	

	private Long id;
	

	private String name;
	

	private String descripcion;
	

	private String fechaDeOcurrencia;
	

	private Long empleadoId;
	

	private Long sqldevId;
	

	private Long mysqlId;
	

	private Long paginawebId;
	

	private Long wikiId;
	

	private Long maquinavirtualId;
	

	private Long unidadderedId;
	

	private Long repositorioId;
	

	private Long contenedorwebId;
	

	private Long softwaresalasId;



	public Long getId() {
		return id;
	}
 
	public void setId(Long id) {
		this.id = id;
	}


	public String getName() {
		return name;
	}
 
	public void setName(String name) {
		this.name = name;
	}


	public String getDescripcion() {
		return descripcion;
	}
 
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}


	public String getFechaDeOcurrencia() {
		return fechaDeOcurrencia;
	}
 
	public void setFechaDeOcurrencia(String fechadeocurrencia) {
		this.fechaDeOcurrencia = fechadeocurrencia;
	}


	public Long getEmpleadoId() {
		return empleadoId;
	}
 
	public void setEmpleadoId(Long empleadoid) {
		this.empleadoId = empleadoid;
	}


	public Long getSqldevId() {
		return sqldevId;
	}
 
	public void setSqldevId(Long sqldevid) {
		this.sqldevId = sqldevid;
	}


	public Long getMysqlId() {
		return mysqlId;
	}
 
	public void setMysqlId(Long mysqlid) {
		this.mysqlId = mysqlid;
	}


	public Long getPaginawebId() {
		return paginawebId;
	}
 
	public void setPaginawebId(Long paginawebid) {
		this.paginawebId = paginawebid;
	}


	public Long getWikiId() {
		return wikiId;
	}
 
	public void setWikiId(Long wikiid) {
		this.wikiId = wikiid;
	}


	public Long getMaquinavirtualId() {
		return maquinavirtualId;
	}
 
	public void setMaquinavirtualId(Long maquinavirtualid) {
		this.maquinavirtualId = maquinavirtualid;
	}


	public Long getUnidadderedId() {
		return unidadderedId;
	}
 
	public void setUnidadderedId(Long unidadderedid) {
		this.unidadderedId = unidadderedid;
	}


	public Long getRepositorioId() {
		return repositorioId;
	}
 
	public void setRepositorioId(Long repositorioid) {
		this.repositorioId = repositorioid;
	}


	public Long getContenedorwebId() {
		return contenedorwebId;
	}
 
	public void setContenedorwebId(Long contenedorwebid) {
		this.contenedorwebId = contenedorwebid;
	}


	public Long getSoftwaresalasId() {
		return softwaresalasId;
	}
 
	public void setSoftwaresalasId(Long softwaresalasid) {
		this.softwaresalasId = softwaresalasid;
	}
	
}