/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.paginaweb.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.grupo.paginaweb.logic.dto.PaginaWebDTO;
import co.edu.uniandes.csw.grupo.paginaweb.persistence.entity.PaginaWebEntity;

public abstract class _PaginaWebConverter {

 
	private final static SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");
	public static PaginaWebDTO entity2PersistenceDTO(PaginaWebEntity entity){
		if (entity != null) {
			PaginaWebDTO dto = new PaginaWebDTO();
					dto.setFormato(entity.getFormato());
 
			    if(entity.getUltimaFechaModificacion() != null){
					dto.setUltimaFechaModificacion(DATE_FORMAT.format(entity.getUltimaFechaModificacion()));
				}	
					dto.setUrl(entity.getUrl());
					dto.setAlias(entity.getAlias());
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setDescripcion(entity.getDescripcion());
					dto.setProposito(entity.getProposito());
 
			    if(entity.getFechaCreacion() != null){
					dto.setFechaCreacion(DATE_FORMAT.format(entity.getFechaCreacion()));
				}	
					dto.setDestruido(entity.getDestruido());
					dto.setCaracteristicas(entity.getCaracteristicas());
					dto.setCmsId(entity.getCmsId());
					dto.setEncargadoId(entity.getEncargadoId());
			return dto;
		}else{
			return null;
		}
	}
	
	public static PaginaWebEntity persistenceDTO2Entity(PaginaWebDTO dto){
		if(dto!=null){
			PaginaWebEntity entity=new PaginaWebEntity();
					entity.setFormato(dto.getFormato());
			
 
			      try{ 
			        if(dto.getUltimaFechaModificacion() != null){
						entity.setUltimaFechaModificacion(DATE_FORMAT.parse(dto.getUltimaFechaModificacion()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_PaginaWebConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
					entity.setUrl(dto.getUrl());
			
					entity.setAlias(dto.getAlias());
			
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setDescripcion(dto.getDescripcion());
			
					entity.setProposito(dto.getProposito());
			
 
			      try{ 
			        if(dto.getFechaCreacion() != null){
						entity.setFechaCreacion(DATE_FORMAT.parse(dto.getFechaCreacion()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_PaginaWebConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
					entity.setDestruido(dto.getDestruido());
			
					entity.setCaracteristicas(dto.getCaracteristicas());
			
					entity.setCmsId(dto.getCmsId());
			
					entity.setEncargadoId(dto.getEncargadoId());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<PaginaWebDTO> entity2PersistenceDTOList(List<PaginaWebEntity> entities){
		List<PaginaWebDTO> dtos=new ArrayList<PaginaWebDTO>();
		for(PaginaWebEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<PaginaWebEntity> persistenceDTO2EntityList(List<PaginaWebDTO> dtos){
		List<PaginaWebEntity> entities=new ArrayList<PaginaWebEntity>();
		for(PaginaWebDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}