/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.encargado.master.logic.dto;

import co.edu.uniandes.csw.grupo.wiki.logic.dto.WikiDTO;
import co.edu.uniandes.csw.grupo.maquinavirtual.logic.dto.MaquinaVirtualDTO;
import co.edu.uniandes.csw.grupo.unidaddered.logic.dto.UnidadDeRedDTO;
import co.edu.uniandes.csw.grupo.repositorio.logic.dto.RepositorioDTO;
import co.edu.uniandes.csw.grupo.contenedorweb.logic.dto.ContenedorWebDTO;
import co.edu.uniandes.csw.grupo.softwaresalas.logic.dto.SoftwareSalasDTO;
import co.edu.uniandes.csw.grupo.sqldev.logic.dto.SQLDevDTO;
import co.edu.uniandes.csw.grupo.mysql.logic.dto.MySQLDTO;
import co.edu.uniandes.csw.grupo.encargado.logic.dto.EncargadoDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _EncargadoMasterDTO {

 
    protected EncargadoDTO encargadoEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public EncargadoDTO getEncargadoEntity() {
        return encargadoEntity;
    }

    public void setEncargadoEntity(EncargadoDTO encargadoEntity) {
        this.encargadoEntity = encargadoEntity;
    }
    
    public List<WikiDTO> createwiki;
    public List<WikiDTO> updatewiki;
    public List<WikiDTO> deletewiki;
    public List<WikiDTO> listwiki;	
    public List<MaquinaVirtualDTO> createmaquinaVirtual;
    public List<MaquinaVirtualDTO> updatemaquinaVirtual;
    public List<MaquinaVirtualDTO> deletemaquinaVirtual;
    public List<MaquinaVirtualDTO> listmaquinaVirtual;	
    public List<UnidadDeRedDTO> createunidadDeRed;
    public List<UnidadDeRedDTO> updateunidadDeRed;
    public List<UnidadDeRedDTO> deleteunidadDeRed;
    public List<UnidadDeRedDTO> listunidadDeRed;	
    public List<RepositorioDTO> createrepositorio;
    public List<RepositorioDTO> updaterepositorio;
    public List<RepositorioDTO> deleterepositorio;
    public List<RepositorioDTO> listrepositorio;	
    public List<ContenedorWebDTO> createcontenedorWeb;
    public List<ContenedorWebDTO> updatecontenedorWeb;
    public List<ContenedorWebDTO> deletecontenedorWeb;
    public List<ContenedorWebDTO> listcontenedorWeb;	
    public List<SoftwareSalasDTO> createsoftwareSalas;
    public List<SoftwareSalasDTO> updatesoftwareSalas;
    public List<SoftwareSalasDTO> deletesoftwareSalas;
    public List<SoftwareSalasDTO> listsoftwareSalas;	
    public List<SQLDevDTO> createsQLDev;
    public List<SQLDevDTO> updatesQLDev;
    public List<SQLDevDTO> deletesQLDev;
    public List<SQLDevDTO> listsQLDev;	
    public List<MySQLDTO> createmySQL;
    public List<MySQLDTO> updatemySQL;
    public List<MySQLDTO> deletemySQL;
    public List<MySQLDTO> listmySQL;	
	
	
	
    public List<WikiDTO> getCreatewiki(){ return createwiki; };
    public void setCreatewiki(List<WikiDTO> createwiki){ this.createwiki=createwiki; };
    public List<WikiDTO> getUpdatewiki(){ return updatewiki; };
    public void setUpdatewiki(List<WikiDTO> updatewiki){ this.updatewiki=updatewiki; };
    public List<WikiDTO> getDeletewiki(){ return deletewiki; };
    public void setDeletewiki(List<WikiDTO> deletewiki){ this.deletewiki=deletewiki; };
    public List<WikiDTO> getListwiki(){ return listwiki; };
    public void setListwiki(List<WikiDTO> listwiki){ this.listwiki=listwiki; };	
    public List<MaquinaVirtualDTO> getCreatemaquinaVirtual(){ return createmaquinaVirtual; };
    public void setCreatemaquinaVirtual(List<MaquinaVirtualDTO> createmaquinaVirtual){ this.createmaquinaVirtual=createmaquinaVirtual; };
    public List<MaquinaVirtualDTO> getUpdatemaquinaVirtual(){ return updatemaquinaVirtual; };
    public void setUpdatemaquinaVirtual(List<MaquinaVirtualDTO> updatemaquinaVirtual){ this.updatemaquinaVirtual=updatemaquinaVirtual; };
    public List<MaquinaVirtualDTO> getDeletemaquinaVirtual(){ return deletemaquinaVirtual; };
    public void setDeletemaquinaVirtual(List<MaquinaVirtualDTO> deletemaquinaVirtual){ this.deletemaquinaVirtual=deletemaquinaVirtual; };
    public List<MaquinaVirtualDTO> getListmaquinaVirtual(){ return listmaquinaVirtual; };
    public void setListmaquinaVirtual(List<MaquinaVirtualDTO> listmaquinaVirtual){ this.listmaquinaVirtual=listmaquinaVirtual; };	
    public List<UnidadDeRedDTO> getCreateunidadDeRed(){ return createunidadDeRed; };
    public void setCreateunidadDeRed(List<UnidadDeRedDTO> createunidadDeRed){ this.createunidadDeRed=createunidadDeRed; };
    public List<UnidadDeRedDTO> getUpdateunidadDeRed(){ return updateunidadDeRed; };
    public void setUpdateunidadDeRed(List<UnidadDeRedDTO> updateunidadDeRed){ this.updateunidadDeRed=updateunidadDeRed; };
    public List<UnidadDeRedDTO> getDeleteunidadDeRed(){ return deleteunidadDeRed; };
    public void setDeleteunidadDeRed(List<UnidadDeRedDTO> deleteunidadDeRed){ this.deleteunidadDeRed=deleteunidadDeRed; };
    public List<UnidadDeRedDTO> getListunidadDeRed(){ return listunidadDeRed; };
    public void setListunidadDeRed(List<UnidadDeRedDTO> listunidadDeRed){ this.listunidadDeRed=listunidadDeRed; };	
    public List<RepositorioDTO> getCreaterepositorio(){ return createrepositorio; };
    public void setCreaterepositorio(List<RepositorioDTO> createrepositorio){ this.createrepositorio=createrepositorio; };
    public List<RepositorioDTO> getUpdaterepositorio(){ return updaterepositorio; };
    public void setUpdaterepositorio(List<RepositorioDTO> updaterepositorio){ this.updaterepositorio=updaterepositorio; };
    public List<RepositorioDTO> getDeleterepositorio(){ return deleterepositorio; };
    public void setDeleterepositorio(List<RepositorioDTO> deleterepositorio){ this.deleterepositorio=deleterepositorio; };
    public List<RepositorioDTO> getListrepositorio(){ return listrepositorio; };
    public void setListrepositorio(List<RepositorioDTO> listrepositorio){ this.listrepositorio=listrepositorio; };	
    public List<ContenedorWebDTO> getCreatecontenedorWeb(){ return createcontenedorWeb; };
    public void setCreatecontenedorWeb(List<ContenedorWebDTO> createcontenedorWeb){ this.createcontenedorWeb=createcontenedorWeb; };
    public List<ContenedorWebDTO> getUpdatecontenedorWeb(){ return updatecontenedorWeb; };
    public void setUpdatecontenedorWeb(List<ContenedorWebDTO> updatecontenedorWeb){ this.updatecontenedorWeb=updatecontenedorWeb; };
    public List<ContenedorWebDTO> getDeletecontenedorWeb(){ return deletecontenedorWeb; };
    public void setDeletecontenedorWeb(List<ContenedorWebDTO> deletecontenedorWeb){ this.deletecontenedorWeb=deletecontenedorWeb; };
    public List<ContenedorWebDTO> getListcontenedorWeb(){ return listcontenedorWeb; };
    public void setListcontenedorWeb(List<ContenedorWebDTO> listcontenedorWeb){ this.listcontenedorWeb=listcontenedorWeb; };	
    public List<SoftwareSalasDTO> getCreatesoftwareSalas(){ return createsoftwareSalas; };
    public void setCreatesoftwareSalas(List<SoftwareSalasDTO> createsoftwareSalas){ this.createsoftwareSalas=createsoftwareSalas; };
    public List<SoftwareSalasDTO> getUpdatesoftwareSalas(){ return updatesoftwareSalas; };
    public void setUpdatesoftwareSalas(List<SoftwareSalasDTO> updatesoftwareSalas){ this.updatesoftwareSalas=updatesoftwareSalas; };
    public List<SoftwareSalasDTO> getDeletesoftwareSalas(){ return deletesoftwareSalas; };
    public void setDeletesoftwareSalas(List<SoftwareSalasDTO> deletesoftwareSalas){ this.deletesoftwareSalas=deletesoftwareSalas; };
    public List<SoftwareSalasDTO> getListsoftwareSalas(){ return listsoftwareSalas; };
    public void setListsoftwareSalas(List<SoftwareSalasDTO> listsoftwareSalas){ this.listsoftwareSalas=listsoftwareSalas; };	
    public List<SQLDevDTO> getCreatesQLDev(){ return createsQLDev; };
    public void setCreatesQLDev(List<SQLDevDTO> createsQLDev){ this.createsQLDev=createsQLDev; };
    public List<SQLDevDTO> getUpdatesQLDev(){ return updatesQLDev; };
    public void setUpdatesQLDev(List<SQLDevDTO> updatesQLDev){ this.updatesQLDev=updatesQLDev; };
    public List<SQLDevDTO> getDeletesQLDev(){ return deletesQLDev; };
    public void setDeletesQLDev(List<SQLDevDTO> deletesQLDev){ this.deletesQLDev=deletesQLDev; };
    public List<SQLDevDTO> getListsQLDev(){ return listsQLDev; };
    public void setListsQLDev(List<SQLDevDTO> listsQLDev){ this.listsQLDev=listsQLDev; };	
    public List<MySQLDTO> getCreatemySQL(){ return createmySQL; };
    public void setCreatemySQL(List<MySQLDTO> createmySQL){ this.createmySQL=createmySQL; };
    public List<MySQLDTO> getUpdatemySQL(){ return updatemySQL; };
    public void setUpdatemySQL(List<MySQLDTO> updatemySQL){ this.updatemySQL=updatemySQL; };
    public List<MySQLDTO> getDeletemySQL(){ return deletemySQL; };
    public void setDeletemySQL(List<MySQLDTO> deletemySQL){ this.deletemySQL=deletemySQL; };
    public List<MySQLDTO> getListmySQL(){ return listmySQL; };
    public void setListmySQL(List<MySQLDTO> listmySQL){ this.listmySQL=listmySQL; };	
	
	
}

