/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.estudiante.persistence;

import co.edu.uniandes.csw.grupo.estudiante.logic.dto.EstudiantePageDTO;
import javax.ejb.Stateless;
import javax.enterprise.inject.Default;

import co.edu.uniandes.csw.grupo.estudiante.persistence.api.IEstudiantePersistence;
import co.edu.uniandes.csw.grupo.estudiante.persistence.converter.EstudianteConverter;
import javax.ejb.LocalBean;
import javax.persistence.Query;

@Default
@Stateless 
@LocalBean
public class EstudiantePersistence extends _EstudiantePersistence  implements IEstudiantePersistence {

    @SuppressWarnings("unchecked")
    public EstudiantePageDTO getEstudiantesByParameters(String name ,String login ,String permisoEscritura ,String permisoLectura ,String tipoAcceso)
    {
        Query count = entityManager.createQuery("select count(u) from EstudianteEntity u");
        Long regCount = 0L;
        regCount = Long.parseLong(count.getSingleResult().toString());
                
        String sql = "SELECT u FROM EstudianteEntity u WHERE";
        if(!name.isEmpty())
            sql += " AND u.name like :name";
        if(!login.isEmpty())
            sql += " AND u.login like :login";
        if(!permisoEscritura.isEmpty())
            sql += " AND u.permisoEscritura = :permisoEscritura";
        if(!permisoLectura.isEmpty())
            sql  += " AND u.permisoLectura = :permisoLectura";
        if(!tipoAcceso.isEmpty())
            sql += " AND u.tipoAcceso like :tipoAcceso";       
       
        // Se limpia la sentencia sql
        
        if(sql.endsWith("WHERE"))
            sql = sql.replace("WHERE", "");
        if(sql.contains("WHERE AND"))
            sql = sql.replace("WHERE AND", "WHERE");
        
        System.out.println(sql);
        
        boolean permisoEscrituraP = false;
        
        if(permisoEscritura.equals("1"))
            permisoEscrituraP = true;
        
        boolean permisoLecturaP = false;
        
        if(permisoLectura.equals("1"))
            permisoLecturaP = true;
        
        Query q = entityManager.createQuery(sql);
        
        if(!name.isEmpty())
            q.setParameter("name", "%"+name+"%");
        if(!login .isEmpty())
            q.setParameter("login", "%"+login +"%");
        if(!permisoEscritura.isEmpty())
            q.setParameter("permisoEscritura", permisoEscrituraP);
        if(!permisoLectura.isEmpty())
            q.setParameter("permisoLectura", permisoLecturaP);
        if(!tipoAcceso.isEmpty())
            q.setParameter("tipoAcceso", "%"+tipoAcceso+"%");        
        
                
        EstudiantePageDTO response = new EstudiantePageDTO();
        response.setTotalRecords(regCount);
        response.setRecords(EstudianteConverter.entity2PersistenceDTOList(q.getResultList()));
        return response;
        
            
    }
}