/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.empleado.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.grupo.empleado.logic.dto.EmpleadoDTO;
import co.edu.uniandes.csw.grupo.empleado.persistence.entity.EmpleadoEntity;

public abstract class _EmpleadoConverter {

	public static EmpleadoDTO entity2PersistenceDTO(EmpleadoEntity entity){
		if (entity != null) {
			EmpleadoDTO dto = new EmpleadoDTO();
					dto.setPassword(entity.getPassword());
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setLogin(entity.getLogin());
			return dto;
		}else{
			return null;
		}
	}
	
	public static EmpleadoEntity persistenceDTO2Entity(EmpleadoDTO dto){
		if(dto!=null){
			EmpleadoEntity entity=new EmpleadoEntity();
					entity.setPassword(dto.getPassword());
			
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setLogin(dto.getLogin());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<EmpleadoDTO> entity2PersistenceDTOList(List<EmpleadoEntity> entities){
		List<EmpleadoDTO> dtos=new ArrayList<EmpleadoDTO>();
		for(EmpleadoEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<EmpleadoEntity> persistenceDTO2EntityList(List<EmpleadoDTO> dtos){
		List<EmpleadoEntity> entities=new ArrayList<EmpleadoEntity>();
		for(EmpleadoDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}