/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.repositorio.master.persistence.entity;

import co.edu.uniandes.csw.grupo.estudiante.persistence.entity.EstudianteEntity;
import co.edu.uniandes.csw.grupo.repositorio.persistence.entity.RepositorioEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(RepositoriousuariosQueAccedenEntityId.class)
@NamedQueries({
    @NamedQuery(name = "RepositoriousuariosQueAccedenEntity.getByMasterId", query = "SELECT  u FROM RepositoriousuariosQueAccedenEntity u WHERE u.repositorioId=:repositorioId"),
    @NamedQuery(name = "RepositoriousuariosQueAccedenEntity.deleteRepositoriousuariosQueAccedenEntity", query = "DELETE FROM RepositoriousuariosQueAccedenEntity u WHERE u.repositorioId=:repositorioId and  u.usuariosQueAccedenId=:usuariosQueAccedenId")
})
public class RepositoriousuariosQueAccedenEntity implements Serializable {

    @Id
    @Column(name = "repositorioId")
    private Long repositorioId;
    @Id
    @Column(name = "usuariosQueAccedenId")
    private Long usuariosQueAccedenId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "repositorioId", referencedColumnName = "id")
    @JoinFetch
    private EstudianteEntity repositorioIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "usuariosQueAccedenId", referencedColumnName = "id")
    @JoinFetch
    private EstudianteEntity usuariosQueAccedenIdEntity; 

    public RepositoriousuariosQueAccedenEntity() {
    }

    public RepositoriousuariosQueAccedenEntity(Long repositorioId, Long usuariosQueAccedenId) {
        this.repositorioId =repositorioId;
        this.usuariosQueAccedenId = usuariosQueAccedenId;
    }

    public Long getRepositorioId() {
        return repositorioId;
    }

    public void setRepositorioId(Long repositorioId) {
        this.repositorioId = repositorioId;
    }

    public Long getUsuariosQueAccedenId() {
        return usuariosQueAccedenId;
    }

    public void setUsuariosQueAccedenId(Long usuariosQueAccedenId) {
        this.usuariosQueAccedenId = usuariosQueAccedenId;
    }

    public EstudianteEntity getRepositorioIdEntity() {
        return repositorioIdEntity;
    }

    public void setRepositorioIdEntity(EstudianteEntity repositorioIdEntity) {
        this.repositorioIdEntity = repositorioIdEntity;
    }

    public EstudianteEntity getUsuariosQueAccedenIdEntity() {
        return usuariosQueAccedenIdEntity;
    }

    public void setUsuariosQueAccedenIdEntity(EstudianteEntity usuariosQueAccedenIdEntity) {
        this.usuariosQueAccedenIdEntity = usuariosQueAccedenIdEntity;
    }

}
