/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.contenedorweb.master.logic.ejb;

import co.edu.uniandes.csw.grupo.problema.logic.dto.ProblemaDTO;
import co.edu.uniandes.csw.grupo.problema.persistence.api.IProblemaPersistence;
import co.edu.uniandes.csw.grupo.contenedorweb.logic.dto.ContenedorWebDTO;
import co.edu.uniandes.csw.grupo.contenedorweb.master.logic.api._IContenedorWebMasterLogicService;
import co.edu.uniandes.csw.grupo.contenedorweb.master.logic.dto.ContenedorWebMasterDTO;
import co.edu.uniandes.csw.grupo.contenedorweb.master.persistence.api.IContenedorWebMasterPersistence;
import co.edu.uniandes.csw.grupo.contenedorweb.master.persistence.entity.ContenedorWebproblemaEntity;
import co.edu.uniandes.csw.grupo.contenedorweb.persistence.api.IContenedorWebPersistence;
import javax.inject.Inject;

public abstract class _ContenedorWebMasterLogicService implements _IContenedorWebMasterLogicService {

    @Inject
    protected IContenedorWebPersistence contenedorwebPersistance;
    @Inject
    protected IContenedorWebMasterPersistence contenedorwebMasterPersistance;
    @Inject
    protected IProblemaPersistence problemaPersistance;

    public ContenedorWebMasterDTO createMasterContenedorWeb(ContenedorWebMasterDTO contenedorweb) {
        ContenedorWebDTO persistedContenedorWebDTO = contenedorwebPersistance.createContenedorWeb(contenedorweb.getContenedorWebEntity());
        if (contenedorweb.getCreateproblema() != null) {
            for (ProblemaDTO problemaDTO : contenedorweb.getCreateproblema()) {
                ProblemaDTO createdProblemaDTO = problemaPersistance.createProblema(problemaDTO);
                ContenedorWebproblemaEntity contenedorwebProblemaEntity = new ContenedorWebproblemaEntity(persistedContenedorWebDTO.getId(), createdProblemaDTO.getId());
                contenedorwebMasterPersistance.createContenedorWebproblemaEntity(contenedorwebProblemaEntity);
            }
        }
        // update problema
        if (contenedorweb.getUpdateproblema() != null) {
            for (ProblemaDTO problemaDTO : contenedorweb.getUpdateproblema()) {
                problemaPersistance.updateProblema(problemaDTO);
                ContenedorWebproblemaEntity contenedorwebProblemaEntity = new ContenedorWebproblemaEntity(persistedContenedorWebDTO.getId(), problemaDTO.getId());
                contenedorwebMasterPersistance.createContenedorWebproblemaEntity(contenedorwebProblemaEntity);
            }
        }
        return contenedorweb;
    }

    public ContenedorWebMasterDTO getMasterContenedorWeb(Long id) {
        return contenedorwebMasterPersistance.getContenedorWeb(id);
    }

    public void deleteMasterContenedorWeb(Long id) {
        contenedorwebPersistance.deleteContenedorWeb(id);
    }

    public void updateMasterContenedorWeb(ContenedorWebMasterDTO contenedorweb) {
        contenedorwebPersistance.updateContenedorWeb(contenedorweb.getContenedorWebEntity());

        //---- FOR RELATIONSHIP
        // delete problema
        if (contenedorweb.getDeleteproblema() != null) {
            for (ProblemaDTO problemaDTO : contenedorweb.getDeleteproblema()) {
                contenedorwebMasterPersistance.deleteContenedorWebproblemaEntity(contenedorweb.getContenedorWebEntity().getId(), problemaDTO.getId());
            }
        }
        // persist new problema
        if (contenedorweb.getCreateproblema() != null) {
            for (ProblemaDTO problemaDTO : contenedorweb.getCreateproblema()) {
                ContenedorWebproblemaEntity contenedorwebProblemaEntity = new ContenedorWebproblemaEntity(contenedorweb.getContenedorWebEntity().getId(), problemaDTO.getId());
                contenedorwebMasterPersistance.createContenedorWebproblemaEntity(contenedorwebProblemaEntity);
            }
        }
        // update problema
        if (contenedorweb.getUpdateproblema() != null) {
            for (ProblemaDTO problemaDTO : contenedorweb.getUpdateproblema()) {
                contenedorwebMasterPersistance.deleteContenedorWebproblemaEntity(contenedorweb.getContenedorWebEntity().getId(), problemaDTO.getId());
                problemaPersistance.updateProblema(problemaDTO);
                ContenedorWebproblemaEntity contenedorwebProblemaEntity = new ContenedorWebproblemaEntity(contenedorweb.getId(), problemaDTO.getId());
                contenedorwebMasterPersistance.createContenedorWebproblemaEntity(contenedorwebProblemaEntity);
                
            }
        }
    }
}
