/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.recurso.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.grupo.recurso.logic.dto.RecursoDTO;
import co.edu.uniandes.csw.grupo.recurso.logic.dto.RecursoPageDTO;
import co.edu.uniandes.csw.grupo.recurso.persistence.api._IRecursoPersistence;
import co.edu.uniandes.csw.grupo.recurso.persistence.converter.RecursoConverter;
import co.edu.uniandes.csw.grupo.recurso.persistence.entity.RecursoEntity;

public abstract class _RecursoPersistence implements _IRecursoPersistence {

  	@PersistenceContext(unitName="RigitalAppPU")
 
	protected EntityManager entityManager;
	
	public RecursoDTO createRecurso(RecursoDTO recurso) {
		RecursoEntity entity=RecursoConverter.persistenceDTO2Entity(recurso);
		entityManager.persist(entity);
		return RecursoConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<RecursoDTO> getRecursos() {
		Query q = entityManager.createQuery("select u from RecursoEntity u");
		return RecursoConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public RecursoPageDTO getRecursos(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from RecursoEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from RecursoEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		RecursoPageDTO response = new RecursoPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(RecursoConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public RecursoDTO getRecurso(Long id) {
		return RecursoConverter.entity2PersistenceDTO(entityManager.find(RecursoEntity.class, id));
	}

	public void deleteRecurso(Long id) {
		RecursoEntity entity=entityManager.find(RecursoEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateRecurso(RecursoDTO detail) {
		RecursoEntity entity=entityManager.merge(RecursoConverter.persistenceDTO2Entity(detail));
		RecursoConverter.entity2PersistenceDTO(entity);
	}

}