/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

<<<<<<< .mine
*/

package co.edu.uniandes.csw.grupo.maquinavirtual.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;

import co.edu.uniandes.csw.grupo.encargado.master.persistence.entity.EncargadomaquinaVirtualEntity;
import co.edu.uniandes.csw.grupo.maquinavirtual.logic.dto.MaquinaVirtualPageDTO;
import co.edu.uniandes.csw.grupo.maquinavirtual.logic.dto.MaquinaVirtualDTO;
import co.edu.uniandes.csw.grupo.maquinavirtual.persistence.api.IMaquinaVirtualPersistence;
import co.edu.uniandes.csw.grupo.maquinavirtual.persistence.entity.MaquinaVirtualEntity;
import co.edu.uniandes.csw.grupo.maquinavirtual.persistence.converter.MaquinaVirtualConverter;
import static co.edu.uniandes.csw.grupo.util._TestUtil.*;

@RunWith(Arquillian.class)
public class MaquinaVirtualPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(MaquinaVirtualPersistence.class.getPackage())
				.addPackage(MaquinaVirtualEntity.class.getPackage())
				.addPackage(IMaquinaVirtualPersistence.class.getPackage())
                .addPackage(MaquinaVirtualDTO.class.getPackage())
                .addPackage(MaquinaVirtualConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IMaquinaVirtualPersistence maquinaVirtualPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from MaquinaVirtualEntity").executeUpdate();
	}

	private List<MaquinaVirtualEntity> data=new ArrayList<MaquinaVirtualEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			MaquinaVirtualEntity entity=new MaquinaVirtualEntity();
			entity.setIps(generateRandom(String.class));
			entity.setServiciosAsociados(generateRandom(String.class));
			entity.setVersion(generateRandom(String.class));
			entity.setSistemaOperativo(generateRandom(String.class));
			entity.setNumDiscos(generateRandom(Integer.class));
			entity.setCapacidadDiscos(generateRandom(Long.class));
			entity.setRam(generateRandom(String.class));
			entity.setNumCores(generateRandom(Integer.class));
			entity.setFechaVencimiento(generateRandom(Date.class));
			entity.setName(generateRandom(String.class));
			entity.setDescripcion(generateRandom(String.class));
			entity.setProposito(generateRandom(String.class));
			entity.setFechaCreacion(generateRandom(Date.class));
			entity.setDestruido(generateRandom(Boolean.class));
			entity.setCaracteristicas(generateRandom(String.class));
			entity.setEncargadoId(generateRandom(Long.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createMaquinaVirtualTest(){
		MaquinaVirtualDTO dto=new MaquinaVirtualDTO();
		dto.setIps(generateRandom(String.class));
		dto.setServiciosAsociados(generateRandom(String.class));
		dto.setVersion(generateRandom(String.class));
		dto.setSistemaOperativo(generateRandom(String.class));
		dto.setNumDiscos(generateRandom(Integer.class));
		dto.setCapacidadDiscos(generateRandom(Long.class));
		dto.setRam(generateRandom(String.class));
		dto.setNumCores(generateRandom(Integer.class));
dto.setFechaVencimiento(generateRandomDate());
		dto.setName(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		dto.setProposito(generateRandom(String.class));
dto.setFechaCreacion(generateRandomDate());
		dto.setDestruido(generateRandom(Boolean.class));
		dto.setCaracteristicas(generateRandom(String.class));
		dto.setEncargadoId(generateRandom(Long.class));
		
		MaquinaVirtualDTO result=maquinaVirtualPersistence.createMaquinaVirtual(dto);
		
		Assert.assertNotNull(result);
		
		MaquinaVirtualEntity entity=em.find(MaquinaVirtualEntity.class, result.getId());
		
		Assert.assertEquals(dto.getIps(), entity.getIps());
		Assert.assertEquals(dto.getServiciosAsociados(), entity.getServiciosAsociados());
		Assert.assertEquals(dto.getVersion(), entity.getVersion());
		Assert.assertEquals(dto.getSistemaOperativo(), entity.getSistemaOperativo());
		Assert.assertEquals(dto.getNumDiscos(), entity.getNumDiscos());
		Assert.assertEquals(dto.getCapacidadDiscos(), entity.getCapacidadDiscos());
		Assert.assertEquals(dto.getRam(), entity.getRam());
		Assert.assertEquals(dto.getNumCores(), entity.getNumCores());
Assert.assertEquals(parseDate(dto.getFechaVencimiento()), entity.getFechaVencimiento());	
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getDescripcion(), entity.getDescripcion());
		Assert.assertEquals(dto.getProposito(), entity.getProposito());
Assert.assertEquals(parseDate(dto.getFechaCreacion()), entity.getFechaCreacion());	
		Assert.assertEquals(dto.getDestruido(), entity.getDestruido());
		Assert.assertEquals(dto.getCaracteristicas(), entity.getCaracteristicas());
		Assert.assertEquals(dto.getEncargadoId(), entity.getEncargadoId());
	}
	
	@Test
	public void getMaquinaVirtualsTest(){
		List<MaquinaVirtualDTO> list=maquinaVirtualPersistence.getMaquinaVirtuals();
		Assert.assertEquals(list.size(), data.size());
        for(MaquinaVirtualDTO dto:list){
        	boolean found=false;
            for(MaquinaVirtualEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getMaquinaVirtualTest(){
		MaquinaVirtualEntity entity=data.get(0);
		MaquinaVirtualDTO dto=maquinaVirtualPersistence.getMaquinaVirtual(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getIps(), dto.getIps());
		Assert.assertEquals(entity.getServiciosAsociados(), dto.getServiciosAsociados());
		Assert.assertEquals(entity.getVersion(), dto.getVersion());
		Assert.assertEquals(entity.getSistemaOperativo(), dto.getSistemaOperativo());
		Assert.assertEquals(entity.getNumDiscos(), dto.getNumDiscos());
		Assert.assertEquals(entity.getCapacidadDiscos(), dto.getCapacidadDiscos());
		Assert.assertEquals(entity.getRam(), dto.getRam());
		Assert.assertEquals(entity.getNumCores(), dto.getNumCores());
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getDescripcion(), dto.getDescripcion());
		Assert.assertEquals(entity.getProposito(), dto.getProposito());
		Assert.assertEquals(entity.getDestruido(), dto.getDestruido());
		Assert.assertEquals(entity.getCaracteristicas(), dto.getCaracteristicas());
		Assert.assertEquals(entity.getEncargadoId(), dto.getEncargadoId());
        
	}
	
	@Test
	public void deleteMaquinaVirtualTest(){
		MaquinaVirtualEntity entity=data.get(0);
		maquinaVirtualPersistence.deleteMaquinaVirtual(entity.getId());
        MaquinaVirtualEntity deleted=em.find(MaquinaVirtualEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateMaquinaVirtualTest(){
		MaquinaVirtualEntity entity=data.get(0);
		
		MaquinaVirtualDTO dto=new MaquinaVirtualDTO();
		dto.setId(entity.getId());
		dto.setIps(generateRandom(String.class));
		dto.setServiciosAsociados(generateRandom(String.class));
		dto.setVersion(generateRandom(String.class));
		dto.setSistemaOperativo(generateRandom(String.class));
		dto.setNumDiscos(generateRandom(Integer.class));
		dto.setCapacidadDiscos(generateRandom(Long.class));
		dto.setRam(generateRandom(String.class));
		dto.setNumCores(generateRandom(Integer.class));
dto.setFechaVencimiento(generateRandomDate());
		dto.setName(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		dto.setProposito(generateRandom(String.class));
dto.setFechaCreacion(generateRandomDate());
		dto.setDestruido(generateRandom(Boolean.class));
		dto.setCaracteristicas(generateRandom(String.class));
		dto.setEncargadoId(generateRandom(Long.class));
		
		
		maquinaVirtualPersistence.updateMaquinaVirtual(dto);
		
		
		MaquinaVirtualEntity resp=em.find(MaquinaVirtualEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getIps(), resp.getIps());	
		Assert.assertEquals(dto.getServiciosAsociados(), resp.getServiciosAsociados());	
		Assert.assertEquals(dto.getVersion(), resp.getVersion());	
		Assert.assertEquals(dto.getSistemaOperativo(), resp.getSistemaOperativo());	
		Assert.assertEquals(dto.getNumDiscos(), resp.getNumDiscos());	
		Assert.assertEquals(dto.getCapacidadDiscos(), resp.getCapacidadDiscos());	
		Assert.assertEquals(dto.getRam(), resp.getRam());	
		Assert.assertEquals(dto.getNumCores(), resp.getNumCores());	
Assert.assertEquals(parseDate(dto.getFechaVencimiento()), resp.getFechaVencimiento());
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getDescripcion(), resp.getDescripcion());	
		Assert.assertEquals(dto.getProposito(), resp.getProposito());	
Assert.assertEquals(parseDate(dto.getFechaCreacion()), resp.getFechaCreacion());
		Assert.assertEquals(dto.getDestruido(), resp.getDestruido());	
		Assert.assertEquals(dto.getCaracteristicas(), resp.getCaracteristicas());	
		Assert.assertEquals(dto.getEncargadoId(), resp.getEncargadoId());	
	}
	
	@Test
	public void getMaquinaVirtualPaginationTest(){
		//Page 1
		MaquinaVirtualPageDTO dto1=maquinaVirtualPersistence.getMaquinaVirtuals(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        MaquinaVirtualPageDTO dto2=maquinaVirtualPersistence.getMaquinaVirtuals(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(MaquinaVirtualDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(MaquinaVirtualEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(MaquinaVirtualDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(MaquinaVirtualEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
        @Test
        public void desactivarRecursoTest(){
            for(int i=0;i<data.size();i++)
            {
                MaquinaVirtualEntity maquina= data.get(i);
                if(maquina.getDestruido())
                {
                    Long idMaquina= maquina.getId();
                    maquinaVirtualPersistence.desactivarRecurso(idMaquina);
                    Assert.assertFalse(maquina.getDestruido());
                }
            }
        }
	
        @Test
        public void agregarEncargadoMaquinaVirtualTest1(){
                MaquinaVirtualDTO dto=new MaquinaVirtualDTO();
		dto.setIps(generateRandom(String.class));
		dto.setServiciosAsociados(generateRandom(String.class));
		dto.setVersion(generateRandom(String.class));
		dto.setSistemaOperativo(generateRandom(String.class));
		dto.setNumDiscos(generateRandom(Integer.class));
		dto.setCapacidadDiscos(generateRandom(Long.class));
		dto.setRam(generateRandom(String.class));
		dto.setNumCores(generateRandom(Integer.class));
                dto.setFechaVencimiento(generateRandomDate());
		dto.setName(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		dto.setProposito(generateRandom(String.class));
                dto.setFechaCreacion(generateRandomDate());
		dto.setDestruido(generateRandom(Boolean.class));
		dto.setCaracteristicas(generateRandom(String.class));
		dto.setEncargadoId(generateRandom(Long.class));
		
		MaquinaVirtualDTO result=maquinaVirtualPersistence.createMaquinaVirtual(dto);
		
		Assert.assertNotNull(result);
		
		MaquinaVirtualEntity entity=em.find(MaquinaVirtualEntity.class, result.getId());
		
		Assert.assertEquals(dto.getIps(), entity.getIps());
		Assert.assertEquals(dto.getServiciosAsociados(), entity.getServiciosAsociados());
		Assert.assertEquals(dto.getVersion(), entity.getVersion());
		Assert.assertEquals(dto.getSistemaOperativo(), entity.getSistemaOperativo());
		Assert.assertEquals(dto.getNumDiscos(), entity.getNumDiscos());
		Assert.assertEquals(dto.getCapacidadDiscos(), entity.getCapacidadDiscos());
		Assert.assertEquals(dto.getRam(), entity.getRam());
		Assert.assertEquals(dto.getNumCores(), entity.getNumCores());
                Assert.assertEquals(parseDate(dto.getFechaVencimiento()), entity.getFechaVencimiento());	
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getDescripcion(), entity.getDescripcion());
		Assert.assertEquals(dto.getProposito(), entity.getProposito());
                Assert.assertEquals(parseDate(dto.getFechaCreacion()), entity.getFechaCreacion());	
		Assert.assertEquals(dto.getDestruido(), entity.getDestruido());
		Assert.assertEquals(dto.getCaracteristicas(), entity.getCaracteristicas());
		Assert.assertEquals(dto.getEncargadoId(), entity.getEncargadoId());
                
                //Probar que exista el entity Encargadowiki
                EncargadomaquinaVirtualEntity encargado1 = em.find(EncargadomaquinaVirtualEntity.class,dto.getEncargadoId());
                EncargadomaquinaVirtualEntity encargado2 = em.find(EncargadomaquinaVirtualEntity.class,dto.getId());
            
                Assert.assertNotNull(encargado1);
                Assert.assertNotNull(encargado2);
        }
        
        @Test
        public void agregarEncargadoMaquinaVirtualTest2(){
                MaquinaVirtualDTO dto=new MaquinaVirtualDTO();
		dto.setIps(generateRandom(String.class));
		dto.setServiciosAsociados(generateRandom(String.class));
		dto.setVersion(generateRandom(String.class));
		dto.setSistemaOperativo(generateRandom(String.class));
		dto.setNumDiscos(generateRandom(Integer.class));
		dto.setCapacidadDiscos(generateRandom(Long.class));
		dto.setRam(generateRandom(String.class));
		dto.setNumCores(generateRandom(Integer.class));
                dto.setFechaVencimiento(generateRandomDate());
		dto.setName(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		dto.setProposito(generateRandom(String.class));
                dto.setFechaCreacion(generateRandomDate());
		dto.setDestruido(generateRandom(Boolean.class));
		dto.setCaracteristicas(generateRandom(String.class));
		//dto.setEncargadoId(generateRandom(Long.class));
		
		MaquinaVirtualDTO result=maquinaVirtualPersistence.createMaquinaVirtual(dto);
		
		Assert.assertNotNull(result);
		
		MaquinaVirtualEntity entity=em.find(MaquinaVirtualEntity.class, result.getId());
		
		Assert.assertEquals(dto.getIps(), entity.getIps());
		Assert.assertEquals(dto.getServiciosAsociados(), entity.getServiciosAsociados());
		Assert.assertEquals(dto.getVersion(), entity.getVersion());
		Assert.assertEquals(dto.getSistemaOperativo(), entity.getSistemaOperativo());
		Assert.assertEquals(dto.getNumDiscos(), entity.getNumDiscos());
		Assert.assertEquals(dto.getCapacidadDiscos(), entity.getCapacidadDiscos());
		Assert.assertEquals(dto.getRam(), entity.getRam());
		Assert.assertEquals(dto.getNumCores(), entity.getNumCores());
                Assert.assertEquals(parseDate(dto.getFechaVencimiento()), entity.getFechaVencimiento());	
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getDescripcion(), entity.getDescripcion());
		Assert.assertEquals(dto.getProposito(), entity.getProposito());
                Assert.assertEquals(parseDate(dto.getFechaCreacion()), entity.getFechaCreacion());	
		Assert.assertEquals(dto.getDestruido(), entity.getDestruido());
		Assert.assertEquals(dto.getCaracteristicas(), entity.getCaracteristicas());
		//Assert.assertEquals(dto.getEncargadoId(), entity.getEncargadoId());
                
                //Probar que NO exista el entity Encargadowiki
                EncargadomaquinaVirtualEntity encargado1 = em.find(EncargadomaquinaVirtualEntity.class,dto.getEncargadoId());
                EncargadomaquinaVirtualEntity encargado2 = em.find(EncargadomaquinaVirtualEntity.class,dto.getId());
            
                Assert.assertNull(encargado1);
                Assert.assertNull(encargado2);
        }
}