/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.paginaweb.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.grupo.paginaweb.logic.dto.PaginaWebPageDTO;
import co.edu.uniandes.csw.grupo.paginaweb.logic.dto.PaginaWebDTO;
import co.edu.uniandes.csw.grupo.paginaweb.persistence.api.IPaginaWebPersistence;
import co.edu.uniandes.csw.grupo.paginaweb.persistence.entity.PaginaWebEntity;
import co.edu.uniandes.csw.grupo.paginaweb.persistence.converter.PaginaWebConverter;
import static co.edu.uniandes.csw.grupo.util._TestUtil.*;

@RunWith(Arquillian.class)
public class PaginaWebPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(PaginaWebPersistence.class.getPackage())
				.addPackage(PaginaWebEntity.class.getPackage())
				.addPackage(IPaginaWebPersistence.class.getPackage())
                .addPackage(PaginaWebDTO.class.getPackage())
                .addPackage(PaginaWebConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IPaginaWebPersistence paginaWebPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from PaginaWebEntity").executeUpdate();
	}

	private List<PaginaWebEntity> data=new ArrayList<PaginaWebEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			PaginaWebEntity entity=new PaginaWebEntity();
			entity.setFormato(generateRandom(String.class));
			entity.setUltimaFechaModificacion(generateRandom(Date.class));
			entity.setUrl(generateRandom(String.class));
			entity.setAlias(generateRandom(String.class));
			entity.setName(generateRandom(String.class));
			entity.setDescripcion(generateRandom(String.class));
			entity.setProposito(generateRandom(String.class));
			entity.setFechaCreacion(generateRandom(Date.class));
			entity.setDestruido(generateRandom(Boolean.class));
			entity.setCaracteristicas(generateRandom(String.class));
			entity.setCmsId(generateRandom(Long.class));
			entity.setEncargadoId(generateRandom(Long.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createPaginaWebTest(){
		PaginaWebDTO dto=new PaginaWebDTO();
		dto.setFormato(generateRandom(String.class));
dto.setUltimaFechaModificacion(generateRandomDate());
		dto.setUrl(generateRandom(String.class));
		dto.setAlias(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		dto.setProposito(generateRandom(String.class));
dto.setFechaCreacion(generateRandomDate());
		dto.setDestruido(generateRandom(Boolean.class));
		dto.setCaracteristicas(generateRandom(String.class));
		dto.setCmsId(generateRandom(Long.class));
		dto.setEncargadoId(generateRandom(Long.class));
		
		PaginaWebDTO result=paginaWebPersistence.createPaginaWeb(dto);
		
		Assert.assertNotNull(result);
		
		PaginaWebEntity entity=em.find(PaginaWebEntity.class, result.getId());
		
		Assert.assertEquals(dto.getFormato(), entity.getFormato());
Assert.assertEquals(parseDate(dto.getUltimaFechaModificacion()), entity.getUltimaFechaModificacion());	
		Assert.assertEquals(dto.getUrl(), entity.getUrl());
		Assert.assertEquals(dto.getAlias(), entity.getAlias());
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getDescripcion(), entity.getDescripcion());
		Assert.assertEquals(dto.getProposito(), entity.getProposito());
Assert.assertEquals(parseDate(dto.getFechaCreacion()), entity.getFechaCreacion());	
		Assert.assertEquals(dto.getDestruido(), entity.getDestruido());
		Assert.assertEquals(dto.getCaracteristicas(), entity.getCaracteristicas());
		Assert.assertEquals(dto.getCmsId(), entity.getCmsId());
		Assert.assertEquals(dto.getEncargadoId(), entity.getEncargadoId());
	}
	
	@Test
	public void getPaginaWebsTest(){
		List<PaginaWebDTO> list=paginaWebPersistence.getPaginaWebs();
		Assert.assertEquals(list.size(), data.size());
        for(PaginaWebDTO dto:list){
        	boolean found=false;
            for(PaginaWebEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getPaginaWebTest(){
		PaginaWebEntity entity=data.get(0);
		PaginaWebDTO dto=paginaWebPersistence.getPaginaWeb(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getFormato(), dto.getFormato());
		Assert.assertEquals(entity.getUrl(), dto.getUrl());
		Assert.assertEquals(entity.getAlias(), dto.getAlias());
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getDescripcion(), dto.getDescripcion());
		Assert.assertEquals(entity.getProposito(), dto.getProposito());
		Assert.assertEquals(entity.getDestruido(), dto.getDestruido());
		Assert.assertEquals(entity.getCaracteristicas(), dto.getCaracteristicas());
		Assert.assertEquals(entity.getCmsId(), dto.getCmsId());
		Assert.assertEquals(entity.getEncargadoId(), dto.getEncargadoId());
        
	}
	
	@Test
	public void deletePaginaWebTest(){
		PaginaWebEntity entity=data.get(0);
		paginaWebPersistence.deletePaginaWeb(entity.getId());
        PaginaWebEntity deleted=em.find(PaginaWebEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updatePaginaWebTest(){
		PaginaWebEntity entity=data.get(0);
		
		PaginaWebDTO dto=new PaginaWebDTO();
		dto.setId(entity.getId());
		dto.setFormato(generateRandom(String.class));
dto.setUltimaFechaModificacion(generateRandomDate());
		dto.setUrl(generateRandom(String.class));
		dto.setAlias(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		dto.setProposito(generateRandom(String.class));
dto.setFechaCreacion(generateRandomDate());
		dto.setDestruido(generateRandom(Boolean.class));
		dto.setCaracteristicas(generateRandom(String.class));
		dto.setCmsId(generateRandom(Long.class));
		dto.setEncargadoId(generateRandom(Long.class));
		
		
		paginaWebPersistence.updatePaginaWeb(dto);
		
		
		PaginaWebEntity resp=em.find(PaginaWebEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getFormato(), resp.getFormato());	
Assert.assertEquals(parseDate(dto.getUltimaFechaModificacion()), resp.getUltimaFechaModificacion());
		Assert.assertEquals(dto.getUrl(), resp.getUrl());	
		Assert.assertEquals(dto.getAlias(), resp.getAlias());	
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getDescripcion(), resp.getDescripcion());	
		Assert.assertEquals(dto.getProposito(), resp.getProposito());	
Assert.assertEquals(parseDate(dto.getFechaCreacion()), resp.getFechaCreacion());
		Assert.assertEquals(dto.getDestruido(), resp.getDestruido());	
		Assert.assertEquals(dto.getCaracteristicas(), resp.getCaracteristicas());	
		Assert.assertEquals(dto.getCmsId(), resp.getCmsId());	
		Assert.assertEquals(dto.getEncargadoId(), resp.getEncargadoId());	
	}
	
	@Test
	public void getPaginaWebPaginationTest(){
		//Page 1
		PaginaWebPageDTO dto1=paginaWebPersistence.getPaginaWebs(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        PaginaWebPageDTO dto2=paginaWebPersistence.getPaginaWebs(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(PaginaWebDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(PaginaWebEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(PaginaWebDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(PaginaWebEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}