/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.softwaresalas.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.grupo.softwaresalas.logic.dto.SoftwareSalasDTO;
import co.edu.uniandes.csw.grupo.softwaresalas.logic.dto.SoftwareSalasPageDTO;
import co.edu.uniandes.csw.grupo.softwaresalas.persistence.api._ISoftwareSalasPersistence;
import co.edu.uniandes.csw.grupo.softwaresalas.persistence.converter.SoftwareSalasConverter;
import co.edu.uniandes.csw.grupo.softwaresalas.persistence.entity.SoftwareSalasEntity;

public abstract class _SoftwareSalasPersistence implements _ISoftwareSalasPersistence {

  	@PersistenceContext(unitName="RigitalAppPU")
 
	protected EntityManager entityManager;
	
	public SoftwareSalasDTO createSoftwareSalas(SoftwareSalasDTO softwareSalas) {
		SoftwareSalasEntity entity=SoftwareSalasConverter.persistenceDTO2Entity(softwareSalas);
		entityManager.persist(entity);
		return SoftwareSalasConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<SoftwareSalasDTO> getSoftwareSalass() {
		Query q = entityManager.createQuery("select u from SoftwareSalasEntity u");
		return SoftwareSalasConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public SoftwareSalasPageDTO getSoftwareSalass(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from SoftwareSalasEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from SoftwareSalasEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		SoftwareSalasPageDTO response = new SoftwareSalasPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(SoftwareSalasConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public SoftwareSalasDTO getSoftwareSalas(Long id) {
		return SoftwareSalasConverter.entity2PersistenceDTO(entityManager.find(SoftwareSalasEntity.class, id));
	}

	public void deleteSoftwareSalas(Long id) {
		SoftwareSalasEntity entity=entityManager.find(SoftwareSalasEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateSoftwareSalas(SoftwareSalasDTO detail) {
		SoftwareSalasEntity entity=entityManager.merge(SoftwareSalasConverter.persistenceDTO2Entity(detail));
		SoftwareSalasConverter.entity2PersistenceDTO(entity);
	}

}