/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.repositorio.service;

import co.edu.uniandes.csw.grupo.maquinavirtual.logic.dto.MaquinaVirtualPageDTO;
import co.edu.uniandes.csw.grupo.repositorio.logic.dto.RepositorioPageDTO;
import java.util.List;

import javax.ejb.Stateless;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.MultivaluedMap;
import javax.ws.rs.core.UriInfo;

@Path("/Repositorio")
@Stateless
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public class RepositorioService extends _RepositorioService {

    @Context
    UriInfo uriInfo;
    
    @GET
    @Override
    public RepositorioPageDTO getRepositorios(@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords){
        System.out.println("Acceso!!!!!!!!!!!!!!!!!!");
		return super.getRepositorios(page, maxRecords);
    }
    
    @GET
    @Path("/Search")
    public RepositorioPageDTO searchRepositorios(@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords){
        
        MultivaluedMap<String, String> queryParams = uriInfo.getQueryParameters();
        
        System.out.println(queryParams.keySet());
        System.out.println(queryParams.values());
        
        // Estos atributos podrán ser vacios o tener valores
        // Si estan vacíos no se incluirán en la búsqueda
        
        String tipo = queryParams.getFirst("tipo");
        String servidor = queryParams.getFirst("servidor");
        String destino = queryParams.getFirst("destino");        
        String tipoAcceso = queryParams.getFirst("tipoAcceso");
        String ubicacionDelServidor = queryParams.getFirst("ubicacionDelServidor");
        String url = queryParams.getFirst("url");
        String name = queryParams.getFirst("name");
        String descripcion = queryParams.getFirst("descripcion");
        String proposito = queryParams.getFirst("proposito");
        String caracteristicas = queryParams.getFirst("caracteristicas");
        String encargadoId = queryParams.getFirst("encargadoId");

       
        // Estos atributos, en cambio, siempre poseeran valores estándar.
        // Se debe aclarar eso en el manual de uso.
                       
        String fechaCreac1 = queryParams.getFirst("fechaCreacion");
        String fechaCreac2 = queryParams.getFirst("fechaCreacion2");
        
        String fechaVenc1 = queryParams.getFirst("fechaVencimiento");
        String fechaVenc2 = queryParams.getFirst("fechaVencimiento2");
        
        String destruido = queryParams.getFirst("destruido");
        
        String estaDestruido = "";

        
        if(tipo == null)
            tipo = "";
        if(servidor == null)
            servidor = "";
        if(destino == null)
            destino = "";
        if(tipoAcceso == null)
            tipoAcceso = "";
        if(ubicacionDelServidor == null)
            ubicacionDelServidor = "";
        if(url == null)
            url = "";
        if(name == null)
            name = "";
        if(descripcion == null)
            descripcion = "";
        if(proposito == null)
            proposito = "";
        if(caracteristicas == null)
            caracteristicas = "";
        if(encargadoId == null)
            encargadoId = "";
        if(destruido == null)
            destruido = "";
               
        String fechaCreacion1 = "";
        String fechaCreacion2 = "";
        
        if(!fechaCreac1.isEmpty() && fechaCreac1 != null)
        {
            String[] date1 = fechaCreac1.split("%2F");
            fechaCreacion1 = date1[2] + "-" + date1[1] + "-" + date1[0];
        }       
        
        if(!fechaCreac2.isEmpty() && fechaCreac2 != null)
        {
            String[] date2 = fechaCreac2.split("%2F");            
            fechaCreacion2 = date2[2] + "-" + date2[1] + "-" + date2[0];

        }
        
        String fechaVencimiento1 = "";
        String fechaVencimiento2 = "";
        
        if(!fechaVenc1.isEmpty() && fechaVenc1 != null)
        {
            String[] date1 = fechaVenc1.split("%2F");
            fechaVencimiento1 = date1[2] + "-" + date1[1] + "-" + date1[0];
        }       
        
        if(!fechaVenc2.isEmpty() && fechaVenc2 != null)
        {
            String[] date2 = fechaVenc2.split("%2F");            
            fechaVencimiento2 = date2[2] + "-" + date2[1] + "-" + date2[0];

        }
        
        if(destruido == null)       
            estaDestruido = "0";
        else
            estaDestruido = "1";   
        
        
        return repositorioLogicService.getRepositoriosByParameters(tipo , servidor , destino , tipoAcceso , ubicacionDelServidor , url , name , descripcion , proposito , caracteristicas , encargadoId , fechaCreacion1, fechaCreacion2, fechaVencimiento1, fechaVencimiento2, estaDestruido);
    }

}