/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.encargado.master.persistence.entity;

import co.edu.uniandes.csw.grupo.repositorio.persistence.entity.RepositorioEntity;
import co.edu.uniandes.csw.grupo.encargado.persistence.entity.EncargadoEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(EncargadorepositorioEntityId.class)
@NamedQueries({
    @NamedQuery(name = "EncargadorepositorioEntity.getByMasterId", query = "SELECT  u FROM EncargadorepositorioEntity u WHERE u.encargadoId=:encargadoId"),
    @NamedQuery(name = "EncargadorepositorioEntity.deleteEncargadorepositorioEntity", query = "DELETE FROM EncargadorepositorioEntity u WHERE u.encargadoId=:encargadoId and  u.repositorioId=:repositorioId")
})
public class EncargadorepositorioEntity implements Serializable {

    @Id
    @Column(name = "encargadoId")
    private Long encargadoId;
    @Id
    @Column(name = "repositorioId")
    private Long repositorioId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "encargadoId", referencedColumnName = "id")
    @JoinFetch
    private RepositorioEntity encargadoIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "repositorioId", referencedColumnName = "id")
    @JoinFetch
    private RepositorioEntity repositorioIdEntity; 

    public EncargadorepositorioEntity() {
    }

    public EncargadorepositorioEntity(Long encargadoId, Long repositorioId) {
        this.encargadoId =encargadoId;
        this.repositorioId = repositorioId;
    }

    public Long getEncargadoId() {
        return encargadoId;
    }

    public void setEncargadoId(Long encargadoId) {
        this.encargadoId = encargadoId;
    }

    public Long getRepositorioId() {
        return repositorioId;
    }

    public void setRepositorioId(Long repositorioId) {
        this.repositorioId = repositorioId;
    }

    public RepositorioEntity getEncargadoIdEntity() {
        return encargadoIdEntity;
    }

    public void setEncargadoIdEntity(RepositorioEntity encargadoIdEntity) {
        this.encargadoIdEntity = encargadoIdEntity;
    }

    public RepositorioEntity getRepositorioIdEntity() {
        return repositorioIdEntity;
    }

    public void setRepositorioIdEntity(RepositorioEntity repositorioIdEntity) {
        this.repositorioIdEntity = repositorioIdEntity;
    }

}
