/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.unidaddered.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.grupo.unidaddered.logic.dto.UnidadDeRedPageDTO;
import co.edu.uniandes.csw.grupo.unidaddered.logic.dto.UnidadDeRedDTO;
import co.edu.uniandes.csw.grupo.unidaddered.logic.api.IUnidadDeRedLogicService;
import co.edu.uniandes.csw.grupo.unidaddered.persistence.UnidadDeRedPersistence;
import co.edu.uniandes.csw.grupo.unidaddered.persistence.api.IUnidadDeRedPersistence;
import co.edu.uniandes.csw.grupo.unidaddered.persistence.entity.UnidadDeRedEntity;
import co.edu.uniandes.csw.grupo.unidaddered.persistence.converter.UnidadDeRedConverter;
import static co.edu.uniandes.csw.grupo.util._TestUtil.*;

@RunWith(Arquillian.class)
public class UnidadDeRedLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(UnidadDeRedLogicService.class.getPackage())
				.addPackage(IUnidadDeRedLogicService.class.getPackage())
				.addPackage(UnidadDeRedPersistence.class.getPackage())
				.addPackage(UnidadDeRedEntity.class.getPackage())
				.addPackage(IUnidadDeRedPersistence.class.getPackage())
                .addPackage(UnidadDeRedDTO.class.getPackage())
                .addPackage(UnidadDeRedConverter.class.getPackage())
                .addPackage(UnidadDeRedEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IUnidadDeRedLogicService unidadDeRedLogicService;
	
	@Inject
	private IUnidadDeRedPersistence unidadDeRedPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<UnidadDeRedDTO> dtos=unidadDeRedPersistence.getUnidadDeReds();
		for(UnidadDeRedDTO dto:dtos){
			unidadDeRedPersistence.deleteUnidadDeRed(dto.getId());
		}
	}

	private List<UnidadDeRedDTO> data=new ArrayList<UnidadDeRedDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			UnidadDeRedDTO pdto=new UnidadDeRedDTO();
			pdto.setTipos(generateRandom(String.class));
			pdto.setServidor(generateRandom(String.class));
			pdto.setUrl(generateRandom(String.class));
			pdto.setName(generateRandom(String.class));
			pdto.setDescripcion(generateRandom(String.class));
			pdto.setProposito(generateRandom(String.class));
			pdto.setFechaCreacion(generateRandomDate());
			pdto.setDestruido(generateRandom(Boolean.class));
			pdto.setCaracteristicas(generateRandom(String.class));
			pdto.setEncargadoId(generateRandom(Long.class));
			pdto=unidadDeRedPersistence.createUnidadDeRed(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createUnidadDeRedTest(){
		UnidadDeRedDTO ldto=new UnidadDeRedDTO();
		ldto.setTipos(generateRandom(String.class));
		ldto.setServidor(generateRandom(String.class));
		ldto.setUrl(generateRandom(String.class));
		ldto.setName(generateRandom(String.class));
		ldto.setDescripcion(generateRandom(String.class));
		ldto.setProposito(generateRandom(String.class));
		ldto.setFechaCreacion(generateRandomDate());
		ldto.setDestruido(generateRandom(Boolean.class));
		ldto.setCaracteristicas(generateRandom(String.class));
		ldto.setEncargadoId(generateRandom(Long.class));
		
		
		UnidadDeRedDTO result=unidadDeRedLogicService.createUnidadDeRed(ldto);
		
		Assert.assertNotNull(result);
		
		UnidadDeRedDTO pdto=unidadDeRedPersistence.getUnidadDeRed(result.getId());
		
		Assert.assertEquals(ldto.getTipos(), pdto.getTipos());	
		Assert.assertEquals(ldto.getServidor(), pdto.getServidor());	
		Assert.assertEquals(ldto.getUrl(), pdto.getUrl());	
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getDescripcion(), pdto.getDescripcion());	
		Assert.assertEquals(ldto.getProposito(), pdto.getProposito());	
		Assert.assertEquals(ldto.getFechaCreacion(), pdto.getFechaCreacion());	
		Assert.assertEquals(ldto.getDestruido(), pdto.getDestruido());	
		Assert.assertEquals(ldto.getCaracteristicas(), pdto.getCaracteristicas());	
		Assert.assertEquals(ldto.getEncargadoId(), pdto.getEncargadoId());	
	}
	
	@Test
	public void getUnidadDeRedsTest(){
		List<UnidadDeRedDTO> list=unidadDeRedLogicService.getUnidadDeReds();
		Assert.assertEquals(list.size(), data.size());
        for(UnidadDeRedDTO ldto:list){
        	boolean found=false;
            for(UnidadDeRedDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getUnidadDeRedTest(){
		UnidadDeRedDTO pdto=data.get(0);
		UnidadDeRedDTO ldto=unidadDeRedLogicService.getUnidadDeRed(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getTipos(), ldto.getTipos());
		Assert.assertEquals(pdto.getServidor(), ldto.getServidor());
		Assert.assertEquals(pdto.getUrl(), ldto.getUrl());
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getDescripcion(), ldto.getDescripcion());
		Assert.assertEquals(pdto.getProposito(), ldto.getProposito());
		Assert.assertEquals(pdto.getFechaCreacion(), ldto.getFechaCreacion());
		Assert.assertEquals(pdto.getDestruido(), ldto.getDestruido());
		Assert.assertEquals(pdto.getCaracteristicas(), ldto.getCaracteristicas());
		Assert.assertEquals(pdto.getEncargadoId(), ldto.getEncargadoId());
        
	}
	
	@Test
	public void deleteUnidadDeRedTest(){
		UnidadDeRedDTO pdto=data.get(0);
		unidadDeRedLogicService.deleteUnidadDeRed(pdto.getId());
        UnidadDeRedDTO deleted=unidadDeRedPersistence.getUnidadDeRed(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateUnidadDeRedTest(){
		UnidadDeRedDTO pdto=data.get(0);
		
		UnidadDeRedDTO ldto=new UnidadDeRedDTO();
		ldto.setId(pdto.getId());
		ldto.setTipos(generateRandom(String.class));
		ldto.setServidor(generateRandom(String.class));
		ldto.setUrl(generateRandom(String.class));
		ldto.setName(generateRandom(String.class));
		ldto.setDescripcion(generateRandom(String.class));
		ldto.setProposito(generateRandom(String.class));
		ldto.setFechaCreacion(generateRandomDate());
		ldto.setDestruido(generateRandom(Boolean.class));
		ldto.setCaracteristicas(generateRandom(String.class));
		ldto.setEncargadoId(generateRandom(Long.class));
		
		
		unidadDeRedLogicService.updateUnidadDeRed(ldto);
		
		
		UnidadDeRedDTO resp=unidadDeRedPersistence.getUnidadDeRed(pdto.getId());
		
		Assert.assertEquals(ldto.getTipos(), resp.getTipos());	
		Assert.assertEquals(ldto.getServidor(), resp.getServidor());	
		Assert.assertEquals(ldto.getUrl(), resp.getUrl());	
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getDescripcion(), resp.getDescripcion());	
		Assert.assertEquals(ldto.getProposito(), resp.getProposito());	
		Assert.assertEquals(ldto.getFechaCreacion(), resp.getFechaCreacion());	
		Assert.assertEquals(ldto.getDestruido(), resp.getDestruido());	
		Assert.assertEquals(ldto.getCaracteristicas(), resp.getCaracteristicas());	
		Assert.assertEquals(ldto.getEncargadoId(), resp.getEncargadoId());	
	}
	
	@Test
	public void getUnidadDeRedPaginationTest(){
		
		UnidadDeRedPageDTO dto1=unidadDeRedLogicService.getUnidadDeReds(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		UnidadDeRedPageDTO dto2=unidadDeRedLogicService.getUnidadDeReds(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(UnidadDeRedDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(UnidadDeRedDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(UnidadDeRedDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(UnidadDeRedDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        UnidadDeRedPageDTO dto3=unidadDeRedLogicService.getUnidadDeReds(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(UnidadDeRedDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(UnidadDeRedDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}