/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.sqldev.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.grupo.sqldev.logic.dto.SQLDevPageDTO;
import co.edu.uniandes.csw.grupo.sqldev.logic.dto.SQLDevDTO;
import co.edu.uniandes.csw.grupo.sqldev.logic.api.ISQLDevLogicService;
import co.edu.uniandes.csw.grupo.sqldev.persistence.SQLDevPersistence;
import co.edu.uniandes.csw.grupo.sqldev.persistence.api.ISQLDevPersistence;
import co.edu.uniandes.csw.grupo.sqldev.persistence.entity.SQLDevEntity;
import co.edu.uniandes.csw.grupo.sqldev.persistence.converter.SQLDevConverter;
import static co.edu.uniandes.csw.grupo.util._TestUtil.*;

@RunWith(Arquillian.class)
public class SQLDevLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(SQLDevLogicService.class.getPackage())
				.addPackage(ISQLDevLogicService.class.getPackage())
				.addPackage(SQLDevPersistence.class.getPackage())
				.addPackage(SQLDevEntity.class.getPackage())
				.addPackage(ISQLDevPersistence.class.getPackage())
                .addPackage(SQLDevDTO.class.getPackage())
                .addPackage(SQLDevConverter.class.getPackage())
                .addPackage(SQLDevEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private ISQLDevLogicService sQLDevLogicService;
	
	@Inject
	private ISQLDevPersistence sQLDevPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<SQLDevDTO> dtos=sQLDevPersistence.getSQLDevs();
		for(SQLDevDTO dto:dtos){
			sQLDevPersistence.deleteSQLDev(dto.getId());
		}
	}

	private List<SQLDevDTO> data=new ArrayList<SQLDevDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			SQLDevDTO pdto=new SQLDevDTO();
			pdto.setFechaVencimiento(generateRandomDate());
			pdto.setServidor(generateRandom(String.class));
			pdto.setName(generateRandom(String.class));
			pdto.setDescripcion(generateRandom(String.class));
			pdto.setProposito(generateRandom(String.class));
			pdto.setFechaCreacion(generateRandomDate());
			pdto.setDestruido(generateRandom(Boolean.class));
			pdto.setCaracteristicas(generateRandom(String.class));
			pdto.setPgwebId(generateRandom(Long.class));
			pdto.setEncargadoId(generateRandom(Long.class));
			pdto=sQLDevPersistence.createSQLDev(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createSQLDevTest(){
		SQLDevDTO ldto=new SQLDevDTO();
		ldto.setFechaVencimiento(generateRandomDate());
		ldto.setServidor(generateRandom(String.class));
		ldto.setName(generateRandom(String.class));
		ldto.setDescripcion(generateRandom(String.class));
		ldto.setProposito(generateRandom(String.class));
		ldto.setFechaCreacion(generateRandomDate());
		ldto.setDestruido(generateRandom(Boolean.class));
		ldto.setCaracteristicas(generateRandom(String.class));
		ldto.setPgwebId(generateRandom(Long.class));
		ldto.setEncargadoId(generateRandom(Long.class));
		
		
		SQLDevDTO result=sQLDevLogicService.createSQLDev(ldto);
		
		Assert.assertNotNull(result);
		
		SQLDevDTO pdto=sQLDevPersistence.getSQLDev(result.getId());
		
		Assert.assertEquals(ldto.getFechaVencimiento(), pdto.getFechaVencimiento());	
		Assert.assertEquals(ldto.getServidor(), pdto.getServidor());	
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getDescripcion(), pdto.getDescripcion());	
		Assert.assertEquals(ldto.getProposito(), pdto.getProposito());	
		Assert.assertEquals(ldto.getFechaCreacion(), pdto.getFechaCreacion());	
		Assert.assertEquals(ldto.getDestruido(), pdto.getDestruido());	
		Assert.assertEquals(ldto.getCaracteristicas(), pdto.getCaracteristicas());	
		Assert.assertEquals(ldto.getPgwebId(), pdto.getPgwebId());	
		Assert.assertEquals(ldto.getEncargadoId(), pdto.getEncargadoId());	
	}
	
	@Test
	public void getSQLDevsTest(){
		List<SQLDevDTO> list=sQLDevLogicService.getSQLDevs();
		Assert.assertEquals(list.size(), data.size());
        for(SQLDevDTO ldto:list){
        	boolean found=false;
            for(SQLDevDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getSQLDevTest(){
		SQLDevDTO pdto=data.get(0);
		SQLDevDTO ldto=sQLDevLogicService.getSQLDev(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getFechaVencimiento(), ldto.getFechaVencimiento());
		Assert.assertEquals(pdto.getServidor(), ldto.getServidor());
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getDescripcion(), ldto.getDescripcion());
		Assert.assertEquals(pdto.getProposito(), ldto.getProposito());
		Assert.assertEquals(pdto.getFechaCreacion(), ldto.getFechaCreacion());
		Assert.assertEquals(pdto.getDestruido(), ldto.getDestruido());
		Assert.assertEquals(pdto.getCaracteristicas(), ldto.getCaracteristicas());
		Assert.assertEquals(pdto.getPgwebId(), ldto.getPgwebId());
		Assert.assertEquals(pdto.getEncargadoId(), ldto.getEncargadoId());
        
	}
	
	@Test
	public void deleteSQLDevTest(){
		SQLDevDTO pdto=data.get(0);
		sQLDevLogicService.deleteSQLDev(pdto.getId());
        SQLDevDTO deleted=sQLDevPersistence.getSQLDev(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateSQLDevTest(){
		SQLDevDTO pdto=data.get(0);
		
		SQLDevDTO ldto=new SQLDevDTO();
		ldto.setId(pdto.getId());
		ldto.setFechaVencimiento(generateRandomDate());
		ldto.setServidor(generateRandom(String.class));
		ldto.setName(generateRandom(String.class));
		ldto.setDescripcion(generateRandom(String.class));
		ldto.setProposito(generateRandom(String.class));
		ldto.setFechaCreacion(generateRandomDate());
		ldto.setDestruido(generateRandom(Boolean.class));
		ldto.setCaracteristicas(generateRandom(String.class));
		ldto.setPgwebId(generateRandom(Long.class));
		ldto.setEncargadoId(generateRandom(Long.class));
		
		
		sQLDevLogicService.updateSQLDev(ldto);
		
		
		SQLDevDTO resp=sQLDevPersistence.getSQLDev(pdto.getId());
		
		Assert.assertEquals(ldto.getFechaVencimiento(), resp.getFechaVencimiento());	
		Assert.assertEquals(ldto.getServidor(), resp.getServidor());	
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getDescripcion(), resp.getDescripcion());	
		Assert.assertEquals(ldto.getProposito(), resp.getProposito());	
		Assert.assertEquals(ldto.getFechaCreacion(), resp.getFechaCreacion());	
		Assert.assertEquals(ldto.getDestruido(), resp.getDestruido());	
		Assert.assertEquals(ldto.getCaracteristicas(), resp.getCaracteristicas());	
		Assert.assertEquals(ldto.getPgwebId(), resp.getPgwebId());	
		Assert.assertEquals(ldto.getEncargadoId(), resp.getEncargadoId());	
	}
	
	@Test
	public void getSQLDevPaginationTest(){
		
		SQLDevPageDTO dto1=sQLDevLogicService.getSQLDevs(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		SQLDevPageDTO dto2=sQLDevLogicService.getSQLDevs(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(SQLDevDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(SQLDevDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(SQLDevDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(SQLDevDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        SQLDevPageDTO dto3=sQLDevLogicService.getSQLDevs(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(SQLDevDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(SQLDevDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}