/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.recurso.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.grupo.recurso.logic.dto.RecursoDTO;
import co.edu.uniandes.csw.grupo.recurso.logic.dto.RecursoPageDTO;
import co.edu.uniandes.csw.grupo.recurso.logic.api._IRecursoLogicService;

public abstract class _RecursoMockLogicService implements _IRecursoLogicService {

	private Long id= new Long(1);
	protected List<RecursoDTO> data=new ArrayList<RecursoDTO>();

	public RecursoDTO createRecurso(RecursoDTO recurso){
		id++;
		recurso.setId(id);
		data.add(recurso);
		return recurso;
    }
    
    public List<RecursoDTO> getRecursos(){
		return data; 
	}

	public RecursoPageDTO getRecursos(Integer page, Integer maxRecords){
		RecursoPageDTO response = new RecursoPageDTO();
		response.setTotalRecords(Long.parseLong(data.size()+""));
		response.setRecords(data);
		return response;
	}

	public RecursoDTO getRecurso(Long id){
		for(RecursoDTO data1:data){
			if(data1.getId().equals(id)){
				return data1;
			}
		}
		return null;
	}

	public void deleteRecurso(Long id){
	    RecursoDTO delete=null;
		for(RecursoDTO data1:data){
			if(data1.getId().equals(id)){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
		} 
	}

	public void updateRecurso(RecursoDTO recurso){
	    RecursoDTO delete=null;
		for(RecursoDTO data1:data){
			if(data1.getId().equals(id)){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
			data.add(recurso);
		} 
	}	
}