/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.contenedorweb.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.grupo.contenedorweb.logic.dto.ContenedorWebPageDTO;
import co.edu.uniandes.csw.grupo.contenedorweb.logic.dto.ContenedorWebDTO;
import co.edu.uniandes.csw.grupo.contenedorweb.persistence.api.IContenedorWebPersistence;
import co.edu.uniandes.csw.grupo.contenedorweb.persistence.entity.ContenedorWebEntity;
import co.edu.uniandes.csw.grupo.contenedorweb.persistence.converter.ContenedorWebConverter;
import static co.edu.uniandes.csw.grupo.util._TestUtil.*;

@RunWith(Arquillian.class)
public class ContenedorWebPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(ContenedorWebPersistence.class.getPackage())
				.addPackage(ContenedorWebEntity.class.getPackage())
				.addPackage(IContenedorWebPersistence.class.getPackage())
                .addPackage(ContenedorWebDTO.class.getPackage())
                .addPackage(ContenedorWebConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IContenedorWebPersistence contenedorWebPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from ContenedorWebEntity").executeUpdate();
	}

	private List<ContenedorWebEntity> data=new ArrayList<ContenedorWebEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			ContenedorWebEntity entity=new ContenedorWebEntity();
			entity.setPuertos(generateRandom(String.class));
			entity.setServidor(generateRandom(String.class));
			entity.setUrl(generateRandom(String.class));
			entity.setFechaVencimiento(generateRandom(Date.class));
			entity.setName(generateRandom(String.class));
			entity.setDescripcion(generateRandom(String.class));
			entity.setProposito(generateRandom(String.class));
			entity.setFechaCreacion(generateRandom(Date.class));
			entity.setDestruido(generateRandom(Boolean.class));
			entity.setCaracteristicas(generateRandom(String.class));
			entity.setEncargadoId(generateRandom(Long.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createContenedorWebTest(){
		ContenedorWebDTO dto=new ContenedorWebDTO();
		dto.setPuertos(generateRandom(String.class));
		dto.setServidor(generateRandom(String.class));
		dto.setUrl(generateRandom(String.class));
dto.setFechaVencimiento(generateRandomDate());
		dto.setName(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		dto.setProposito(generateRandom(String.class));
dto.setFechaCreacion(generateRandomDate());
		dto.setDestruido(generateRandom(Boolean.class));
		dto.setCaracteristicas(generateRandom(String.class));
		dto.setEncargadoId(generateRandom(Long.class));
		
		ContenedorWebDTO result=contenedorWebPersistence.createContenedorWeb(dto);
		
		Assert.assertNotNull(result);
		
		ContenedorWebEntity entity=em.find(ContenedorWebEntity.class, result.getId());
		
		Assert.assertEquals(dto.getPuertos(), entity.getPuertos());
		Assert.assertEquals(dto.getServidor(), entity.getServidor());
		Assert.assertEquals(dto.getUrl(), entity.getUrl());
Assert.assertEquals(parseDate(dto.getFechaVencimiento()), entity.getFechaVencimiento());	
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getDescripcion(), entity.getDescripcion());
		Assert.assertEquals(dto.getProposito(), entity.getProposito());
Assert.assertEquals(parseDate(dto.getFechaCreacion()), entity.getFechaCreacion());	
		Assert.assertEquals(dto.getDestruido(), entity.getDestruido());
		Assert.assertEquals(dto.getCaracteristicas(), entity.getCaracteristicas());
		Assert.assertEquals(dto.getEncargadoId(), entity.getEncargadoId());
	}
	
	@Test
	public void getContenedorWebsTest(){
		List<ContenedorWebDTO> list=contenedorWebPersistence.getContenedorWebs();
		Assert.assertEquals(list.size(), data.size());
        for(ContenedorWebDTO dto:list){
        	boolean found=false;
            for(ContenedorWebEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getContenedorWebTest(){
		ContenedorWebEntity entity=data.get(0);
		ContenedorWebDTO dto=contenedorWebPersistence.getContenedorWeb(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getPuertos(), dto.getPuertos());
		Assert.assertEquals(entity.getServidor(), dto.getServidor());
		Assert.assertEquals(entity.getUrl(), dto.getUrl());
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getDescripcion(), dto.getDescripcion());
		Assert.assertEquals(entity.getProposito(), dto.getProposito());
		Assert.assertEquals(entity.getDestruido(), dto.getDestruido());
		Assert.assertEquals(entity.getCaracteristicas(), dto.getCaracteristicas());
		Assert.assertEquals(entity.getEncargadoId(), dto.getEncargadoId());
        
	}
	
	@Test
	public void deleteContenedorWebTest(){
		ContenedorWebEntity entity=data.get(0);
		contenedorWebPersistence.deleteContenedorWeb(entity.getId());
        ContenedorWebEntity deleted=em.find(ContenedorWebEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateContenedorWebTest(){
		ContenedorWebEntity entity=data.get(0);
		
		ContenedorWebDTO dto=new ContenedorWebDTO();
		dto.setId(entity.getId());
		dto.setPuertos(generateRandom(String.class));
		dto.setServidor(generateRandom(String.class));
		dto.setUrl(generateRandom(String.class));
dto.setFechaVencimiento(generateRandomDate());
		dto.setName(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		dto.setProposito(generateRandom(String.class));
dto.setFechaCreacion(generateRandomDate());
		dto.setDestruido(generateRandom(Boolean.class));
		dto.setCaracteristicas(generateRandom(String.class));
		dto.setEncargadoId(generateRandom(Long.class));
		
		
		contenedorWebPersistence.updateContenedorWeb(dto);
		
		
		ContenedorWebEntity resp=em.find(ContenedorWebEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getPuertos(), resp.getPuertos());	
		Assert.assertEquals(dto.getServidor(), resp.getServidor());	
		Assert.assertEquals(dto.getUrl(), resp.getUrl());	
Assert.assertEquals(parseDate(dto.getFechaVencimiento()), resp.getFechaVencimiento());
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getDescripcion(), resp.getDescripcion());	
		Assert.assertEquals(dto.getProposito(), resp.getProposito());	
Assert.assertEquals(parseDate(dto.getFechaCreacion()), resp.getFechaCreacion());
		Assert.assertEquals(dto.getDestruido(), resp.getDestruido());	
		Assert.assertEquals(dto.getCaracteristicas(), resp.getCaracteristicas());	
		Assert.assertEquals(dto.getEncargadoId(), resp.getEncargadoId());	
	}
	
	@Test
	public void getContenedorWebPaginationTest(){
		//Page 1
		ContenedorWebPageDTO dto1=contenedorWebPersistence.getContenedorWebs(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        ContenedorWebPageDTO dto2=contenedorWebPersistence.getContenedorWebs(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(ContenedorWebDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(ContenedorWebEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(ContenedorWebDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(ContenedorWebEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}