/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.encargado.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.grupo.encargado.logic.dto.EncargadoPageDTO;
import co.edu.uniandes.csw.grupo.encargado.logic.dto.EncargadoDTO;
import co.edu.uniandes.csw.grupo.encargado.persistence.api.IEncargadoPersistence;
import co.edu.uniandes.csw.grupo.encargado.persistence.entity.EncargadoEntity;
import co.edu.uniandes.csw.grupo.encargado.persistence.converter.EncargadoConverter;
import static co.edu.uniandes.csw.grupo.util._TestUtil.*;

@RunWith(Arquillian.class)
public class EncargadoPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(EncargadoPersistence.class.getPackage())
				.addPackage(EncargadoEntity.class.getPackage())
				.addPackage(IEncargadoPersistence.class.getPackage())
                .addPackage(EncargadoDTO.class.getPackage())
                .addPackage(EncargadoConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IEncargadoPersistence encargadoPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from EncargadoEntity").executeUpdate();
	}

	private List<EncargadoEntity> data=new ArrayList<EncargadoEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			EncargadoEntity entity=new EncargadoEntity();
			entity.setName(generateRandom(String.class));
			entity.setLogin(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createEncargadoTest(){
		EncargadoDTO dto=new EncargadoDTO();
		dto.setName(generateRandom(String.class));
		dto.setLogin(generateRandom(String.class));
		
		EncargadoDTO result=encargadoPersistence.createEncargado(dto);
		
		Assert.assertNotNull(result);
		
		EncargadoEntity entity=em.find(EncargadoEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getLogin(), entity.getLogin());
	}
	
	@Test
	public void getEncargadosTest(){
		List<EncargadoDTO> list=encargadoPersistence.getEncargados();
		Assert.assertEquals(list.size(), data.size());
        for(EncargadoDTO dto:list){
        	boolean found=false;
            for(EncargadoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getEncargadoTest(){
		EncargadoEntity entity=data.get(0);
		EncargadoDTO dto=encargadoPersistence.getEncargado(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getLogin(), dto.getLogin());
        
	}
	
	@Test
	public void deleteEncargadoTest(){
		EncargadoEntity entity=data.get(0);
		encargadoPersistence.deleteEncargado(entity.getId());
        EncargadoEntity deleted=em.find(EncargadoEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateEncargadoTest(){
		EncargadoEntity entity=data.get(0);
		
		EncargadoDTO dto=new EncargadoDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setLogin(generateRandom(String.class));
		
		
		encargadoPersistence.updateEncargado(dto);
		
		
		EncargadoEntity resp=em.find(EncargadoEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getLogin(), resp.getLogin());	
	}
	
	@Test
	public void getEncargadoPaginationTest(){
		//Page 1
		EncargadoPageDTO dto1=encargadoPersistence.getEncargados(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        EncargadoPageDTO dto2=encargadoPersistence.getEncargados(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(EncargadoDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(EncargadoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(EncargadoDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(EncargadoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}