/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.problema.service;

import co.edu.uniandes.csw.grupo.problema.logic.dto.ProblemaPageDTO;
import java.util.List;

import javax.ejb.Stateless;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.MultivaluedMap;
import javax.ws.rs.core.UriInfo;

@Path("/Problema")
@Stateless
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public class ProblemaService extends _ProblemaService {

    @Context
    UriInfo uriInfo;
    
    @GET
    @Override
    public ProblemaPageDTO getProblemas(@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords){
        System.out.println("Acceso!!!!!!!!!!!!!!!!!!");
		return super.getProblemas(page, maxRecords);
    }
    
    @GET
    @Path("/Search")
    public ProblemaPageDTO searchProblemas(@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords){
        
        MultivaluedMap<String, String> queryParams = uriInfo.getQueryParameters();
        
        System.out.println(queryParams.keySet());
        System.out.println(queryParams.values());
        
        // Estos atributos podrán ser vacios o tener valores
        // Si estan vacíos no se incluirán en la búsqueda
        
        String name = queryParams.getFirst("name");
        String descripcion = queryParams.getFirst("descripcion");
        String empleadoId = queryParams.getFirst("empleadoId");        
        String sqldevId = queryParams.getFirst("sqldevId");
        String mysqlId = queryParams.getFirst("mysqlId");
        String paginawebId = queryParams.getFirst("paginawebId");
        String wikiId = queryParams.getFirst("wikiId");
        String maquinavirtualId = queryParams.getFirst("maquinavirtualId");
        String unidadderedId = queryParams.getFirst("unidadderedId");
        String repositorioId = queryParams.getFirst("repositorioId");
        String contenedorwebId = queryParams.getFirst("contenedorwebId");
        String softwaresalasId = queryParams.getFirst("softwaresalasId");
       
        // Estos atributos, en cambio, siempre poseeran valores estándar.
        // Se debe aclarar eso en el manual de uso.
                       
        String fecha1 = queryParams.getFirst("fechaOcurrencia");
        String fecha2 = queryParams.getFirst("fechaOcurrencia2");
        
        if(name == null)
            name = "";
        if(descripcion == null)
            descripcion = "";
        if(empleadoId == null)
            empleadoId = "";
        if(sqldevId == null)
            sqldevId = "";
        if(mysqlId == null)
            mysqlId = "";
        if(paginawebId == null)
            paginawebId = "";
        if(wikiId == null)
            wikiId = "";
        if(maquinavirtualId == null)
            maquinavirtualId = "";
        if(unidadderedId == null)
            unidadderedId = "";
        if(repositorioId == null)
            repositorioId = "";
        if(contenedorwebId == null)
            contenedorwebId = "";
        if(softwaresalasId == null)
            softwaresalasId = "";
        if(fecha1 == null)
            fecha1 = "";
        if(fecha2 == null)
            fecha2 = "";
               
        String fechaDeOcurrencia1 = "";
        String fechaOcurrencia2 = "";
        
        if(!fecha1.isEmpty() && fecha1 != null)
        {
            String[] date1 = fecha1.split("%2F");
            fechaDeOcurrencia1 = date1[2] + "-" + date1[1] + "-" + date1[0];

        }       
        
        if(!fecha2.isEmpty() && fecha2 != null)
        {
            String[] date2 = fecha2.split("%2F");            
            fechaOcurrencia2 = date2[2] + "-" + date2[1] + "-" + date2[0];

        }
        
        return problemaLogicService.getProblemasByParameters(name, descripcion, empleadoId, sqldevId, mysqlId, paginawebId, wikiId, maquinavirtualId, unidadderedId, repositorioId, contenedorwebId, softwaresalasId, fechaDeOcurrencia1, fechaOcurrencia2);
    }

}