/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.softwaresalas.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.grupo.softwaresalas.logic.dto.SoftwareSalasDTO;
import co.edu.uniandes.csw.grupo.softwaresalas.persistence.entity.SoftwareSalasEntity;

public abstract class _SoftwareSalasConverter {

 
	private final static SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");
	public static SoftwareSalasDTO entity2PersistenceDTO(SoftwareSalasEntity entity){
		if (entity != null) {
			SoftwareSalasDTO dto = new SoftwareSalasDTO();
					dto.setTipoMaquina(entity.getTipoMaquina());
					dto.setSoftware(entity.getSoftware());
					dto.setVersion(entity.getVersion());
					dto.setSolicitante(entity.getSolicitante());
					dto.setNumeroMaquina(entity.getNumeroMaquina());
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setDescripcion(entity.getDescripcion());
					dto.setProposito(entity.getProposito());
 
			    if(entity.getFechaCreacion() != null){
					dto.setFechaCreacion(DATE_FORMAT.format(entity.getFechaCreacion()));
				}	
					dto.setDestruido(entity.getDestruido());
					dto.setCaracteristicas(entity.getCaracteristicas());
					dto.setWorkstationId(entity.getWorkstationId());
			return dto;
		}else{
			return null;
		}
	}
	
	public static SoftwareSalasEntity persistenceDTO2Entity(SoftwareSalasDTO dto){
		if(dto!=null){
			SoftwareSalasEntity entity=new SoftwareSalasEntity();
					entity.setTipoMaquina(dto.getTipoMaquina());
			
					entity.setSoftware(dto.getSoftware());
			
					entity.setVersion(dto.getVersion());
			
					entity.setSolicitante(dto.getSolicitante());
			
					entity.setNumeroMaquina(dto.getNumeroMaquina());
			
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setDescripcion(dto.getDescripcion());
			
					entity.setProposito(dto.getProposito());
			
 
			      try{ 
			        if(dto.getFechaCreacion() != null){
						entity.setFechaCreacion(DATE_FORMAT.parse(dto.getFechaCreacion()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_SoftwareSalasConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
					entity.setDestruido(dto.getDestruido());
			
					entity.setCaracteristicas(dto.getCaracteristicas());
			
					entity.setWorkstationId(dto.getWorkstationId());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<SoftwareSalasDTO> entity2PersistenceDTOList(List<SoftwareSalasEntity> entities){
		List<SoftwareSalasDTO> dtos=new ArrayList<SoftwareSalasDTO>();
		for(SoftwareSalasEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<SoftwareSalasEntity> persistenceDTO2EntityList(List<SoftwareSalasDTO> dtos){
		List<SoftwareSalasEntity> entities=new ArrayList<SoftwareSalasEntity>();
		for(SoftwareSalasDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}