/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.empleado.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.grupo.empleado.logic.dto.EmpleadoPageDTO;
import co.edu.uniandes.csw.grupo.empleado.logic.dto.EmpleadoDTO;
import co.edu.uniandes.csw.grupo.empleado.logic.api.IEmpleadoLogicService;
import co.edu.uniandes.csw.grupo.empleado.persistence.EmpleadoPersistence;
import co.edu.uniandes.csw.grupo.empleado.persistence.api.IEmpleadoPersistence;
import co.edu.uniandes.csw.grupo.empleado.persistence.entity.EmpleadoEntity;
import co.edu.uniandes.csw.grupo.empleado.persistence.converter.EmpleadoConverter;
import static co.edu.uniandes.csw.grupo.util._TestUtil.*;

@RunWith(Arquillian.class)
public class EmpleadoLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(EmpleadoLogicService.class.getPackage())
				.addPackage(IEmpleadoLogicService.class.getPackage())
				.addPackage(EmpleadoPersistence.class.getPackage())
				.addPackage(EmpleadoEntity.class.getPackage())
				.addPackage(IEmpleadoPersistence.class.getPackage())
                .addPackage(EmpleadoDTO.class.getPackage())
                .addPackage(EmpleadoConverter.class.getPackage())
                .addPackage(EmpleadoEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IEmpleadoLogicService empleadoLogicService;
	
	@Inject
	private IEmpleadoPersistence empleadoPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<EmpleadoDTO> dtos=empleadoPersistence.getEmpleados();
		for(EmpleadoDTO dto:dtos){
			empleadoPersistence.deleteEmpleado(dto.getId());
		}
	}

	private List<EmpleadoDTO> data=new ArrayList<EmpleadoDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			EmpleadoDTO pdto=new EmpleadoDTO();
			pdto.setPassword(generateRandom(String.class));
			pdto.setName(generateRandom(String.class));
			pdto.setLogin(generateRandom(String.class));
			pdto=empleadoPersistence.createEmpleado(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createEmpleadoTest(){
		EmpleadoDTO ldto=new EmpleadoDTO();
		ldto.setPassword(generateRandom(String.class));
		ldto.setName(generateRandom(String.class));
		ldto.setLogin(generateRandom(String.class));
		
		
		EmpleadoDTO result=empleadoLogicService.createEmpleado(ldto);
		
		Assert.assertNotNull(result);
		
		EmpleadoDTO pdto=empleadoPersistence.getEmpleado(result.getId());
		
		Assert.assertEquals(ldto.getPassword(), pdto.getPassword());	
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getLogin(), pdto.getLogin());	
	}
	
	@Test
	public void getEmpleadosTest(){
		List<EmpleadoDTO> list=empleadoLogicService.getEmpleados();
		Assert.assertEquals(list.size(), data.size());
        for(EmpleadoDTO ldto:list){
        	boolean found=false;
            for(EmpleadoDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getEmpleadoTest(){
		EmpleadoDTO pdto=data.get(0);
		EmpleadoDTO ldto=empleadoLogicService.getEmpleado(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getPassword(), ldto.getPassword());
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getLogin(), ldto.getLogin());
        
	}
	
	@Test
	public void deleteEmpleadoTest(){
		EmpleadoDTO pdto=data.get(0);
		empleadoLogicService.deleteEmpleado(pdto.getId());
        EmpleadoDTO deleted=empleadoPersistence.getEmpleado(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateEmpleadoTest(){
		EmpleadoDTO pdto=data.get(0);
		
		EmpleadoDTO ldto=new EmpleadoDTO();
		ldto.setId(pdto.getId());
		ldto.setPassword(generateRandom(String.class));
		ldto.setName(generateRandom(String.class));
		ldto.setLogin(generateRandom(String.class));
		
		
		empleadoLogicService.updateEmpleado(ldto);
		
		
		EmpleadoDTO resp=empleadoPersistence.getEmpleado(pdto.getId());
		
		Assert.assertEquals(ldto.getPassword(), resp.getPassword());	
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getLogin(), resp.getLogin());	
	}
	
	@Test
	public void getEmpleadoPaginationTest(){
		
		EmpleadoPageDTO dto1=empleadoLogicService.getEmpleados(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		EmpleadoPageDTO dto2=empleadoLogicService.getEmpleados(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(EmpleadoDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(EmpleadoDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(EmpleadoDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(EmpleadoDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        EmpleadoPageDTO dto3=empleadoLogicService.getEmpleados(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(EmpleadoDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(EmpleadoDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}