/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.contenedorweb.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.grupo.contenedorweb.logic.dto.ContenedorWebDTO;
import co.edu.uniandes.csw.grupo.contenedorweb.logic.dto.ContenedorWebPageDTO;
import co.edu.uniandes.csw.grupo.contenedorweb.persistence.api._IContenedorWebPersistence;
import co.edu.uniandes.csw.grupo.contenedorweb.persistence.converter.ContenedorWebConverter;
import co.edu.uniandes.csw.grupo.contenedorweb.persistence.entity.ContenedorWebEntity;

public abstract class _ContenedorWebPersistence implements _IContenedorWebPersistence {

  	@PersistenceContext(unitName="RigitalAppPU")
 
	protected EntityManager entityManager;
	
	public ContenedorWebDTO createContenedorWeb(ContenedorWebDTO contenedorWeb) {
		ContenedorWebEntity entity=ContenedorWebConverter.persistenceDTO2Entity(contenedorWeb);
		entityManager.persist(entity);
		return ContenedorWebConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<ContenedorWebDTO> getContenedorWebs() {
		Query q = entityManager.createQuery("select u from ContenedorWebEntity u");
		return ContenedorWebConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public ContenedorWebPageDTO getContenedorWebs(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from ContenedorWebEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from ContenedorWebEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		ContenedorWebPageDTO response = new ContenedorWebPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(ContenedorWebConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public ContenedorWebDTO getContenedorWeb(Long id) {
		return ContenedorWebConverter.entity2PersistenceDTO(entityManager.find(ContenedorWebEntity.class, id));
	}

	public void deleteContenedorWeb(Long id) {
		ContenedorWebEntity entity=entityManager.find(ContenedorWebEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateContenedorWeb(ContenedorWebDTO detail) {
		ContenedorWebEntity entity=entityManager.merge(ContenedorWebConverter.persistenceDTO2Entity(detail));
		ContenedorWebConverter.entity2PersistenceDTO(entity);
	}

}