/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.contenedorweb.persistence;

import co.edu.uniandes.csw.grupo.contenedorweb.logic.dto.ContenedorWebDTO;
import co.edu.uniandes.csw.grupo.contenedorweb.logic.dto.ContenedorWebPageDTO;
import javax.ejb.Stateless;
import javax.enterprise.inject.Default;

import co.edu.uniandes.csw.grupo.contenedorweb.persistence.api.IContenedorWebPersistence;
import co.edu.uniandes.csw.grupo.contenedorweb.persistence.converter.ContenedorWebConverter;
import co.edu.uniandes.csw.grupo.contenedorweb.persistence.entity.ContenedorWebEntity;
import co.edu.uniandes.csw.grupo.encargado.master.persistence.entity.EncargadocontenedorWebEntity;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.ejb.LocalBean;
import javax.persistence.Query;

@Default
@Stateless 
@LocalBean
public class ContenedorWebPersistence extends _ContenedorWebPersistence  implements IContenedorWebPersistence {

    @Override
    public ContenedorWebDTO createContenedorWeb(ContenedorWebDTO wiki) {
                ContenedorWebEntity entity=ContenedorWebConverter.persistenceDTO2Entity(wiki);
		entityManager.persist(entity);
                
                ContenedorWebDTO rta = ContenedorWebConverter.entity2PersistenceDTO(entity);
                Long id = rta.getId();
                Long idEncargado = rta.getEncargadoId();
                
                if(idEncargado != 0)
                {
                    System.out.println("ID: " + id);
                    System.out.println("ID Encargado: " + idEncargado);

                    EncargadocontenedorWebEntity este = new EncargadocontenedorWebEntity(idEncargado, id);  
                    entityManager.persist(este);

                }
                
		return rta;
    }
    
    @SuppressWarnings("unchecked")
    public ContenedorWebPageDTO getContenedoresWebByParameters(String puertos ,String servidor ,String url ,String name ,String descripcion ,String proposito ,String caracteristicas ,String encargadoId,String fechaCreacion1,String fechaCreacion2,String fechaVencimiento1,String fechaVencimiento2,String estaDestruido)
    {
        Query count = entityManager.createQuery("select count(u) from ContenedorWebEntity u");
        Long regCount = 0L;
        regCount = Long.parseLong(count.getSingleResult().toString());
                
        String sql = "SELECT u FROM ContenedorWebEntity u WHERE";
        if(!puertos.isEmpty())
            sql += " AND u.puertos like :puertos";
        if(!servidor.isEmpty())
            sql += " AND u.servidor like :servidor";
        if(!url.isEmpty())
            sql += " AND u.url like :url";
        if(!name.isEmpty())
            sql  += " AND u.name like :name";
        if(!descripcion.isEmpty())
            sql += " AND u.descripcion like :descripcion";
        if(!proposito.isEmpty())
            sql += " AND  u.proposito like :proposito";
        if(!caracteristicas.isEmpty())
            sql += " AND  u.caracteristicas like :caracteristicas";
        if(!encargadoId.isEmpty())
            sql += " AND  u.encargadoId = :encargadoId";
        
        if(!estaDestruido.isEmpty())
            sql += " AND  u.destruido = :estaDestruido";
        
        if(!fechaCreacion1.isEmpty() && !fechaCreacion2.isEmpty())
            sql += " AND u.fechaCreacion BETWEEN :fechaCreacion1 and :fechaCreacion2";

        if(!fechaVencimiento1.isEmpty() && !fechaVencimiento1.isEmpty())
            sql += " AND u.fechaVencimiento BETWEEN :fechaVencimiento1 and :fechaVencimiento2";
        // Se limpia la sentencia sql
        
        if(sql.endsWith("WHERE"))
            sql = sql.replace("WHERE", "");
        if(sql.contains("WHERE AND"))
            sql = sql.replace("WHERE AND", "WHERE");
        
        System.out.println(sql);
        
        boolean destruido = false;
        
        if(estaDestruido.equals("1"))
            destruido = true;
        
        Query q = entityManager.createQuery(sql);
        
        if(!puertos.isEmpty())
            q.setParameter("puertos", "%"+puertos+"%");
        if(!servidor .isEmpty())
            q.setParameter("servidor", "%"+servidor +"%");
        if(!url.isEmpty())
            q.setParameter("url", "%"+url+"%");
        if(!name.isEmpty())
            q.setParameter("name", "%"+name+"%");
        if(!descripcion.isEmpty())
            q.setParameter("descripcion", "%"+descripcion+"%");
        if(!proposito.isEmpty())
            q.setParameter("proposito", "%"+proposito+"%");
        if(!caracteristicas.isEmpty())
            q.setParameter("caracteristicas", "%"+caracteristicas+"%");
        if(!encargadoId.isEmpty())
            q.setParameter("numCores", Long.parseLong(encargadoId));
        
        if(!estaDestruido.isEmpty())
            q.setParameter("estaDestruido", destruido);
        
        if(!fechaCreacion1.isEmpty() && !fechaCreacion2.isEmpty())
        {
            String[] a1 = fechaCreacion1.split("-");
            String[] a2 = fechaCreacion2.split("-");
            
            Date fecha1 = new Date(Integer.parseInt(a1[0])-1900, Integer.parseInt(a1[1]),Integer.parseInt(a1[2]));
            Date fecha2 = new Date(Integer.parseInt(a2[0])-1900, Integer.parseInt(a2[1]),Integer.parseInt(a2[2]));
            
            q.setParameter("fechaCreacion1", fecha1);
            q.setParameter("fechaCreacion2", fecha2);            
        }
        
        if(!fechaVencimiento1.isEmpty() && !fechaVencimiento2.isEmpty())
        {
            String[] a1 = fechaVencimiento1.split("-");
            String[] a2 = fechaVencimiento2.split("-");
            
            System.out.println(a1[0] + " -------- " + Integer.parseInt(a1[0]));
            System.out.println(a2[0] + " ------------ " + Integer.parseInt(a2[0]));
            
            Date fecha1 = new Date(Integer.parseInt(a1[0])-1900, Integer.parseInt(a1[1]),Integer.parseInt(a1[2]));
            Date fecha2 = new Date(Integer.parseInt(a2[0])-1900, Integer.parseInt(a2[1]),Integer.parseInt(a2[2]));
            
            q.setParameter("fechaVencimiento1", fecha1);
            q.setParameter("fechaVencimiento2", fecha2);            
        }
        
        ContenedorWebPageDTO response = new ContenedorWebPageDTO();
        response.setTotalRecords(regCount);
        response.setRecords(ContenedorWebConverter.entity2PersistenceDTOList(q.getResultList()));
        return response;
        
            
    }

    public void desactivarRecurso(Long contenedor) {
        Query query= entityManager.createQuery("UPDATE ContenedorWebEntity c SET c.destruido='false' WHERE c.id = :contenedor");
        query.setParameter("contenedor", contenedor);
        query.executeUpdate();

    }
    
    public String mensajeVencidos(){
        
        String respuesta = "\n\n- CONTENEDORES WEB:";
        
        ArrayList<ContenedorWebEntity> proximas = new ArrayList();
        ArrayList<ContenedorWebEntity> vencidas = new ArrayList();
        
        List<ContenedorWebDTO> lista = getContenedorWebs();
        
        for(int i = 0; i < lista.size(); i++)
        {
            ContenedorWebDTO actual = lista.get(i);
            ContenedorWebEntity entidad = ContenedorWebConverter.persistenceDTO2Entity(actual);
            
            boolean estaDestruido = entidad.getDestruido();
            
            Date fechaActual = new Date(System.currentTimeMillis());
            Date fechaVencimiento = entidad.getFechaVencimiento();
            
            System.out.println(fechaActual + " ---- " + fechaActual.getTime());
            System.out.println(fechaVencimiento + " ---- " + fechaVencimiento.getTime());
            
            Long diferencia =  fechaVencimiento.getTime() - fechaActual.getTime();
            
            // 1 semana es equivalente a 604800000 milisegundos
            
            if(estaDestruido)
            {
                if(diferencia < 0)
                    vencidas.add(entidad);
                else if(diferencia < 604800000 && diferencia > 0)
                    proximas.add(entidad);
            }
        }
        
        if(vencidas.size() > 0)
            respuesta += "\n\n      - VENCIDOS:";
        
        for(int i = 0; i < vencidas.size(); i++)
        {
            respuesta += "\n            - " + (i+1) + ": NOMBRE: " + vencidas.get(i).getName() + " , FECHA DE VENCIMIENTO: " + vencidas.get(i).getFechaVencimiento().getDate() + "/" + vencidas.get(i).getFechaVencimiento().getMonth()+ "/" + vencidas.get(i).getFechaVencimiento().getYear();
        }
        
        if(proximas.size() > 0)
            respuesta += "\n\n      - PRÓXIMOS A VENCER:";
        
        for(int i = 0; i < proximas.size(); i++)
        {
            respuesta += "\n            - " + (i+1) + ": NOMBRE: " + proximas.get(i).getName() + " , FECHA DE VENCIMIENTO: " + proximas.get(i).getFechaVencimiento().getDate() + "/" + proximas.get(i).getFechaVencimiento().getMonth()+ "/" + proximas.get(i).getFechaVencimiento().getYear();
        }
                
        if(respuesta.equals("\n\n- CONTENEDORES WEB:"))
            respuesta = "";
        
        return respuesta;
                
    }
}