/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.wiki.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.grupo.wiki.logic.dto.WikiPageDTO;
import co.edu.uniandes.csw.grupo.wiki.logic.dto.WikiDTO;
import co.edu.uniandes.csw.grupo.wiki.logic.api.IWikiLogicService;
import co.edu.uniandes.csw.grupo.wiki.persistence.WikiPersistence;
import co.edu.uniandes.csw.grupo.wiki.persistence.api.IWikiPersistence;
import co.edu.uniandes.csw.grupo.wiki.persistence.entity.WikiEntity;
import co.edu.uniandes.csw.grupo.wiki.persistence.converter.WikiConverter;
import static co.edu.uniandes.csw.grupo.util._TestUtil.*;

@RunWith(Arquillian.class)
public class WikiLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(WikiLogicService.class.getPackage())
				.addPackage(IWikiLogicService.class.getPackage())
				.addPackage(WikiPersistence.class.getPackage())
				.addPackage(WikiEntity.class.getPackage())
				.addPackage(IWikiPersistence.class.getPackage())
                .addPackage(WikiDTO.class.getPackage())
                .addPackage(WikiConverter.class.getPackage())
                .addPackage(WikiEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IWikiLogicService wikiLogicService;
	
	@Inject
	private IWikiPersistence wikiPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<WikiDTO> dtos=wikiPersistence.getWikis();
		for(WikiDTO dto:dtos){
			wikiPersistence.deleteWiki(dto.getId());
		}
	}

	private List<WikiDTO> data=new ArrayList<WikiDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			WikiDTO pdto=new WikiDTO();
			pdto.setServidor_host(generateRandom(String.class));
			pdto.setRutaServidor(generateRandom(String.class));
			pdto.setName(generateRandom(String.class));
			pdto.setDescripcion(generateRandom(String.class));
			pdto.setProposito(generateRandom(String.class));
			pdto.setFechaCreacion(generateRandomDate());
			pdto.setDestruido(generateRandom(Boolean.class));
			pdto.setCaracteristicas(generateRandom(String.class));
			pdto.setEncargadoId(generateRandom(Long.class));
			pdto=wikiPersistence.createWiki(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createWikiTest(){
		WikiDTO ldto=new WikiDTO();
		ldto.setServidor_host(generateRandom(String.class));
		ldto.setRutaServidor(generateRandom(String.class));
		ldto.setName(generateRandom(String.class));
		ldto.setDescripcion(generateRandom(String.class));
		ldto.setProposito(generateRandom(String.class));
		ldto.setFechaCreacion(generateRandomDate());
		ldto.setDestruido(generateRandom(Boolean.class));
		ldto.setCaracteristicas(generateRandom(String.class));
		ldto.setEncargadoId(generateRandom(Long.class));
		
		
		WikiDTO result=wikiLogicService.createWiki(ldto);
		
		Assert.assertNotNull(result);
		
		WikiDTO pdto=wikiPersistence.getWiki(result.getId());
		
		Assert.assertEquals(ldto.getServidor_host(), pdto.getServidor_host());	
		Assert.assertEquals(ldto.getRutaServidor(), pdto.getRutaServidor());	
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getDescripcion(), pdto.getDescripcion());	
		Assert.assertEquals(ldto.getProposito(), pdto.getProposito());	
		Assert.assertEquals(ldto.getFechaCreacion(), pdto.getFechaCreacion());	
		Assert.assertEquals(ldto.getDestruido(), pdto.getDestruido());	
		Assert.assertEquals(ldto.getCaracteristicas(), pdto.getCaracteristicas());	
		Assert.assertEquals(ldto.getEncargadoId(), pdto.getEncargadoId());	
	}
	
	@Test
	public void getWikisTest(){
		List<WikiDTO> list=wikiLogicService.getWikis();
		Assert.assertEquals(list.size(), data.size());
        for(WikiDTO ldto:list){
        	boolean found=false;
            for(WikiDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getWikiTest(){
		WikiDTO pdto=data.get(0);
		WikiDTO ldto=wikiLogicService.getWiki(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getServidor_host(), ldto.getServidor_host());
		Assert.assertEquals(pdto.getRutaServidor(), ldto.getRutaServidor());
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getDescripcion(), ldto.getDescripcion());
		Assert.assertEquals(pdto.getProposito(), ldto.getProposito());
		Assert.assertEquals(pdto.getFechaCreacion(), ldto.getFechaCreacion());
		Assert.assertEquals(pdto.getDestruido(), ldto.getDestruido());
		Assert.assertEquals(pdto.getCaracteristicas(), ldto.getCaracteristicas());
		Assert.assertEquals(pdto.getEncargadoId(), ldto.getEncargadoId());
        
	}
	
	@Test
	public void deleteWikiTest(){
		WikiDTO pdto=data.get(0);
		wikiLogicService.deleteWiki(pdto.getId());
        WikiDTO deleted=wikiPersistence.getWiki(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateWikiTest(){
		WikiDTO pdto=data.get(0);
		
		WikiDTO ldto=new WikiDTO();
		ldto.setId(pdto.getId());
		ldto.setServidor_host(generateRandom(String.class));
		ldto.setRutaServidor(generateRandom(String.class));
		ldto.setName(generateRandom(String.class));
		ldto.setDescripcion(generateRandom(String.class));
		ldto.setProposito(generateRandom(String.class));
		ldto.setFechaCreacion(generateRandomDate());
		ldto.setDestruido(generateRandom(Boolean.class));
		ldto.setCaracteristicas(generateRandom(String.class));
		ldto.setEncargadoId(generateRandom(Long.class));
		
		
		wikiLogicService.updateWiki(ldto);
		
		
		WikiDTO resp=wikiPersistence.getWiki(pdto.getId());
		
		Assert.assertEquals(ldto.getServidor_host(), resp.getServidor_host());	
		Assert.assertEquals(ldto.getRutaServidor(), resp.getRutaServidor());	
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getDescripcion(), resp.getDescripcion());	
		Assert.assertEquals(ldto.getProposito(), resp.getProposito());	
		Assert.assertEquals(ldto.getFechaCreacion(), resp.getFechaCreacion());	
		Assert.assertEquals(ldto.getDestruido(), resp.getDestruido());	
		Assert.assertEquals(ldto.getCaracteristicas(), resp.getCaracteristicas());	
		Assert.assertEquals(ldto.getEncargadoId(), resp.getEncargadoId());	
	}
	
	@Test
	public void getWikiPaginationTest(){
		
		WikiPageDTO dto1=wikiLogicService.getWikis(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		WikiPageDTO dto2=wikiLogicService.getWikis(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(WikiDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(WikiDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(WikiDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(WikiDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        WikiPageDTO dto3=wikiLogicService.getWikis(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(WikiDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(WikiDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}