/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.cms.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.grupo.cms.logic.dto.CMSPageDTO;
import co.edu.uniandes.csw.grupo.cms.logic.dto.CMSDTO;
import co.edu.uniandes.csw.grupo.cms.logic.api.ICMSLogicService;
import co.edu.uniandes.csw.grupo.cms.persistence.CMSPersistence;
import co.edu.uniandes.csw.grupo.cms.persistence.api.ICMSPersistence;
import co.edu.uniandes.csw.grupo.cms.persistence.entity.CMSEntity;
import co.edu.uniandes.csw.grupo.cms.persistence.converter.CMSConverter;
import static co.edu.uniandes.csw.grupo.util._TestUtil.*;

@RunWith(Arquillian.class)
public class CMSLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(CMSLogicService.class.getPackage())
				.addPackage(ICMSLogicService.class.getPackage())
				.addPackage(CMSPersistence.class.getPackage())
				.addPackage(CMSEntity.class.getPackage())
				.addPackage(ICMSPersistence.class.getPackage())
                .addPackage(CMSDTO.class.getPackage())
                .addPackage(CMSConverter.class.getPackage())
                .addPackage(CMSEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private ICMSLogicService cMSLogicService;
	
	@Inject
	private ICMSPersistence cMSPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<CMSDTO> dtos=cMSPersistence.getCMSs();
		for(CMSDTO dto:dtos){
			cMSPersistence.deleteCMS(dto.getId());
		}
	}

	private List<CMSDTO> data=new ArrayList<CMSDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			CMSDTO pdto=new CMSDTO();
			pdto.setName(generateRandom(String.class));
			pdto.setVersion(generateRandom(Double.class));
			pdto=cMSPersistence.createCMS(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createCMSTest(){
		CMSDTO ldto=new CMSDTO();
		ldto.setName(generateRandom(String.class));
		ldto.setVersion(generateRandom(Double.class));
		
		
		CMSDTO result=cMSLogicService.createCMS(ldto);
		
		Assert.assertNotNull(result);
		
		CMSDTO pdto=cMSPersistence.getCMS(result.getId());
		
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getVersion(), pdto.getVersion());	
	}
	
	@Test
	public void getCMSsTest(){
		List<CMSDTO> list=cMSLogicService.getCMSs();
		Assert.assertEquals(list.size(), data.size());
        for(CMSDTO ldto:list){
        	boolean found=false;
            for(CMSDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getCMSTest(){
		CMSDTO pdto=data.get(0);
		CMSDTO ldto=cMSLogicService.getCMS(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getVersion(), ldto.getVersion());
        
	}
	
	@Test
	public void deleteCMSTest(){
		CMSDTO pdto=data.get(0);
		cMSLogicService.deleteCMS(pdto.getId());
        CMSDTO deleted=cMSPersistence.getCMS(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateCMSTest(){
		CMSDTO pdto=data.get(0);
		
		CMSDTO ldto=new CMSDTO();
		ldto.setId(pdto.getId());
		ldto.setName(generateRandom(String.class));
		ldto.setVersion(generateRandom(Double.class));
		
		
		cMSLogicService.updateCMS(ldto);
		
		
		CMSDTO resp=cMSPersistence.getCMS(pdto.getId());
		
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getVersion(), resp.getVersion());	
	}
	
	@Test
	public void getCMSPaginationTest(){
		
		CMSPageDTO dto1=cMSLogicService.getCMSs(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		CMSPageDTO dto2=cMSLogicService.getCMSs(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(CMSDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(CMSDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(CMSDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(CMSDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        CMSPageDTO dto3=cMSLogicService.getCMSs(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(CMSDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(CMSDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}