/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.mysql.master.logic.ejb;

import co.edu.uniandes.csw.grupo.problema.logic.dto.ProblemaDTO;
import co.edu.uniandes.csw.grupo.problema.persistence.api.IProblemaPersistence;
import co.edu.uniandes.csw.grupo.mysql.logic.dto.MySQLDTO;
import co.edu.uniandes.csw.grupo.mysql.master.logic.api._IMySQLMasterLogicService;
import co.edu.uniandes.csw.grupo.mysql.master.logic.dto.MySQLMasterDTO;
import co.edu.uniandes.csw.grupo.mysql.master.persistence.api.IMySQLMasterPersistence;
import co.edu.uniandes.csw.grupo.mysql.master.persistence.entity.MySQLproblemaEntity;
import co.edu.uniandes.csw.grupo.mysql.persistence.api.IMySQLPersistence;
import javax.inject.Inject;

public abstract class _MySQLMasterLogicService implements _IMySQLMasterLogicService {

    @Inject
    protected IMySQLPersistence mysqlPersistance;
    @Inject
    protected IMySQLMasterPersistence mysqlMasterPersistance;
    @Inject
    protected IProblemaPersistence problemaPersistance;

    public MySQLMasterDTO createMasterMySQL(MySQLMasterDTO mysql) {
        MySQLDTO persistedMySQLDTO = mysqlPersistance.createMySQL(mysql.getMySQLEntity());
        if (mysql.getCreateproblema() != null) {
            for (ProblemaDTO problemaDTO : mysql.getCreateproblema()) {
                ProblemaDTO createdProblemaDTO = problemaPersistance.createProblema(problemaDTO);
                MySQLproblemaEntity mysqlProblemaEntity = new MySQLproblemaEntity(persistedMySQLDTO.getId(), createdProblemaDTO.getId());
                mysqlMasterPersistance.createMySQLproblemaEntity(mysqlProblemaEntity);
            }
        }
        // update problema
        if (mysql.getUpdateproblema() != null) {
            for (ProblemaDTO problemaDTO : mysql.getUpdateproblema()) {
                problemaPersistance.updateProblema(problemaDTO);
                MySQLproblemaEntity mysqlProblemaEntity = new MySQLproblemaEntity(persistedMySQLDTO.getId(), problemaDTO.getId());
                mysqlMasterPersistance.createMySQLproblemaEntity(mysqlProblemaEntity);
            }
        }
        return mysql;
    }

    public MySQLMasterDTO getMasterMySQL(Long id) {
        return mysqlMasterPersistance.getMySQL(id);
    }

    public void deleteMasterMySQL(Long id) {
        mysqlPersistance.deleteMySQL(id);
    }

    public void updateMasterMySQL(MySQLMasterDTO mysql) {
        mysqlPersistance.updateMySQL(mysql.getMySQLEntity());

        //---- FOR RELATIONSHIP
        // delete problema
        if (mysql.getDeleteproblema() != null) {
            for (ProblemaDTO problemaDTO : mysql.getDeleteproblema()) {
                mysqlMasterPersistance.deleteMySQLproblemaEntity(mysql.getMySQLEntity().getId(), problemaDTO.getId());
            }
        }
        // persist new problema
        if (mysql.getCreateproblema() != null) {
            for (ProblemaDTO problemaDTO : mysql.getCreateproblema()) {
                MySQLproblemaEntity mysqlProblemaEntity = new MySQLproblemaEntity(mysql.getMySQLEntity().getId(), problemaDTO.getId());
                mysqlMasterPersistance.createMySQLproblemaEntity(mysqlProblemaEntity);
            }
        }
        // update problema
        if (mysql.getUpdateproblema() != null) {
            for (ProblemaDTO problemaDTO : mysql.getUpdateproblema()) {
                mysqlMasterPersistance.deleteMySQLproblemaEntity(mysql.getMySQLEntity().getId(), problemaDTO.getId());
                problemaPersistance.updateProblema(problemaDTO);
                MySQLproblemaEntity mysqlProblemaEntity = new MySQLproblemaEntity(mysql.getId(), problemaDTO.getId());
                mysqlMasterPersistance.createMySQLproblemaEntity(mysqlProblemaEntity);
                
            }
        }
    }
}
