/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.empleado.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.grupo.empleado.logic.dto.EmpleadoDTO;
import co.edu.uniandes.csw.grupo.empleado.logic.dto.EmpleadoPageDTO;
import co.edu.uniandes.csw.grupo.empleado.persistence.api._IEmpleadoPersistence;
import co.edu.uniandes.csw.grupo.empleado.persistence.converter.EmpleadoConverter;
import co.edu.uniandes.csw.grupo.empleado.persistence.entity.EmpleadoEntity;

public abstract class _EmpleadoPersistence implements _IEmpleadoPersistence {

  	@PersistenceContext(unitName="RigitalAppPU")
 
	protected EntityManager entityManager;
	
	public EmpleadoDTO createEmpleado(EmpleadoDTO empleado) {
		EmpleadoEntity entity=EmpleadoConverter.persistenceDTO2Entity(empleado);
		entityManager.persist(entity);
		return EmpleadoConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<EmpleadoDTO> getEmpleados() {
		Query q = entityManager.createQuery("select u from EmpleadoEntity u");
		return EmpleadoConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public EmpleadoPageDTO getEmpleados(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from EmpleadoEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from EmpleadoEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		EmpleadoPageDTO response = new EmpleadoPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(EmpleadoConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public EmpleadoDTO getEmpleado(Long id) {
		return EmpleadoConverter.entity2PersistenceDTO(entityManager.find(EmpleadoEntity.class, id));
	}

	public void deleteEmpleado(Long id) {
		EmpleadoEntity entity=entityManager.find(EmpleadoEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateEmpleado(EmpleadoDTO detail) {
		EmpleadoEntity entity=entityManager.merge(EmpleadoConverter.persistenceDTO2Entity(detail));
		EmpleadoConverter.entity2PersistenceDTO(entity);
	}

}