/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.empleado.persistence;

import co.edu.uniandes.csw.grupo.empleado.logic.dto.EmpleadoDTO;
import co.edu.uniandes.csw.grupo.empleado.logic.dto.EmpleadoPageDTO;
import co.edu.uniandes.csw.grupo.empleado.persistence.api.IEmpleadoPersistence;
import co.edu.uniandes.csw.grupo.empleado.persistence.converter.EmpleadoConverter;
import co.edu.uniandes.csw.grupo.empleado.persistence.entity.EmpleadoEntity;
import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.ejb.LocalBean;
import javax.ejb.Stateless;
import javax.enterprise.inject.Default;
import javax.persistence.Query;

@Default
@Stateless 
@LocalBean
public class EmpleadoPersistence extends _EmpleadoPersistence  implements IEmpleadoPersistence {
    
    public EmpleadoDTO getEmpleadoId(String name){
        Query q = entityManager.createQuery("select y from EmpleadoEntity y where y.name='" + name +"'");
        if( q.getResultList().isEmpty())
        {
            return null;
        }
        else
        {
            return EmpleadoConverter.entity2PersistenceDTO((EmpleadoEntity)q.getResultList().get(0));
        }
    }

    @SuppressWarnings("unchecked")
    public EmpleadoPageDTO getEmpleadosByParameters(String name,String password,String login)
    {
        Query count = entityManager.createQuery("select count(u) from EmpleadoEntity u");
        Long regCount = 0L;
        regCount = Long.parseLong(count.getSingleResult().toString());
                
        String sql = "SELECT u FROM EmpleadoEntity u WHERE";
        if(!name.isEmpty())
            sql += " AND u.name like :name";
        if(!password.isEmpty())
            sql += " AND u.password like :password";
        if(!login.isEmpty())
            sql += " AND u.login login :login";
        
        // Se limpia la sentencia sql
        
        if(sql.endsWith("WHERE"))
            sql = sql.replace("WHERE", "");
        if(sql.contains("WHERE AND"))
            sql = sql.replace("WHERE AND", "WHERE");
        
        System.out.println(sql);
        
        Query q = entityManager.createQuery(sql);
        
        if(!name.isEmpty())
            q.setParameter("name", "%"+name+"%");
        if(!password.isEmpty())
            q.setParameter("password", "%"+password+"%");
        if(!login.isEmpty())
            q.setParameter("login", "%"+login+"%");
        
        
        
        EmpleadoPageDTO response = new EmpleadoPageDTO();
        response.setTotalRecords(regCount);
        response.setRecords(EmpleadoConverter.entity2PersistenceDTOList(q.getResultList()));
        return response;
        
            
    }
    
    @Override
    public EmpleadoDTO createEmpleado(EmpleadoDTO empleado) {
        try
        {
            empleado.setPassword(MD5(empleado.getPassword()));
        }
        catch (Exception e)
        {
            //No hace nada?
        }
        EmpleadoEntity entity = EmpleadoConverter.persistenceDTO2Entity(empleado);
        entityManager.persist(entity);
        return EmpleadoConverter.entity2PersistenceDTO(entity);
    }
/*Método auxiliar que converte bytes a Strings en hexadecimal*/
    private static String convertedToHex(byte[] data) {
        StringBuffer buf = new StringBuffer();
 
        for (int i = 0; i < data.length; i++) {
            int halfOfByte = (data[i] >>> 4) & 0x0F;
            int twoHalfBytes = 0;
 
            do {
                if ((0 <= halfOfByte) && (halfOfByte <= 9))
                {
                    buf.append((char) ('0' + halfOfByte));
                }
                else
                {
                    buf.append((char) ('a' + (halfOfByte - 10)));
                }
 
                halfOfByte = data[i] & 0x0F;
 
            } while (twoHalfBytes++ < 1);
        }
 
        return buf.toString();
    }
/*Método que realiza la encripción a MD5*/
    public static String MD5(String text)
            throws NoSuchAlgorithmException, UnsupportedEncodingException {
        MessageDigest md;
        md = MessageDigest.getInstance("MD5");
        byte[] md5 = new byte[64];
        md.update(text.getBytes("iso-8859-1"), 0, text.length());
        md5 = md.digest();
        return convertedToHex(md5);
    }
    
}