/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.unidaddered.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.grupo.unidaddered.logic.dto.UnidadDeRedDTO;
import co.edu.uniandes.csw.grupo.unidaddered.logic.dto.UnidadDeRedPageDTO;
import co.edu.uniandes.csw.grupo.unidaddered.persistence.api._IUnidadDeRedPersistence;
import co.edu.uniandes.csw.grupo.unidaddered.persistence.converter.UnidadDeRedConverter;
import co.edu.uniandes.csw.grupo.unidaddered.persistence.entity.UnidadDeRedEntity;

public abstract class _UnidadDeRedPersistence implements _IUnidadDeRedPersistence {

  	@PersistenceContext(unitName="RigitalAppPU")
 
	protected EntityManager entityManager;
	
	public UnidadDeRedDTO createUnidadDeRed(UnidadDeRedDTO unidadDeRed) {
		UnidadDeRedEntity entity=UnidadDeRedConverter.persistenceDTO2Entity(unidadDeRed);
		entityManager.persist(entity);
		return UnidadDeRedConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<UnidadDeRedDTO> getUnidadDeReds() {
		Query q = entityManager.createQuery("select u from UnidadDeRedEntity u");
		return UnidadDeRedConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public UnidadDeRedPageDTO getUnidadDeReds(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from UnidadDeRedEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from UnidadDeRedEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		UnidadDeRedPageDTO response = new UnidadDeRedPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(UnidadDeRedConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public UnidadDeRedDTO getUnidadDeRed(Long id) {
		return UnidadDeRedConverter.entity2PersistenceDTO(entityManager.find(UnidadDeRedEntity.class, id));
	}

	public void deleteUnidadDeRed(Long id) {
		UnidadDeRedEntity entity=entityManager.find(UnidadDeRedEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateUnidadDeRed(UnidadDeRedDTO detail) {
		UnidadDeRedEntity entity=entityManager.merge(UnidadDeRedConverter.persistenceDTO2Entity(detail));
		UnidadDeRedConverter.entity2PersistenceDTO(entity);
	}

}