/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.cms.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.grupo.cms.logic.dto.CMSDTO;
import co.edu.uniandes.csw.grupo.cms.logic.dto.CMSPageDTO;
import co.edu.uniandes.csw.grupo.cms.persistence.api._ICMSPersistence;
import co.edu.uniandes.csw.grupo.cms.persistence.converter.CMSConverter;
import co.edu.uniandes.csw.grupo.cms.persistence.entity.CMSEntity;

public abstract class _CMSPersistence implements _ICMSPersistence {

  	@PersistenceContext(unitName="RigitalAppPU")
 
	protected EntityManager entityManager;
	
	public CMSDTO createCMS(CMSDTO cMS) {
		CMSEntity entity=CMSConverter.persistenceDTO2Entity(cMS);
		entityManager.persist(entity);
		return CMSConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<CMSDTO> getCMSs() {
		Query q = entityManager.createQuery("select u from CMSEntity u");
		return CMSConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public CMSPageDTO getCMSs(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from CMSEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from CMSEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		CMSPageDTO response = new CMSPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(CMSConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public CMSDTO getCMS(Long id) {
		return CMSConverter.entity2PersistenceDTO(entityManager.find(CMSEntity.class, id));
	}

	public void deleteCMS(Long id) {
		CMSEntity entity=entityManager.find(CMSEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateCMS(CMSDTO detail) {
		CMSEntity entity=entityManager.merge(CMSConverter.persistenceDTO2Entity(detail));
		CMSConverter.entity2PersistenceDTO(entity);
	}

}