/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.paginaweb.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.grupo.paginaweb.logic.dto.PaginaWebDTO;
import co.edu.uniandes.csw.grupo.paginaweb.logic.api.IPaginaWebLogicService;
import co.edu.uniandes.csw.grupo.paginaweb.master.logic.api._IPaginaWebMasterLogicService;
import co.edu.uniandes.csw.grupo.paginaweb.master.logic.dto.PaginaWebMasterDTO;
import co.edu.uniandes.csw.grupo.problema.logic.api.IProblemaLogicService;
import co.edu.uniandes.csw.grupo.problema.logic.dto.ProblemaDTO;
import javax.inject.Inject;


public abstract class _PaginaWebMasterMockLogicService implements _IPaginaWebMasterLogicService {

    protected static ArrayList<PaginaWebMasterDTO> paginaWebMasterDtosList = new ArrayList<PaginaWebMasterDTO>() ;
    @Inject
    protected IProblemaLogicService problemaPersistance;
    @Inject
    protected IPaginaWebLogicService paginaWebPersistance;

    public PaginaWebMasterDTO createMasterPaginaWeb(PaginaWebMasterDTO paginaWeb) {

        paginaWebPersistance.createPaginaWeb(paginaWeb.getPaginaWebEntity());
        for (ProblemaDTO dto : paginaWeb.getCreateproblema()) {
            problemaPersistance.createProblema(dto);
        }
        paginaWebMasterDtosList.add(paginaWeb);
        return paginaWeb;
    }

    public PaginaWebMasterDTO getMasterPaginaWeb(Long id) {
        for (PaginaWebMasterDTO paginaWebMasterDTO : paginaWebMasterDtosList) {
            if (paginaWebMasterDTO.getPaginaWebEntity().getId() == id) {
                return paginaWebMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterPaginaWeb(Long id) {
        for (PaginaWebMasterDTO paginaWebMasterDTO : paginaWebMasterDtosList) {
            if (paginaWebMasterDTO.getPaginaWebEntity().getId() == id) {

                for (ProblemaDTO dto : paginaWebMasterDTO.getCreateproblema()) {
                    problemaPersistance.deleteProblema(dto.getId());
                }
                paginaWebPersistance.deletePaginaWeb(paginaWebMasterDTO.getId());
                paginaWebMasterDtosList.remove(paginaWebMasterDTO);
            }
        }

    }

    public void updateMasterPaginaWeb(PaginaWebMasterDTO paginaWeb) {

        // update Problema
        if (paginaWeb.getUpdateproblema() != null) {
            for (ProblemaDTO dto : paginaWeb.getUpdateproblema()) {
                problemaPersistance.updateProblema(dto);
            }
        }
        // persist new Problema
        if (paginaWeb.getCreateproblema() != null) {
            for (ProblemaDTO dto : paginaWeb.getCreateproblema()) {
                ProblemaDTO persistedProblemaDTO = problemaPersistance.createProblema(dto);
                dto = persistedProblemaDTO;
            }
        }
        // delete Problema
        if (paginaWeb.getDeleteproblema() != null) {
            for (ProblemaDTO dto : paginaWeb.getDeleteproblema()) {

                problemaPersistance.deleteProblema(dto.getId());
            }
        }
    }
}