/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.mysql.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.grupo.mysql.logic.dto.MySQLPageDTO;
import co.edu.uniandes.csw.grupo.mysql.logic.dto.MySQLDTO;
import co.edu.uniandes.csw.grupo.mysql.logic.api.IMySQLLogicService;
import co.edu.uniandes.csw.grupo.mysql.persistence.MySQLPersistence;
import co.edu.uniandes.csw.grupo.mysql.persistence.api.IMySQLPersistence;
import co.edu.uniandes.csw.grupo.mysql.persistence.entity.MySQLEntity;
import co.edu.uniandes.csw.grupo.mysql.persistence.converter.MySQLConverter;
import static co.edu.uniandes.csw.grupo.util._TestUtil.*;

@RunWith(Arquillian.class)
public class MySQLLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(MySQLLogicService.class.getPackage())
				.addPackage(IMySQLLogicService.class.getPackage())
				.addPackage(MySQLPersistence.class.getPackage())
				.addPackage(MySQLEntity.class.getPackage())
				.addPackage(IMySQLPersistence.class.getPackage())
                .addPackage(MySQLDTO.class.getPackage())
                .addPackage(MySQLConverter.class.getPackage())
                .addPackage(MySQLEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IMySQLLogicService mySQLLogicService;
	
	@Inject
	private IMySQLPersistence mySQLPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<MySQLDTO> dtos=mySQLPersistence.getMySQLs();
		for(MySQLDTO dto:dtos){
			mySQLPersistence.deleteMySQL(dto.getId());
		}
	}

	private List<MySQLDTO> data=new ArrayList<MySQLDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			MySQLDTO pdto=new MySQLDTO();
			pdto.setDescripcionDestino(generateRandom(String.class));
			pdto.setServidor(generateRandom(String.class));
			pdto.setName(generateRandom(String.class));
			pdto.setDescripcion(generateRandom(String.class));
			pdto.setProposito(generateRandom(String.class));
			pdto.setFechaCreacion(generateRandomDate());
			pdto.setDestruido(generateRandom(Boolean.class));
			pdto.setCaracteristicas(generateRandom(String.class));
			pdto.setPgwebId(generateRandom(Long.class));
			pdto.setPaginawebId(generateRandom(Long.class));
			pdto.setEncargadoId(generateRandom(Long.class));
			pdto=mySQLPersistence.createMySQL(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createMySQLTest(){
		MySQLDTO ldto=new MySQLDTO();
		ldto.setDescripcionDestino(generateRandom(String.class));
		ldto.setServidor(generateRandom(String.class));
		ldto.setName(generateRandom(String.class));
		ldto.setDescripcion(generateRandom(String.class));
		ldto.setProposito(generateRandom(String.class));
		ldto.setFechaCreacion(generateRandomDate());
		ldto.setDestruido(generateRandom(Boolean.class));
		ldto.setCaracteristicas(generateRandom(String.class));
		ldto.setPgwebId(generateRandom(Long.class));
		ldto.setPaginawebId(generateRandom(Long.class));
		ldto.setEncargadoId(generateRandom(Long.class));
		
		
		MySQLDTO result=mySQLLogicService.createMySQL(ldto);
		
		Assert.assertNotNull(result);
		
		MySQLDTO pdto=mySQLPersistence.getMySQL(result.getId());
		
		Assert.assertEquals(ldto.getDescripcionDestino(), pdto.getDescripcionDestino());	
		Assert.assertEquals(ldto.getServidor(), pdto.getServidor());	
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getDescripcion(), pdto.getDescripcion());	
		Assert.assertEquals(ldto.getProposito(), pdto.getProposito());	
		Assert.assertEquals(ldto.getFechaCreacion(), pdto.getFechaCreacion());	
		Assert.assertEquals(ldto.getDestruido(), pdto.getDestruido());	
		Assert.assertEquals(ldto.getCaracteristicas(), pdto.getCaracteristicas());	
		Assert.assertEquals(ldto.getPgwebId(), pdto.getPgwebId());	
		Assert.assertEquals(ldto.getPaginawebId(), pdto.getPaginawebId());	
		Assert.assertEquals(ldto.getEncargadoId(), pdto.getEncargadoId());	
	}
	
	@Test
	public void getMySQLsTest(){
		List<MySQLDTO> list=mySQLLogicService.getMySQLs();
		Assert.assertEquals(list.size(), data.size());
        for(MySQLDTO ldto:list){
        	boolean found=false;
            for(MySQLDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getMySQLTest(){
		MySQLDTO pdto=data.get(0);
		MySQLDTO ldto=mySQLLogicService.getMySQL(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getDescripcionDestino(), ldto.getDescripcionDestino());
		Assert.assertEquals(pdto.getServidor(), ldto.getServidor());
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getDescripcion(), ldto.getDescripcion());
		Assert.assertEquals(pdto.getProposito(), ldto.getProposito());
		Assert.assertEquals(pdto.getFechaCreacion(), ldto.getFechaCreacion());
		Assert.assertEquals(pdto.getDestruido(), ldto.getDestruido());
		Assert.assertEquals(pdto.getCaracteristicas(), ldto.getCaracteristicas());
		Assert.assertEquals(pdto.getPgwebId(), ldto.getPgwebId());
		Assert.assertEquals(pdto.getPaginawebId(), ldto.getPaginawebId());
		Assert.assertEquals(pdto.getEncargadoId(), ldto.getEncargadoId());
        
	}
	
	@Test
	public void deleteMySQLTest(){
		MySQLDTO pdto=data.get(0);
		mySQLLogicService.deleteMySQL(pdto.getId());
        MySQLDTO deleted=mySQLPersistence.getMySQL(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateMySQLTest(){
		MySQLDTO pdto=data.get(0);
		
		MySQLDTO ldto=new MySQLDTO();
		ldto.setId(pdto.getId());
		ldto.setDescripcionDestino(generateRandom(String.class));
		ldto.setServidor(generateRandom(String.class));
		ldto.setName(generateRandom(String.class));
		ldto.setDescripcion(generateRandom(String.class));
		ldto.setProposito(generateRandom(String.class));
		ldto.setFechaCreacion(generateRandomDate());
		ldto.setDestruido(generateRandom(Boolean.class));
		ldto.setCaracteristicas(generateRandom(String.class));
		ldto.setPgwebId(generateRandom(Long.class));
		ldto.setPaginawebId(generateRandom(Long.class));
		ldto.setEncargadoId(generateRandom(Long.class));
		
		
		mySQLLogicService.updateMySQL(ldto);
		
		
		MySQLDTO resp=mySQLPersistence.getMySQL(pdto.getId());
		
		Assert.assertEquals(ldto.getDescripcionDestino(), resp.getDescripcionDestino());	
		Assert.assertEquals(ldto.getServidor(), resp.getServidor());	
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getDescripcion(), resp.getDescripcion());	
		Assert.assertEquals(ldto.getProposito(), resp.getProposito());	
		Assert.assertEquals(ldto.getFechaCreacion(), resp.getFechaCreacion());	
		Assert.assertEquals(ldto.getDestruido(), resp.getDestruido());	
		Assert.assertEquals(ldto.getCaracteristicas(), resp.getCaracteristicas());	
		Assert.assertEquals(ldto.getPgwebId(), resp.getPgwebId());	
		Assert.assertEquals(ldto.getPaginawebId(), resp.getPaginawebId());	
		Assert.assertEquals(ldto.getEncargadoId(), resp.getEncargadoId());	
	}
	
	@Test
	public void getMySQLPaginationTest(){
		
		MySQLPageDTO dto1=mySQLLogicService.getMySQLs(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		MySQLPageDTO dto2=mySQLLogicService.getMySQLs(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(MySQLDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(MySQLDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(MySQLDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(MySQLDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        MySQLPageDTO dto3=mySQLLogicService.getMySQLs(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(MySQLDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(MySQLDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}