/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.repositorio.master.logic.dto;

import co.edu.uniandes.csw.grupo.estudiante.logic.dto.EstudianteDTO;
import co.edu.uniandes.csw.grupo.problema.logic.dto.ProblemaDTO;
import co.edu.uniandes.csw.grupo.repositorio.logic.dto.RepositorioDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _RepositorioMasterDTO {

 
    protected RepositorioDTO repositorioEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public RepositorioDTO getRepositorioEntity() {
        return repositorioEntity;
    }

    public void setRepositorioEntity(RepositorioDTO repositorioEntity) {
        this.repositorioEntity = repositorioEntity;
    }
    
    public List<EstudianteDTO> createusuariosQueAcceden;
    public List<EstudianteDTO> updateusuariosQueAcceden;
    public List<EstudianteDTO> deleteusuariosQueAcceden;
    public List<EstudianteDTO> listusuariosQueAcceden;	
    public List<ProblemaDTO> createproblemas;
    public List<ProblemaDTO> updateproblemas;
    public List<ProblemaDTO> deleteproblemas;
    public List<ProblemaDTO> listproblemas;	
	
	
	
    public List<EstudianteDTO> getCreateusuariosQueAcceden(){ return createusuariosQueAcceden; };
    public void setCreateusuariosQueAcceden(List<EstudianteDTO> createusuariosQueAcceden){ this.createusuariosQueAcceden=createusuariosQueAcceden; };
    public List<EstudianteDTO> getUpdateusuariosQueAcceden(){ return updateusuariosQueAcceden; };
    public void setUpdateusuariosQueAcceden(List<EstudianteDTO> updateusuariosQueAcceden){ this.updateusuariosQueAcceden=updateusuariosQueAcceden; };
    public List<EstudianteDTO> getDeleteusuariosQueAcceden(){ return deleteusuariosQueAcceden; };
    public void setDeleteusuariosQueAcceden(List<EstudianteDTO> deleteusuariosQueAcceden){ this.deleteusuariosQueAcceden=deleteusuariosQueAcceden; };
    public List<EstudianteDTO> getListusuariosQueAcceden(){ return listusuariosQueAcceden; };
    public void setListusuariosQueAcceden(List<EstudianteDTO> listusuariosQueAcceden){ this.listusuariosQueAcceden=listusuariosQueAcceden; };	
    public List<ProblemaDTO> getCreateproblemas(){ return createproblemas; };
    public void setCreateproblemas(List<ProblemaDTO> createproblemas){ this.createproblemas=createproblemas; };
    public List<ProblemaDTO> getUpdateproblemas(){ return updateproblemas; };
    public void setUpdateproblemas(List<ProblemaDTO> updateproblemas){ this.updateproblemas=updateproblemas; };
    public List<ProblemaDTO> getDeleteproblemas(){ return deleteproblemas; };
    public void setDeleteproblemas(List<ProblemaDTO> deleteproblemas){ this.deleteproblemas=deleteproblemas; };
    public List<ProblemaDTO> getListproblemas(){ return listproblemas; };
    public void setListproblemas(List<ProblemaDTO> listproblemas){ this.listproblemas=listproblemas; };	
	
	
}

