/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.usuario.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.grupo.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.grupo.usuario.logic.dto.UsuarioPageDTO;
import co.edu.uniandes.csw.grupo.usuario.persistence.api._IUsuarioPersistence;
import co.edu.uniandes.csw.grupo.usuario.persistence.converter.UsuarioConverter;
import co.edu.uniandes.csw.grupo.usuario.persistence.entity.UsuarioEntity;

public abstract class _UsuarioPersistence implements _IUsuarioPersistence {

  	@PersistenceContext(unitName="RigitalAppPU")
 
	protected EntityManager entityManager;
	
	public UsuarioDTO createUsuario(UsuarioDTO usuario) {
		UsuarioEntity entity=UsuarioConverter.persistenceDTO2Entity(usuario);
		entityManager.persist(entity);
		return UsuarioConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<UsuarioDTO> getUsuarios() {
		Query q = entityManager.createQuery("select u from UsuarioEntity u");
		return UsuarioConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public UsuarioPageDTO getUsuarios(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from UsuarioEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from UsuarioEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		UsuarioPageDTO response = new UsuarioPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(UsuarioConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public UsuarioDTO getUsuario(Long id) {
		return UsuarioConverter.entity2PersistenceDTO(entityManager.find(UsuarioEntity.class, id));
	}

	public void deleteUsuario(Long id) {
		UsuarioEntity entity=entityManager.find(UsuarioEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateUsuario(UsuarioDTO detail) {
		UsuarioEntity entity=entityManager.merge(UsuarioConverter.persistenceDTO2Entity(detail));
		UsuarioConverter.entity2PersistenceDTO(entity);
	}

}