/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.mysql.service;

import java.util.List;

import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.QueryParam;
import javax.inject.Inject;

import co.edu.uniandes.csw.grupo.mysql.logic.api.IMySQLLogicService;
import co.edu.uniandes.csw.grupo.mysql.logic.dto.MySQLDTO;
import co.edu.uniandes.csw.grupo.mysql.logic.dto.MySQLPageDTO;


public abstract class _MySQLService {

	@Inject
	protected IMySQLLogicService mySQLLogicService;
	
	@POST
	public MySQLDTO createMySQL(MySQLDTO mySQL){
		return mySQLLogicService.createMySQL(mySQL);
	}
	
	@DELETE
	@Path("{id}")
	public void deleteMySQL(@PathParam("id") Long id){
		mySQLLogicService.deleteMySQL(id);
	}
	
	@GET
	public MySQLPageDTO getMySQLs(@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords){
		return mySQLLogicService.getMySQLs(page, maxRecords);
	}
	
	@GET
	@Path("{id}")
	public MySQLDTO getMySQL(@PathParam("id") Long id){
		return mySQLLogicService.getMySQL(id);
	}
	
	@PUT
	public void updateMySQL(@PathParam("id") Long id, MySQLDTO mySQL){
		mySQLLogicService.updateMySQL(mySQL);
	}
	
}