/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.paginaweb.logic.ejb;

import javax.ejb.EJB;
import javax.ejb.LocalBean;
import javax.ejb.Stateless; 
import javax.inject.Inject;

import javax.enterprise.inject.Default;

import co.edu.uniandes.csw.grupo.paginaweb.logic.api.IPaginaWebLogicService;
import co.edu.uniandes.csw.grupo.paginaweb.logic.dto.PaginaWebPageDTO;

@Default
@Stateless
@LocalBean
public class PaginaWebLogicService extends _PaginaWebLogicService implements IPaginaWebLogicService {

    public PaginaWebPageDTO getPaginasWebByParameters(String formato ,String url ,String alias ,String name ,String descripcion ,String proposito ,String caracteristicas ,String cmsId ,String encargadoId ,String fechaCreacion1,String fechaCreacion2,String ultimaFechaModificacion1,String ultimaFechaModificacion2,String estaDestruido){
        return persistance.getPaginasWebByParameters(formato , url , alias , name , descripcion , proposito , caracteristicas , cmsId , encargadoId , fechaCreacion1, fechaCreacion2, ultimaFechaModificacion1, ultimaFechaModificacion2, estaDestruido);
    }

    public void desactivarRecurso(Long pagina) {
        persistance.desactivarRecurso(pagina);
    }
}