/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.maquinavirtual.master.persistence;
import co.edu.uniandes.csw.grupo.problema.logic.dto.ProblemaDTO;
import co.edu.uniandes.csw.grupo.maquinavirtual.master.persistence.entity.MaquinaVirtualproblemaEntity;
import co.edu.uniandes.csw.grupo.problema.persistence.converter.ProblemaConverter;
import co.edu.uniandes.csw.grupo.maquinavirtual.logic.dto.MaquinaVirtualDTO;
import co.edu.uniandes.csw.grupo.maquinavirtual.master.logic.dto.MaquinaVirtualMasterDTO;
import co.edu.uniandes.csw.grupo.maquinavirtual.master.persistence.api._IMaquinaVirtualMasterPersistence;
import co.edu.uniandes.csw.grupo.maquinavirtual.persistence.api.IMaquinaVirtualPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _MaquinaVirtualMasterPersistence implements _IMaquinaVirtualMasterPersistence {

  	@PersistenceContext(unitName="RigitalAppPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected IMaquinaVirtualPersistence maquinavirtualPersistence;  

    public MaquinaVirtualMasterDTO getMaquinaVirtual(Long maquinavirtualId) {
        MaquinaVirtualMasterDTO maquinavirtualMasterDTO = new MaquinaVirtualMasterDTO();
        MaquinaVirtualDTO maquinavirtual = maquinavirtualPersistence.getMaquinaVirtual(maquinavirtualId);
        maquinavirtualMasterDTO.setMaquinaVirtualEntity(maquinavirtual);
        maquinavirtualMasterDTO.setListproblema(getMaquinaVirtualproblemaEntityList(maquinavirtualId));
        return maquinavirtualMasterDTO;
    }

    public MaquinaVirtualproblemaEntity createMaquinaVirtualproblemaEntity(MaquinaVirtualproblemaEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteMaquinaVirtualproblemaEntity(Long maquinaVirtualId, Long problemaId) {
        Query q = entityManager.createNamedQuery("MaquinaVirtualproblemaEntity.deleteMaquinaVirtualproblemaEntity");
        q.setParameter("maquinaVirtualId", maquinaVirtualId);
        q.setParameter("problemaId", problemaId);
        q.executeUpdate();
    }

    public List<ProblemaDTO> getMaquinaVirtualproblemaEntityList(Long maquinaVirtualId) {
        ArrayList<ProblemaDTO> resp = new ArrayList<ProblemaDTO>();
        Query q = entityManager.createNamedQuery("MaquinaVirtualproblemaEntity.getByMasterId");
        q.setParameter("maquinaVirtualId",maquinaVirtualId);
        List<MaquinaVirtualproblemaEntity> qResult =  q.getResultList();
        for (MaquinaVirtualproblemaEntity entity : qResult) { 
            if(entity.getProblemaIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(ProblemaConverter.entity2PersistenceDTO(entity.getProblemaIdEntity()));
        }
        return resp;
    }

}
