/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.sqldev.master.persistence.entity;

import co.edu.uniandes.csw.grupo.problema.persistence.entity.ProblemaEntity;
import co.edu.uniandes.csw.grupo.sqldev.persistence.entity.SQLDevEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(SQLDevproblemaEntityId.class)
@NamedQueries({
    @NamedQuery(name = "SQLDevproblemaEntity.getByMasterId", query = "SELECT  u FROM SQLDevproblemaEntity u WHERE u.sQLDevId=:sQLDevId"),
    @NamedQuery(name = "SQLDevproblemaEntity.deleteSQLDevproblemaEntity", query = "DELETE FROM SQLDevproblemaEntity u WHERE u.sQLDevId=:sQLDevId and  u.problemaId=:problemaId")
})
public class SQLDevproblemaEntity implements Serializable {

    @Id
    @Column(name = "sQLDevId")
    private Long sQLDevId;
    @Id
    @Column(name = "problemaId")
    private Long problemaId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "sQLDevId", referencedColumnName = "id")
    @JoinFetch
    private ProblemaEntity sQLDevIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "problemaId", referencedColumnName = "id")
    @JoinFetch
    private ProblemaEntity problemaIdEntity; 

    public SQLDevproblemaEntity() {
    }

    public SQLDevproblemaEntity(Long sQLDevId, Long problemaId) {
        this.sQLDevId =sQLDevId;
        this.problemaId = problemaId;
    }

    public Long getSQLDevId() {
        return sQLDevId;
    }

    public void setSQLDevId(Long sQLDevId) {
        this.sQLDevId = sQLDevId;
    }

    public Long getProblemaId() {
        return problemaId;
    }

    public void setProblemaId(Long problemaId) {
        this.problemaId = problemaId;
    }

    public ProblemaEntity getSQLDevIdEntity() {
        return sQLDevIdEntity;
    }

    public void setSQLDevIdEntity(ProblemaEntity sQLDevIdEntity) {
        this.sQLDevIdEntity = sQLDevIdEntity;
    }

    public ProblemaEntity getProblemaIdEntity() {
        return problemaIdEntity;
    }

    public void setProblemaIdEntity(ProblemaEntity problemaIdEntity) {
        this.problemaIdEntity = problemaIdEntity;
    }

}
