/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.sqldev.master.persistence.entity;

import co.edu.uniandes.csw.grupo.estudiante.persistence.entity.EstudianteEntity;
import co.edu.uniandes.csw.grupo.sqldev.persistence.entity.SQLDevEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(SQLDevestudiantesConAccesoEntityId.class)
@NamedQueries({
    @NamedQuery(name = "SQLDevestudiantesConAccesoEntity.getByMasterId", query = "SELECT  u FROM SQLDevestudiantesConAccesoEntity u WHERE u.sQLDevId=:sQLDevId"),
    @NamedQuery(name = "SQLDevestudiantesConAccesoEntity.deleteSQLDevestudiantesConAccesoEntity", query = "DELETE FROM SQLDevestudiantesConAccesoEntity u WHERE u.sQLDevId=:sQLDevId and  u.estudiantesConAccesoId=:estudiantesConAccesoId")
})
public class SQLDevestudiantesConAccesoEntity implements Serializable {

    @Id
    @Column(name = "sQLDevId")
    private Long sQLDevId;
    @Id
    @Column(name = "estudiantesConAccesoId")
    private Long estudiantesConAccesoId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "sQLDevId", referencedColumnName = "id")
    @JoinFetch
    private EstudianteEntity sQLDevIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "estudiantesConAccesoId", referencedColumnName = "id")
    @JoinFetch
    private EstudianteEntity estudiantesConAccesoIdEntity; 

    public SQLDevestudiantesConAccesoEntity() {
    }

    public SQLDevestudiantesConAccesoEntity(Long sQLDevId, Long estudiantesConAccesoId) {
        this.sQLDevId =sQLDevId;
        this.estudiantesConAccesoId = estudiantesConAccesoId;
    }

    public Long getSQLDevId() {
        return sQLDevId;
    }

    public void setSQLDevId(Long sQLDevId) {
        this.sQLDevId = sQLDevId;
    }

    public Long getEstudiantesConAccesoId() {
        return estudiantesConAccesoId;
    }

    public void setEstudiantesConAccesoId(Long estudiantesConAccesoId) {
        this.estudiantesConAccesoId = estudiantesConAccesoId;
    }

    public EstudianteEntity getSQLDevIdEntity() {
        return sQLDevIdEntity;
    }

    public void setSQLDevIdEntity(EstudianteEntity sQLDevIdEntity) {
        this.sQLDevIdEntity = sQLDevIdEntity;
    }

    public EstudianteEntity getEstudiantesConAccesoIdEntity() {
        return estudiantesConAccesoIdEntity;
    }

    public void setEstudiantesConAccesoIdEntity(EstudianteEntity estudiantesConAccesoIdEntity) {
        this.estudiantesConAccesoIdEntity = estudiantesConAccesoIdEntity;
    }

}
