/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.workstation.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.grupo.workstation.logic.dto.WorkstationDTO;
import co.edu.uniandes.csw.grupo.workstation.persistence.entity.WorkstationEntity;

public abstract class _WorkstationConverter {

	public static WorkstationDTO entity2PersistenceDTO(WorkstationEntity entity){
		if (entity != null) {
			WorkstationDTO dto = new WorkstationDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setDuenio(entity.getDuenio());
					dto.setDestino(entity.getDestino());
					dto.setSistemaOperativo(entity.getSistemaOperativo());
			return dto;
		}else{
			return null;
		}
	}
	
	public static WorkstationEntity persistenceDTO2Entity(WorkstationDTO dto){
		if(dto!=null){
			WorkstationEntity entity=new WorkstationEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setDuenio(dto.getDuenio());
			
					entity.setDestino(dto.getDestino());
			
					entity.setSistemaOperativo(dto.getSistemaOperativo());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<WorkstationDTO> entity2PersistenceDTOList(List<WorkstationEntity> entities){
		List<WorkstationDTO> dtos=new ArrayList<WorkstationDTO>();
		for(WorkstationEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<WorkstationEntity> persistenceDTO2EntityList(List<WorkstationDTO> dtos){
		List<WorkstationEntity> entities=new ArrayList<WorkstationEntity>();
		for(WorkstationDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}