/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.empleado.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.grupo.empleado.logic.dto.EmpleadoPageDTO;
import co.edu.uniandes.csw.grupo.empleado.logic.dto.EmpleadoDTO;
import co.edu.uniandes.csw.grupo.empleado.persistence.api.IEmpleadoPersistence;
import co.edu.uniandes.csw.grupo.empleado.persistence.entity.EmpleadoEntity;
import co.edu.uniandes.csw.grupo.empleado.persistence.converter.EmpleadoConverter;
import static co.edu.uniandes.csw.grupo.util._TestUtil.*;

@RunWith(Arquillian.class)
public class EmpleadoPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(EmpleadoPersistence.class.getPackage())
				.addPackage(EmpleadoEntity.class.getPackage())
				.addPackage(IEmpleadoPersistence.class.getPackage())
                .addPackage(EmpleadoDTO.class.getPackage())
                .addPackage(EmpleadoConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IEmpleadoPersistence empleadoPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from EmpleadoEntity").executeUpdate();
	}

	private List<EmpleadoEntity> data=new ArrayList<EmpleadoEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			EmpleadoEntity entity=new EmpleadoEntity();
			entity.setPassword(generateRandom(String.class));
			entity.setName(generateRandom(String.class));
			entity.setLogin(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createEmpleadoTest(){
		EmpleadoDTO dto=new EmpleadoDTO();
		dto.setPassword(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		dto.setLogin(generateRandom(String.class));
		
		EmpleadoDTO result=empleadoPersistence.createEmpleado(dto);
		
		Assert.assertNotNull(result);
		
		EmpleadoEntity entity=em.find(EmpleadoEntity.class, result.getId());
		
		Assert.assertEquals(dto.getPassword(), entity.getPassword());
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getLogin(), entity.getLogin());
	}
	
	@Test
	public void getEmpleadosTest(){
		List<EmpleadoDTO> list=empleadoPersistence.getEmpleados();
		Assert.assertEquals(list.size(), data.size());
        for(EmpleadoDTO dto:list){
        	boolean found=false;
            for(EmpleadoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getEmpleadoTest(){
		EmpleadoEntity entity=data.get(0);
		EmpleadoDTO dto=empleadoPersistence.getEmpleado(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getPassword(), dto.getPassword());
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getLogin(), dto.getLogin());
        
	}
	
	@Test
	public void deleteEmpleadoTest(){
		EmpleadoEntity entity=data.get(0);
		empleadoPersistence.deleteEmpleado(entity.getId());
        EmpleadoEntity deleted=em.find(EmpleadoEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateEmpleadoTest(){
		EmpleadoEntity entity=data.get(0);
		
		EmpleadoDTO dto=new EmpleadoDTO();
		dto.setId(entity.getId());
		dto.setPassword(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		dto.setLogin(generateRandom(String.class));
		
		
		empleadoPersistence.updateEmpleado(dto);
		
		
		EmpleadoEntity resp=em.find(EmpleadoEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getPassword(), resp.getPassword());	
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getLogin(), resp.getLogin());	
	}
	
	@Test
	public void getEmpleadoPaginationTest(){
		//Page 1
		EmpleadoPageDTO dto1=empleadoPersistence.getEmpleados(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        EmpleadoPageDTO dto2=empleadoPersistence.getEmpleados(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(EmpleadoDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(EmpleadoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(EmpleadoDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(EmpleadoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}