/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.paginaweb.persistence;

import co.edu.uniandes.csw.grupo.paginaweb.logic.dto.PaginaWebDTO;
import co.edu.uniandes.csw.grupo.paginaweb.logic.dto.PaginaWebPageDTO;
import javax.ejb.Stateless;
import javax.enterprise.inject.Default;

import co.edu.uniandes.csw.grupo.paginaweb.persistence.api.IPaginaWebPersistence;
import co.edu.uniandes.csw.grupo.paginaweb.persistence.converter.PaginaWebConverter;
import java.util.Date;
import javax.ejb.LocalBean;
import javax.persistence.Query;

@Default
@Stateless 
@LocalBean
public class PaginaWebPersistence extends _PaginaWebPersistence  implements IPaginaWebPersistence {

//    @Override
//    public PaginaWebDTO createPaginaWeb(PaginaWebDTO wiki) {
//                PaginaWebEntity entity=PaginaWebConverter.persistenceDTO2Entity(wiki);
//		entityManager.persist(entity);
//                
//                PaginaWebDTO rta = PaginaWebConverter.entity2PersistenceDTO(entity);
//                Long id = rta.getId();
//                Long idEncargado = rta.getEncargadoId();
//                
//                if(idEncargado != 0)
//                {
//                    System.out.println("ID: " + id);
//                    System.out.println("ID Encargado: " + idEncargado);
//
//                    EncargadopaginaWebEntity este = new EncargadopaginaWebEntity(idEncargado, id);  
//                    entityManager.persist(este);
//
//                }
//                
//		return rta;
//    }
    
    
    @SuppressWarnings("unchecked")
    public PaginaWebPageDTO getPaginasWebByParameters(String formato ,String url ,String alias ,String name ,String descripcion ,String proposito ,String caracteristicas ,String cmsId ,String encargadoId ,String fechaCreacion1,String fechaCreacion2,String ultimaFechaModificacion1,String ultimaFechaModificacion2,String estaDestruido)
    {
        Query count = entityManager.createQuery("select count(u) from PaginaWebEntity u");
        Long regCount = 0L;
        regCount = Long.parseLong(count.getSingleResult().toString());
                
        String sql = "SELECT u FROM PaginaWebEntity u WHERE";
        if(!formato.isEmpty())
            sql += " AND u.formato like :formato";
        if(!url.isEmpty())
            sql += " AND u.url like :url";
        if(!alias.isEmpty())
            sql += " AND u.alias like :alias";
        if(!name.isEmpty())
            sql  += " AND u.name like :name";
        if(!descripcion.isEmpty())
            sql += " AND u.descripcion like :descripcion";
        if(!proposito.isEmpty())
            sql += " AND  u.proposito like :proposito";
        if(!caracteristicas.isEmpty())
            sql += " AND  u.caracteristicas like :caracteristicas";       
        
        if(!cmsId.isEmpty())
            sql += " AND  u.cmsId = :cmsId";
        if(!encargadoId.isEmpty())
            sql += " AND  u.encargadoId = :encargadoId";
        
        if(!estaDestruido.isEmpty())
            sql += " AND  u.destruido = :estaDestruido";
        
        if(!fechaCreacion1.isEmpty() && !fechaCreacion2.isEmpty())
            sql += " AND u.fechaCreacion BETWEEN :fechaCreacion1 and :fechaCreacion2";

        if(!ultimaFechaModificacion1.isEmpty() && !ultimaFechaModificacion2.isEmpty())
            sql += " AND u.ultimaFechaModificacion BETWEEN :ultimaFechaModificacion1 and :ultimaFechaModificacion2";
        // Se limpia la sentencia sql
        
        if(sql.endsWith("WHERE"))
            sql = sql.replace("WHERE", "");
        if(sql.contains("WHERE AND"))
            sql = sql.replace("WHERE AND", "WHERE");
        
        System.out.println(sql);
        
        boolean destruido = false;
        
        if(estaDestruido.equals("1"))
            destruido = true;
        
        Query q = entityManager.createQuery(sql);
        
        
        if(!formato.isEmpty())
            q.setParameter("formato", "%"+formato+"%");
        if(!url .isEmpty())
            q.setParameter("url", "%"+url +"%");
        if(!alias.isEmpty())
            q.setParameter("alias", "%"+alias+"%");
        if(!name.isEmpty())
            q.setParameter("name", "%"+name+"%");
        if(!descripcion.isEmpty())
            q.setParameter("descripcion", "%"+descripcion+"%");
        if(!proposito.isEmpty())
            q.setParameter("proposito", "%"+proposito+"%");
        if(!caracteristicas.isEmpty())
            q.setParameter("caracteristicas", "%"+caracteristicas+"%");
               
        if(!cmsId.isEmpty())
            q.setParameter("cmsId", Long.parseLong(cmsId));
        if(!encargadoId.isEmpty())
            q.setParameter("encargadoId", Long.parseLong(encargadoId));

        if(!estaDestruido.isEmpty())
            q.setParameter("estaDestruido", destruido);
        
        if(!fechaCreacion1.isEmpty() && !fechaCreacion2.isEmpty())
        {
            String[] a1 = fechaCreacion1.split("-");
            String[] a2 = fechaCreacion2.split("-");
            
            Date fecha1 = new Date(Integer.parseInt(a1[0])-1900, Integer.parseInt(a1[1]),Integer.parseInt(a1[2]));
            Date fecha2 = new Date(Integer.parseInt(a2[0])-1900, Integer.parseInt(a2[1]),Integer.parseInt(a2[2]));
            
            q.setParameter("fechaCreacion1", fecha1);
            q.setParameter("fechaCreacion2", fecha2);            
        }
        
        if(!ultimaFechaModificacion1.isEmpty() && !ultimaFechaModificacion2.isEmpty())
        {
            String[] a1 = ultimaFechaModificacion1.split("-");
            String[] a2 = ultimaFechaModificacion2.split("-");
            
            Date fecha1 = new Date(Integer.parseInt(a1[0])-1900, Integer.parseInt(a1[1]),Integer.parseInt(a1[2]));
            Date fecha2 = new Date(Integer.parseInt(a2[0])-1900, Integer.parseInt(a2[1]),Integer.parseInt(a2[2]));
            
            q.setParameter("ultimaFechaModificacion1", fecha1);
            q.setParameter("ultimaFechaModificacion2", fecha2);            
        }
        
        
        PaginaWebPageDTO response = new PaginaWebPageDTO();
        response.setTotalRecords(regCount);
        response.setRecords(PaginaWebConverter.entity2PersistenceDTOList(q.getResultList()));
        return response;
    }

    public void desactivarRecurso(Long pagina) {
        Query query= entityManager.createQuery("UPDATE PaginaWebEntity p SET p.destruido='false' WHERE p.id = :pagina");
        query.setParameter("pagina", pagina);
        query.executeUpdate();

    }

}