/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.maquinavirtual.master.logic.ejb;

import co.edu.uniandes.csw.grupo.problema.logic.dto.ProblemaDTO;
import co.edu.uniandes.csw.grupo.problema.persistence.api.IProblemaPersistence;
import co.edu.uniandes.csw.grupo.maquinavirtual.logic.dto.MaquinaVirtualDTO;
import co.edu.uniandes.csw.grupo.maquinavirtual.master.logic.api._IMaquinaVirtualMasterLogicService;
import co.edu.uniandes.csw.grupo.maquinavirtual.master.logic.dto.MaquinaVirtualMasterDTO;
import co.edu.uniandes.csw.grupo.maquinavirtual.master.persistence.api.IMaquinaVirtualMasterPersistence;
import co.edu.uniandes.csw.grupo.maquinavirtual.master.persistence.entity.MaquinaVirtualproblemaEntity;
import co.edu.uniandes.csw.grupo.maquinavirtual.persistence.api.IMaquinaVirtualPersistence;
import javax.inject.Inject;

public abstract class _MaquinaVirtualMasterLogicService implements _IMaquinaVirtualMasterLogicService {

    @Inject
    protected IMaquinaVirtualPersistence maquinavirtualPersistance;
    @Inject
    protected IMaquinaVirtualMasterPersistence maquinavirtualMasterPersistance;
    @Inject
    protected IProblemaPersistence problemaPersistance;

    public MaquinaVirtualMasterDTO createMasterMaquinaVirtual(MaquinaVirtualMasterDTO maquinavirtual) {
        MaquinaVirtualDTO persistedMaquinaVirtualDTO = maquinavirtualPersistance.createMaquinaVirtual(maquinavirtual.getMaquinaVirtualEntity());
        if (maquinavirtual.getCreateproblema() != null) {
            for (ProblemaDTO problemaDTO : maquinavirtual.getCreateproblema()) {
                ProblemaDTO createdProblemaDTO = problemaPersistance.createProblema(problemaDTO);
                MaquinaVirtualproblemaEntity maquinavirtualProblemaEntity = new MaquinaVirtualproblemaEntity(persistedMaquinaVirtualDTO.getId(), createdProblemaDTO.getId());
                maquinavirtualMasterPersistance.createMaquinaVirtualproblemaEntity(maquinavirtualProblemaEntity);
            }
        }
        // update problema
        if (maquinavirtual.getUpdateproblema() != null) {
            for (ProblemaDTO problemaDTO : maquinavirtual.getUpdateproblema()) {
                problemaPersistance.updateProblema(problemaDTO);
                MaquinaVirtualproblemaEntity maquinavirtualProblemaEntity = new MaquinaVirtualproblemaEntity(persistedMaquinaVirtualDTO.getId(), problemaDTO.getId());
                maquinavirtualMasterPersistance.createMaquinaVirtualproblemaEntity(maquinavirtualProblemaEntity);
            }
        }
        return maquinavirtual;
    }

    public MaquinaVirtualMasterDTO getMasterMaquinaVirtual(Long id) {
        return maquinavirtualMasterPersistance.getMaquinaVirtual(id);
    }

    public void deleteMasterMaquinaVirtual(Long id) {
        maquinavirtualPersistance.deleteMaquinaVirtual(id);
    }

    public void updateMasterMaquinaVirtual(MaquinaVirtualMasterDTO maquinavirtual) {
        maquinavirtualPersistance.updateMaquinaVirtual(maquinavirtual.getMaquinaVirtualEntity());

        //---- FOR RELATIONSHIP
        // delete problema
        if (maquinavirtual.getDeleteproblema() != null) {
            for (ProblemaDTO problemaDTO : maquinavirtual.getDeleteproblema()) {
                maquinavirtualMasterPersistance.deleteMaquinaVirtualproblemaEntity(maquinavirtual.getMaquinaVirtualEntity().getId(), problemaDTO.getId());
            }
        }
        // persist new problema
        if (maquinavirtual.getCreateproblema() != null) {
            for (ProblemaDTO problemaDTO : maquinavirtual.getCreateproblema()) {
                MaquinaVirtualproblemaEntity maquinavirtualProblemaEntity = new MaquinaVirtualproblemaEntity(maquinavirtual.getMaquinaVirtualEntity().getId(), problemaDTO.getId());
                maquinavirtualMasterPersistance.createMaquinaVirtualproblemaEntity(maquinavirtualProblemaEntity);
            }
        }
        // update problema
        if (maquinavirtual.getUpdateproblema() != null) {
            for (ProblemaDTO problemaDTO : maquinavirtual.getUpdateproblema()) {
                maquinavirtualMasterPersistance.deleteMaquinaVirtualproblemaEntity(maquinavirtual.getMaquinaVirtualEntity().getId(), problemaDTO.getId());
                problemaPersistance.updateProblema(problemaDTO);
                MaquinaVirtualproblemaEntity maquinavirtualProblemaEntity = new MaquinaVirtualproblemaEntity(maquinavirtual.getId(), problemaDTO.getId());
                maquinavirtualMasterPersistance.createMaquinaVirtualproblemaEntity(maquinavirtualProblemaEntity);
                
            }
        }
    }
}
