/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.workstation.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.grupo.workstation.logic.dto.WorkstationDTO;
import co.edu.uniandes.csw.grupo.workstation.logic.dto.WorkstationPageDTO;
import co.edu.uniandes.csw.grupo.workstation.persistence.api._IWorkstationPersistence;
import co.edu.uniandes.csw.grupo.workstation.persistence.converter.WorkstationConverter;
import co.edu.uniandes.csw.grupo.workstation.persistence.entity.WorkstationEntity;

public abstract class _WorkstationPersistence implements _IWorkstationPersistence {

  	@PersistenceContext(unitName="RigitalAppPU")
 
	protected EntityManager entityManager;
	
	public WorkstationDTO createWorkstation(WorkstationDTO workstation) {
		WorkstationEntity entity=WorkstationConverter.persistenceDTO2Entity(workstation);
		entityManager.persist(entity);
		return WorkstationConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<WorkstationDTO> getWorkstations() {
		Query q = entityManager.createQuery("select u from WorkstationEntity u");
		return WorkstationConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public WorkstationPageDTO getWorkstations(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from WorkstationEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from WorkstationEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		WorkstationPageDTO response = new WorkstationPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(WorkstationConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public WorkstationDTO getWorkstation(Long id) {
		return WorkstationConverter.entity2PersistenceDTO(entityManager.find(WorkstationEntity.class, id));
	}

	public void deleteWorkstation(Long id) {
		WorkstationEntity entity=entityManager.find(WorkstationEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateWorkstation(WorkstationDTO detail) {
		WorkstationEntity entity=entityManager.merge(WorkstationConverter.persistenceDTO2Entity(detail));
		WorkstationConverter.entity2PersistenceDTO(entity);
	}

}