/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.workstation.persistence;

import co.edu.uniandes.csw.grupo.workstation.logic.dto.WorkstationDTO;
import co.edu.uniandes.csw.grupo.workstation.logic.dto.WorkstationPageDTO;
import co.edu.uniandes.csw.grupo.workstation.persistence.api.IWorkstationPersistence;
import co.edu.uniandes.csw.grupo.workstation.persistence.converter.WorkstationConverter;
import co.edu.uniandes.csw.grupo.workstation.persistence.entity.WorkstationEntity;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import javax.ejb.LocalBean;
import javax.ejb.Stateless;
import javax.enterprise.inject.Default;
import javax.persistence.Query;

@Default
@Stateless 
@LocalBean
public class WorkstationPersistence extends _WorkstationPersistence  implements IWorkstationPersistence {

    @SuppressWarnings("unchecked")
    public WorkstationPageDTO getWorkStationsByParameters(String name ,String duenio ,String destino , String sistemaOperativo )
    {
        Query count = entityManager.createQuery("select count(u) from WorkstationEntity u");
        Long regCount = 0L;
        regCount = Long.parseLong(count.getSingleResult().toString());
                
        String sql = "SELECT u FROM WorkstationEntity u WHERE";
        if(!name.isEmpty())
            sql += " AND u.name like :name";
        if(!duenio.isEmpty())
            sql += " AND u.duenio like :duenio";
        if(!destino.isEmpty())
            sql += " AND u.destino like :destino";
        if(!sistemaOperativo.isEmpty())
            sql  += " AND u.sistemaOperativo like :sistemaOperativo";
        
        // Se limpia la sentencia sql
        
        if(sql.endsWith("WHERE"))
            sql = sql.replace("WHERE", "");
        if(sql.contains("WHERE AND"))
            sql = sql.replace("WHERE AND", "WHERE");
        
        System.out.println(sql);        
                
        Query q = entityManager.createQuery(sql);
        
        if(!name.isEmpty())
            q.setParameter("name", "%"+name+"%");
        if(!duenio .isEmpty())
            q.setParameter("duenio", "%"+duenio +"%");
        if(!destino.isEmpty())
            q.setParameter("destino", "%"+destino+"%");
        if(!sistemaOperativo.isEmpty())
            q.setParameter("sistemaOperativo", "%"+sistemaOperativo+"%");
                
        WorkstationPageDTO response = new WorkstationPageDTO();
        response.setTotalRecords(regCount);
        response.setRecords(WorkstationConverter.entity2PersistenceDTOList(q.getResultList()));
        return response;
        
           
    }
    
    @SuppressWarnings("unchecked")
    public void loadWorkstations()
    {
      try{  
        String archivo = "\\Archivos csv\\Worstationscsv.csv";
        File file = new File(archivo);
        BufferedReader reader = new BufferedReader(new FileReader(file));
        reader.readLine();
        
        for(long i = 0; i < file.length();i++)
        {
            String actual= reader.readLine();
            String[] act = actual.split(";");
            WorkstationEntity entity = new WorkstationEntity();
            entity.setDestino(act[0]);
            entity.setDuenio(act[1]);
            entity.setSistemaOperativo("Windows Server 2008 R2");
            entityManager.persist(entity);
        }
      }
      catch(IOException e){
          
      }
        
    }        

    
}