/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.mysql.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.grupo.mysql.logic.dto.MySQLDTO;
import co.edu.uniandes.csw.grupo.mysql.logic.api.IMySQLLogicService;
import co.edu.uniandes.csw.grupo.mysql.master.logic.api._IMySQLMasterLogicService;
import co.edu.uniandes.csw.grupo.mysql.master.logic.dto.MySQLMasterDTO;
import co.edu.uniandes.csw.grupo.problema.logic.api.IProblemaLogicService;
import co.edu.uniandes.csw.grupo.problema.logic.dto.ProblemaDTO;
import javax.inject.Inject;


public abstract class _MySQLMasterMockLogicService implements _IMySQLMasterLogicService {

    protected static ArrayList<MySQLMasterDTO> mySQLMasterDtosList = new ArrayList<MySQLMasterDTO>() ;
    @Inject
    protected IProblemaLogicService problemaPersistance;
    @Inject
    protected IMySQLLogicService mySQLPersistance;

    public MySQLMasterDTO createMasterMySQL(MySQLMasterDTO mySQL) {

        mySQLPersistance.createMySQL(mySQL.getMySQLEntity());
        for (ProblemaDTO dto : mySQL.getCreateproblema()) {
            problemaPersistance.createProblema(dto);
        }
        mySQLMasterDtosList.add(mySQL);
        return mySQL;
    }

    public MySQLMasterDTO getMasterMySQL(Long id) {
        for (MySQLMasterDTO mySQLMasterDTO : mySQLMasterDtosList) {
            if (mySQLMasterDTO.getMySQLEntity().getId() == id) {
                return mySQLMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterMySQL(Long id) {
        for (MySQLMasterDTO mySQLMasterDTO : mySQLMasterDtosList) {
            if (mySQLMasterDTO.getMySQLEntity().getId() == id) {

                for (ProblemaDTO dto : mySQLMasterDTO.getCreateproblema()) {
                    problemaPersistance.deleteProblema(dto.getId());
                }
                mySQLPersistance.deleteMySQL(mySQLMasterDTO.getId());
                mySQLMasterDtosList.remove(mySQLMasterDTO);
            }
        }

    }

    public void updateMasterMySQL(MySQLMasterDTO mySQL) {

        // update Problema
        if (mySQL.getUpdateproblema() != null) {
            for (ProblemaDTO dto : mySQL.getUpdateproblema()) {
                problemaPersistance.updateProblema(dto);
            }
        }
        // persist new Problema
        if (mySQL.getCreateproblema() != null) {
            for (ProblemaDTO dto : mySQL.getCreateproblema()) {
                ProblemaDTO persistedProblemaDTO = problemaPersistance.createProblema(dto);
                dto = persistedProblemaDTO;
            }
        }
        // delete Problema
        if (mySQL.getDeleteproblema() != null) {
            for (ProblemaDTO dto : mySQL.getDeleteproblema()) {

                problemaPersistance.deleteProblema(dto.getId());
            }
        }
    }
}