/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.unidaddered.service;

import co.edu.uniandes.csw.grupo.maquinavirtual.logic.dto.MaquinaVirtualPageDTO;
import co.edu.uniandes.csw.grupo.unidaddered.logic.dto.UnidadDeRedPageDTO;
import co.edu.uniandes.csw.grupo.wiki.logic.dto.WikiPageDTO;
import java.util.List;

import javax.ejb.Stateless;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.MultivaluedMap;
import javax.ws.rs.core.UriInfo;

@Path("/UnidadDeRed")
@Stateless
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public class UnidadDeRedService extends _UnidadDeRedService {

    @Context
    UriInfo uriInfo;
    
    @GET
    @Override
    public UnidadDeRedPageDTO getUnidadDeReds(@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords){
		return super.getUnidadDeReds(page, maxRecords);
    }
    
    @GET
    @Path("/Search")
    public UnidadDeRedPageDTO searchUnidadesDeRed(@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords){
        
        MultivaluedMap<String, String> queryParams = uriInfo.getQueryParameters();
        
        System.out.println(queryParams.keySet());
        System.out.println(queryParams.values());
        
        // Estos atributos podrán ser vacios o tener valores
        // Si estan vacíos no se incluirán en la búsqueda
        
        String tipos = queryParams.getFirst("tipos");
        String servidor = queryParams.getFirst("servidor");
        String url = queryParams.getFirst("url");        
        String name = queryParams.getFirst("name");
        String descripcion = queryParams.getFirst("descripcion");
        String proposito = queryParams.getFirst("proposito");
        String caracteristicas = queryParams.getFirst("caracteristicas");
        String encargadoId = queryParams.getFirst("encargadoId");
       
        // Estos atributos, en cambio, siempre poseeran valores estándar.
        // Se debe aclarar eso en el manual de uso.
                       
        String fechaCreac1 = queryParams.getFirst("fechaCreacion");
        String fechaCreac2 = queryParams.getFirst("fechaCreacion2");
        
        String destruido = queryParams.getFirst("destruido");
        
        String estaDestruido = "";

        
        if(tipos == null)
            tipos = "";
        if(servidor == null)
            servidor = "";
        if(url == null)
            url = "";
        if(name == null)
            name = "";
        if(descripcion == null)
            descripcion = "";
        if(proposito == null)
            proposito = "";
        if(caracteristicas == null)
            caracteristicas = "";
        if(encargadoId == null)
            encargadoId = "";
        if(destruido == null)
            destruido = "";
        
               
        String fechaCreacion1 = "";
        String fechaCreacion2 = "";
        
        if(!fechaCreac1.isEmpty() && fechaCreac1 != null)
        {
            String[] date1 = fechaCreac1.split("%2F");
            fechaCreacion1 = date1[2] + "-" + date1[1] + "-" + date1[0];
        }       
        
        if(!fechaCreac2.isEmpty() && fechaCreac2 != null)
        {
            String[] date2 = fechaCreac2.split("%2F");            
            fechaCreacion2 = date2[2] + "-" + date2[1] + "-" + date2[0];

        }
                
        if(destruido.isEmpty())       
            estaDestruido = "1";
        else
            estaDestruido = "0";   
        
        
        return unidadDeRedLogicService.getUnidadesDeRedByParameters(tipos , servidor , url , name , descripcion , proposito , caracteristicas , encargadoId, fechaCreacion1, fechaCreacion2, estaDestruido);
    }
    
    @GET
    @Path("/Desactivar")
    public UnidadDeRedPageDTO desactivarUnidadesDeRed(@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords)
    {
        MultivaluedMap<String, String> queryParams = uriInfo.getQueryParameters();
        System.out.println(queryParams.keySet());
        System.out.println(queryParams.values());
        for(int i=0;i<queryParams.size()-2;i++)
        {
            Long id= Long.parseLong(queryParams.getFirst(i+""));
            unidadDeRedLogicService.desactivarRecurso(id);   
        }
        return super.getUnidadDeReds(page, maxRecords);
    }

}