/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.maquinavirtual.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.grupo.maquinavirtual.logic.dto.MaquinaVirtualDTO;
import co.edu.uniandes.csw.grupo.maquinavirtual.logic.api.IMaquinaVirtualLogicService;
import co.edu.uniandes.csw.grupo.maquinavirtual.master.logic.api._IMaquinaVirtualMasterLogicService;
import co.edu.uniandes.csw.grupo.maquinavirtual.master.logic.dto.MaquinaVirtualMasterDTO;
import co.edu.uniandes.csw.grupo.problema.logic.api.IProblemaLogicService;
import co.edu.uniandes.csw.grupo.problema.logic.dto.ProblemaDTO;
import javax.inject.Inject;


public abstract class _MaquinaVirtualMasterMockLogicService implements _IMaquinaVirtualMasterLogicService {

    protected static ArrayList<MaquinaVirtualMasterDTO> maquinaVirtualMasterDtosList = new ArrayList<MaquinaVirtualMasterDTO>() ;
    @Inject
    protected IProblemaLogicService problemaPersistance;
    @Inject
    protected IMaquinaVirtualLogicService maquinaVirtualPersistance;

    public MaquinaVirtualMasterDTO createMasterMaquinaVirtual(MaquinaVirtualMasterDTO maquinaVirtual) {

        maquinaVirtualPersistance.createMaquinaVirtual(maquinaVirtual.getMaquinaVirtualEntity());
        for (ProblemaDTO dto : maquinaVirtual.getCreateproblema()) {
            problemaPersistance.createProblema(dto);
        }
        maquinaVirtualMasterDtosList.add(maquinaVirtual);
        return maquinaVirtual;
    }

    public MaquinaVirtualMasterDTO getMasterMaquinaVirtual(Long id) {
        for (MaquinaVirtualMasterDTO maquinaVirtualMasterDTO : maquinaVirtualMasterDtosList) {
            if (maquinaVirtualMasterDTO.getMaquinaVirtualEntity().getId() == id) {
                return maquinaVirtualMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterMaquinaVirtual(Long id) {
        for (MaquinaVirtualMasterDTO maquinaVirtualMasterDTO : maquinaVirtualMasterDtosList) {
            if (maquinaVirtualMasterDTO.getMaquinaVirtualEntity().getId() == id) {

                for (ProblemaDTO dto : maquinaVirtualMasterDTO.getCreateproblema()) {
                    problemaPersistance.deleteProblema(dto.getId());
                }
                maquinaVirtualPersistance.deleteMaquinaVirtual(maquinaVirtualMasterDTO.getId());
                maquinaVirtualMasterDtosList.remove(maquinaVirtualMasterDTO);
            }
        }

    }

    public void updateMasterMaquinaVirtual(MaquinaVirtualMasterDTO maquinaVirtual) {

        // update Problema
        if (maquinaVirtual.getUpdateproblema() != null) {
            for (ProblemaDTO dto : maquinaVirtual.getUpdateproblema()) {
                problemaPersistance.updateProblema(dto);
            }
        }
        // persist new Problema
        if (maquinaVirtual.getCreateproblema() != null) {
            for (ProblemaDTO dto : maquinaVirtual.getCreateproblema()) {
                ProblemaDTO persistedProblemaDTO = problemaPersistance.createProblema(dto);
                dto = persistedProblemaDTO;
            }
        }
        // delete Problema
        if (maquinaVirtual.getDeleteproblema() != null) {
            for (ProblemaDTO dto : maquinaVirtual.getDeleteproblema()) {

                problemaPersistance.deleteProblema(dto.getId());
            }
        }
    }
}