/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.maquinavirtual.master.persistence.entity;

import co.edu.uniandes.csw.grupo.problema.persistence.entity.ProblemaEntity;
import co.edu.uniandes.csw.grupo.maquinavirtual.persistence.entity.MaquinaVirtualEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(MaquinaVirtualproblemaEntityId.class)
@NamedQueries({
    @NamedQuery(name = "MaquinaVirtualproblemaEntity.getByMasterId", query = "SELECT  u FROM MaquinaVirtualproblemaEntity u WHERE u.maquinaVirtualId=:maquinaVirtualId"),
    @NamedQuery(name = "MaquinaVirtualproblemaEntity.deleteMaquinaVirtualproblemaEntity", query = "DELETE FROM MaquinaVirtualproblemaEntity u WHERE u.maquinaVirtualId=:maquinaVirtualId and  u.problemaId=:problemaId")
})
public class MaquinaVirtualproblemaEntity implements Serializable {

    @Id
    @Column(name = "maquinaVirtualId")
    private Long maquinaVirtualId;
    @Id
    @Column(name = "problemaId")
    private Long problemaId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "maquinaVirtualId", referencedColumnName = "id")
    @JoinFetch
    private ProblemaEntity maquinaVirtualIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "problemaId", referencedColumnName = "id")
    @JoinFetch
    private ProblemaEntity problemaIdEntity; 

    public MaquinaVirtualproblemaEntity() {
    }

    public MaquinaVirtualproblemaEntity(Long maquinaVirtualId, Long problemaId) {
        this.maquinaVirtualId =maquinaVirtualId;
        this.problemaId = problemaId;
    }

    public Long getMaquinaVirtualId() {
        return maquinaVirtualId;
    }

    public void setMaquinaVirtualId(Long maquinaVirtualId) {
        this.maquinaVirtualId = maquinaVirtualId;
    }

    public Long getProblemaId() {
        return problemaId;
    }

    public void setProblemaId(Long problemaId) {
        this.problemaId = problemaId;
    }

    public ProblemaEntity getMaquinaVirtualIdEntity() {
        return maquinaVirtualIdEntity;
    }

    public void setMaquinaVirtualIdEntity(ProblemaEntity maquinaVirtualIdEntity) {
        this.maquinaVirtualIdEntity = maquinaVirtualIdEntity;
    }

    public ProblemaEntity getProblemaIdEntity() {
        return problemaIdEntity;
    }

    public void setProblemaIdEntity(ProblemaEntity problemaIdEntity) {
        this.problemaIdEntity = problemaIdEntity;
    }

}
