/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.basededatos.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.grupo.basededatos.logic.dto.BaseDeDatosPageDTO;
import co.edu.uniandes.csw.grupo.basededatos.logic.dto.BaseDeDatosDTO;
import co.edu.uniandes.csw.grupo.basededatos.logic.api.IBaseDeDatosLogicService;
import co.edu.uniandes.csw.grupo.basededatos.persistence.BaseDeDatosPersistence;
import co.edu.uniandes.csw.grupo.basededatos.persistence.api.IBaseDeDatosPersistence;
import co.edu.uniandes.csw.grupo.basededatos.persistence.entity.BaseDeDatosEntity;
import co.edu.uniandes.csw.grupo.basededatos.persistence.converter.BaseDeDatosConverter;
import static co.edu.uniandes.csw.grupo.util._TestUtil.*;

@RunWith(Arquillian.class)
public class BaseDeDatosLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(BaseDeDatosLogicService.class.getPackage())
				.addPackage(IBaseDeDatosLogicService.class.getPackage())
				.addPackage(BaseDeDatosPersistence.class.getPackage())
				.addPackage(BaseDeDatosEntity.class.getPackage())
				.addPackage(IBaseDeDatosPersistence.class.getPackage())
                .addPackage(BaseDeDatosDTO.class.getPackage())
                .addPackage(BaseDeDatosConverter.class.getPackage())
                .addPackage(BaseDeDatosEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IBaseDeDatosLogicService baseDeDatosLogicService;
	
	@Inject
	private IBaseDeDatosPersistence baseDeDatosPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<BaseDeDatosDTO> dtos=baseDeDatosPersistence.getBaseDeDatoss();
		for(BaseDeDatosDTO dto:dtos){
			baseDeDatosPersistence.deleteBaseDeDatos(dto.getId());
		}
	}

	private List<BaseDeDatosDTO> data=new ArrayList<BaseDeDatosDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			BaseDeDatosDTO pdto=new BaseDeDatosDTO();
			pdto.setServidor(generateRandom(String.class));
			pdto.setName(generateRandom(String.class));
			pdto.setDescripcion(generateRandom(String.class));
			pdto.setProposito(generateRandom(String.class));
			pdto.setFechaCreacion(generateRandomDate());
			pdto.setDestruido(generateRandom(Boolean.class));
			pdto.setCaracteristicas(generateRandom(String.class));
			pdto.setPgwebId(generateRandom(Long.class));
			pdto=baseDeDatosPersistence.createBaseDeDatos(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createBaseDeDatosTest(){
		BaseDeDatosDTO ldto=new BaseDeDatosDTO();
		ldto.setServidor(generateRandom(String.class));
		ldto.setName(generateRandom(String.class));
		ldto.setDescripcion(generateRandom(String.class));
		ldto.setProposito(generateRandom(String.class));
		ldto.setFechaCreacion(generateRandomDate());
		ldto.setDestruido(generateRandom(Boolean.class));
		ldto.setCaracteristicas(generateRandom(String.class));
		ldto.setPgwebId(generateRandom(Long.class));
		
		
		BaseDeDatosDTO result=baseDeDatosLogicService.createBaseDeDatos(ldto);
		
		Assert.assertNotNull(result);
		
		BaseDeDatosDTO pdto=baseDeDatosPersistence.getBaseDeDatos(result.getId());
		
		Assert.assertEquals(ldto.getServidor(), pdto.getServidor());	
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getDescripcion(), pdto.getDescripcion());	
		Assert.assertEquals(ldto.getProposito(), pdto.getProposito());	
		Assert.assertEquals(ldto.getFechaCreacion(), pdto.getFechaCreacion());	
		Assert.assertEquals(ldto.getDestruido(), pdto.getDestruido());	
		Assert.assertEquals(ldto.getCaracteristicas(), pdto.getCaracteristicas());	
		Assert.assertEquals(ldto.getPgwebId(), pdto.getPgwebId());	
	}
	
	@Test
	public void getBaseDeDatossTest(){
		List<BaseDeDatosDTO> list=baseDeDatosLogicService.getBaseDeDatoss();
		Assert.assertEquals(list.size(), data.size());
        for(BaseDeDatosDTO ldto:list){
        	boolean found=false;
            for(BaseDeDatosDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getBaseDeDatosTest(){
		BaseDeDatosDTO pdto=data.get(0);
		BaseDeDatosDTO ldto=baseDeDatosLogicService.getBaseDeDatos(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getServidor(), ldto.getServidor());
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getDescripcion(), ldto.getDescripcion());
		Assert.assertEquals(pdto.getProposito(), ldto.getProposito());
		Assert.assertEquals(pdto.getFechaCreacion(), ldto.getFechaCreacion());
		Assert.assertEquals(pdto.getDestruido(), ldto.getDestruido());
		Assert.assertEquals(pdto.getCaracteristicas(), ldto.getCaracteristicas());
		Assert.assertEquals(pdto.getPgwebId(), ldto.getPgwebId());
        
	}
	
	@Test
	public void deleteBaseDeDatosTest(){
		BaseDeDatosDTO pdto=data.get(0);
		baseDeDatosLogicService.deleteBaseDeDatos(pdto.getId());
        BaseDeDatosDTO deleted=baseDeDatosPersistence.getBaseDeDatos(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateBaseDeDatosTest(){
		BaseDeDatosDTO pdto=data.get(0);
		
		BaseDeDatosDTO ldto=new BaseDeDatosDTO();
		ldto.setId(pdto.getId());
		ldto.setServidor(generateRandom(String.class));
		ldto.setName(generateRandom(String.class));
		ldto.setDescripcion(generateRandom(String.class));
		ldto.setProposito(generateRandom(String.class));
		ldto.setFechaCreacion(generateRandomDate());
		ldto.setDestruido(generateRandom(Boolean.class));
		ldto.setCaracteristicas(generateRandom(String.class));
		ldto.setPgwebId(generateRandom(Long.class));
		
		
		baseDeDatosLogicService.updateBaseDeDatos(ldto);
		
		
		BaseDeDatosDTO resp=baseDeDatosPersistence.getBaseDeDatos(pdto.getId());
		
		Assert.assertEquals(ldto.getServidor(), resp.getServidor());	
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getDescripcion(), resp.getDescripcion());	
		Assert.assertEquals(ldto.getProposito(), resp.getProposito());	
		Assert.assertEquals(ldto.getFechaCreacion(), resp.getFechaCreacion());	
		Assert.assertEquals(ldto.getDestruido(), resp.getDestruido());	
		Assert.assertEquals(ldto.getCaracteristicas(), resp.getCaracteristicas());	
		Assert.assertEquals(ldto.getPgwebId(), resp.getPgwebId());	
	}
	
	@Test
	public void getBaseDeDatosPaginationTest(){
		
		BaseDeDatosPageDTO dto1=baseDeDatosLogicService.getBaseDeDatoss(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		BaseDeDatosPageDTO dto2=baseDeDatosLogicService.getBaseDeDatoss(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(BaseDeDatosDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(BaseDeDatosDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(BaseDeDatosDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(BaseDeDatosDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        BaseDeDatosPageDTO dto3=baseDeDatosLogicService.getBaseDeDatoss(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(BaseDeDatosDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(BaseDeDatosDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}