/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.contenedorweb.service;

import java.util.List;

import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.QueryParam;
import javax.inject.Inject;

import co.edu.uniandes.csw.grupo.contenedorweb.logic.api.IContenedorWebLogicService;
import co.edu.uniandes.csw.grupo.contenedorweb.logic.dto.ContenedorWebDTO;
import co.edu.uniandes.csw.grupo.contenedorweb.logic.dto.ContenedorWebPageDTO;


public abstract class _ContenedorWebService {

	@Inject
	protected IContenedorWebLogicService contenedorWebLogicService;
	
	@POST
	public ContenedorWebDTO createContenedorWeb(ContenedorWebDTO contenedorWeb){
		return contenedorWebLogicService.createContenedorWeb(contenedorWeb);
	}
	
	@DELETE
	@Path("{id}")
	public void deleteContenedorWeb(@PathParam("id") Long id){
		contenedorWebLogicService.deleteContenedorWeb(id);
	}
	
	@GET
	public ContenedorWebPageDTO getContenedorWebs(@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords){
		return contenedorWebLogicService.getContenedorWebs(page, maxRecords);
	}
	
	@GET
	@Path("{id}")
	public ContenedorWebDTO getContenedorWeb(@PathParam("id") Long id){
		return contenedorWebLogicService.getContenedorWeb(id);
	}
	
	@PUT
	public void updateContenedorWeb(@PathParam("id") Long id, ContenedorWebDTO contenedorWeb){
		contenedorWebLogicService.updateContenedorWeb(contenedorWeb);
	}
	
}