/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

<<<<<<< .mine
*/

package co.edu.uniandes.csw.grupo.softwaresalas.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.grupo.softwaresalas.logic.dto.SoftwareSalasPageDTO;
import co.edu.uniandes.csw.grupo.softwaresalas.logic.dto.SoftwareSalasDTO;
import co.edu.uniandes.csw.grupo.softwaresalas.persistence.api.ISoftwareSalasPersistence;
import co.edu.uniandes.csw.grupo.softwaresalas.persistence.entity.SoftwareSalasEntity;
import co.edu.uniandes.csw.grupo.softwaresalas.persistence.converter.SoftwareSalasConverter;
import static co.edu.uniandes.csw.grupo.util._TestUtil.*;

@RunWith(Arquillian.class)
public class SoftwareSalasPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(SoftwareSalasPersistence.class.getPackage())
				.addPackage(SoftwareSalasEntity.class.getPackage())
				.addPackage(ISoftwareSalasPersistence.class.getPackage())
                .addPackage(SoftwareSalasDTO.class.getPackage())
                .addPackage(SoftwareSalasConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private ISoftwareSalasPersistence softwareSalasPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from SoftwareSalasEntity").executeUpdate();
	}

	private List<SoftwareSalasEntity> data=new ArrayList<SoftwareSalasEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			SoftwareSalasEntity entity=new SoftwareSalasEntity();
			entity.setTipoMaquina(generateRandom(String.class));
			entity.setSoftware(generateRandom(String.class));
			entity.setVersion(generateRandom(String.class));
			entity.setSolicitante(generateRandom(String.class));
			entity.setNumeroMaquina(generateRandom(String.class));
			entity.setName(generateRandom(String.class));
			entity.setDescripcion(generateRandom(String.class));
			entity.setProposito(generateRandom(String.class));
			entity.setFechaCreacion(generateRandom(Date.class));
			entity.setDestruido(generateRandom(Boolean.class));
			entity.setCaracteristicas(generateRandom(String.class));
			entity.setWorkstationId(generateRandom(Long.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createSoftwareSalasTest(){
		SoftwareSalasDTO dto=new SoftwareSalasDTO();
		dto.setTipoMaquina(generateRandom(String.class));
		dto.setSoftware(generateRandom(String.class));
		dto.setVersion(generateRandom(String.class));
		dto.setSolicitante(generateRandom(String.class));
		dto.setNumeroMaquina(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		dto.setProposito(generateRandom(String.class));
dto.setFechaCreacion(generateRandomDate());
		dto.setDestruido(generateRandom(Boolean.class));
		dto.setCaracteristicas(generateRandom(String.class));
		dto.setWorkstationId(generateRandom(Long.class));
		
		SoftwareSalasDTO result=softwareSalasPersistence.createSoftwareSalas(dto);
		
		Assert.assertNotNull(result);
		
		SoftwareSalasEntity entity=em.find(SoftwareSalasEntity.class, result.getId());
		
		Assert.assertEquals(dto.getTipoMaquina(), entity.getTipoMaquina());
		Assert.assertEquals(dto.getSoftware(), entity.getSoftware());
		Assert.assertEquals(dto.getVersion(), entity.getVersion());
		Assert.assertEquals(dto.getSolicitante(), entity.getSolicitante());
		Assert.assertEquals(dto.getNumeroMaquina(), entity.getNumeroMaquina());
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getDescripcion(), entity.getDescripcion());
		Assert.assertEquals(dto.getProposito(), entity.getProposito());
Assert.assertEquals(parseDate(dto.getFechaCreacion()), entity.getFechaCreacion());	
		Assert.assertEquals(dto.getDestruido(), entity.getDestruido());
		Assert.assertEquals(dto.getCaracteristicas(), entity.getCaracteristicas());
		Assert.assertEquals(dto.getWorkstationId(), entity.getWorkstationId());
	}
	
	@Test
	public void getSoftwareSalassTest(){
		List<SoftwareSalasDTO> list=softwareSalasPersistence.getSoftwareSalass();
		Assert.assertEquals(list.size(), data.size());
        for(SoftwareSalasDTO dto:list){
        	boolean found=false;
            for(SoftwareSalasEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getSoftwareSalasTest(){
		SoftwareSalasEntity entity=data.get(0);
		SoftwareSalasDTO dto=softwareSalasPersistence.getSoftwareSalas(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getTipoMaquina(), dto.getTipoMaquina());
		Assert.assertEquals(entity.getSoftware(), dto.getSoftware());
		Assert.assertEquals(entity.getVersion(), dto.getVersion());
		Assert.assertEquals(entity.getSolicitante(), dto.getSolicitante());
		Assert.assertEquals(entity.getNumeroMaquina(), dto.getNumeroMaquina());
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getDescripcion(), dto.getDescripcion());
		Assert.assertEquals(entity.getProposito(), dto.getProposito());
		Assert.assertEquals(entity.getDestruido(), dto.getDestruido());
		Assert.assertEquals(entity.getCaracteristicas(), dto.getCaracteristicas());
		Assert.assertEquals(entity.getWorkstationId(), dto.getWorkstationId());
        
	}
	
	@Test
	public void deleteSoftwareSalasTest(){
		SoftwareSalasEntity entity=data.get(0);
		softwareSalasPersistence.deleteSoftwareSalas(entity.getId());
        SoftwareSalasEntity deleted=em.find(SoftwareSalasEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateSoftwareSalasTest(){
		SoftwareSalasEntity entity=data.get(0);
		
		SoftwareSalasDTO dto=new SoftwareSalasDTO();
		dto.setId(entity.getId());
		dto.setTipoMaquina(generateRandom(String.class));
		dto.setSoftware(generateRandom(String.class));
		dto.setVersion(generateRandom(String.class));
		dto.setSolicitante(generateRandom(String.class));
		dto.setNumeroMaquina(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		dto.setProposito(generateRandom(String.class));
dto.setFechaCreacion(generateRandomDate());
		dto.setDestruido(generateRandom(Boolean.class));
		dto.setCaracteristicas(generateRandom(String.class));
		dto.setWorkstationId(generateRandom(Long.class));
		
		
		softwareSalasPersistence.updateSoftwareSalas(dto);
		
		
		SoftwareSalasEntity resp=em.find(SoftwareSalasEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getTipoMaquina(), resp.getTipoMaquina());	
		Assert.assertEquals(dto.getSoftware(), resp.getSoftware());	
		Assert.assertEquals(dto.getVersion(), resp.getVersion());	
		Assert.assertEquals(dto.getSolicitante(), resp.getSolicitante());	
		Assert.assertEquals(dto.getNumeroMaquina(), resp.getNumeroMaquina());	
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getDescripcion(), resp.getDescripcion());	
		Assert.assertEquals(dto.getProposito(), resp.getProposito());	
Assert.assertEquals(parseDate(dto.getFechaCreacion()), resp.getFechaCreacion());
		Assert.assertEquals(dto.getDestruido(), resp.getDestruido());	
		Assert.assertEquals(dto.getCaracteristicas(), resp.getCaracteristicas());	
		Assert.assertEquals(dto.getWorkstationId(), resp.getWorkstationId());	
	}
	
	@Test
	public void getSoftwareSalasPaginationTest(){
		//Page 1
		SoftwareSalasPageDTO dto1=softwareSalasPersistence.getSoftwareSalass(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        SoftwareSalasPageDTO dto2=softwareSalasPersistence.getSoftwareSalass(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(SoftwareSalasDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(SoftwareSalasEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(SoftwareSalasDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(SoftwareSalasEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
        @Test
        public void desactivarRecursoTest(){
            for(int i=0;i<data.size();i++)
            {
                SoftwareSalasEntity software= data.get(i);
                if(software.getDestruido())
                {
                    Long idSoftware= software.getId();
                    softwareSalasPersistence.desactivarRecurso(idSoftware);
                    Assert.assertFalse(software.getDestruido());
                }
            }
        }
        
        @Test
        public void busquedasTest()
        {
            // Primero se prueba que se pueda buscar por activos e inactivos
                
            SoftwareSalasPageDTO wpdto = softwareSalasPersistence.getSoftwareSalasByParameters("", "", "", "", "", "", "", "", "", "", "", "", "1");
            Assert.assertNotNull(wpdto);

            List<SoftwareSalasDTO> lista = wpdto.getRecords();
            int contActivos = 0;
            List<Integer> posicionesActivos = new ArrayList<Integer>();
            List<Integer> posicionesInactivos = new ArrayList<Integer>();
            
            for(int i = 0; i < data.size(); i++)
            {
                if(!data.get(i).getDestruido())
                {
                    posicionesActivos.add(i);
                    contActivos++;
                }
                else
                    posicionesInactivos.add(i);
            }
            
            Assert.assertEquals(lista.size(), contActivos);
            
            for(int i = 0; i < contActivos; i++)
            {
                SoftwareSalasEntity entityP=data.get(posicionesActivos.get(i));
                SoftwareSalasDTO entity = SoftwareSalasConverter.entity2PersistenceDTO(entityP);
                SoftwareSalasDTO primer = lista.get(i);            

                Assert.assertEquals(entity.getTipoMaquina(),primer.getTipoMaquina());
                Assert.assertEquals(entity.getSoftware(), primer.getSoftware());
                Assert.assertEquals(entity.getVersion(), primer.getVersion());
                Assert.assertEquals(entity.getSolicitante(),primer.getSolicitante());
                Assert.assertEquals(entity.getNumeroMaquina(),primer.getNumeroMaquina());
                Assert.assertEquals(entity.getName(), primer.getName());
                Assert.assertEquals(entity.getDescripcion(), primer.getDescripcion());
                Assert.assertEquals(entity.getProposito(), primer.getProposito());
                Assert.assertEquals(entity.getCaracteristicas(), primer.getCaracteristicas());
                Assert.assertEquals(entity.getWorkstationId(), primer.getWorkstationId());
                Assert.assertEquals(entity.getDestruido(),primer.getDestruido());
                Assert.assertEquals(entity.getFechaCreacion(),primer.getFechaCreacion());
            }
            
            String fecha1 = (data.get(0).getFechaCreacion().getDate()) + "-" + (data.get(0).getFechaCreacion().getMonth()+1) + "-" + (data.get(0).getFechaCreacion().getYear()+1900-1);
            String fecha2 = (data.get(0).getFechaCreacion().getDate()) + "-" + (data.get(0).getFechaCreacion().getMonth()+1) + "-" + (data.get(0).getFechaCreacion().getYear()+1900+1);
            
            wpdto = softwareSalasPersistence.getSoftwareSalasByParameters(data.get(0).getTipoMaquina(), data.get(0).getSoftware(), data.get(0).getVersion(), data.get(0).getSolicitante(), data.get(0).getNumeroMaquina()
                    , data.get(0).getName(), data.get(0).getDescripcion(), data.get(0).getProposito(), data.get(0).getCaracteristicas(), "" + data.get(0).getWorkstationId(), fecha1, fecha2, (data.get(0).getDestruido())?"0":"1");

            lista = wpdto.getRecords();
            
            Assert.assertEquals(lista.size(), 1);
            
            Assert.assertEquals(lista.get(0).getName(), data.get(0).getName());
            
        }
}