/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.unidaddered.persistence;

import co.edu.uniandes.csw.grupo.encargado.master.persistence.entity.EncargadounidadDeRedEntity;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.grupo.unidaddered.logic.dto.UnidadDeRedPageDTO;
import co.edu.uniandes.csw.grupo.unidaddered.logic.dto.UnidadDeRedDTO;
import co.edu.uniandes.csw.grupo.unidaddered.persistence.api.IUnidadDeRedPersistence;
import co.edu.uniandes.csw.grupo.unidaddered.persistence.entity.UnidadDeRedEntity;
import co.edu.uniandes.csw.grupo.unidaddered.persistence.converter.UnidadDeRedConverter;
import static co.edu.uniandes.csw.grupo.util._TestUtil.*;

@RunWith(Arquillian.class)
public class UnidadDeRedPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(UnidadDeRedPersistence.class.getPackage())
				.addPackage(UnidadDeRedEntity.class.getPackage())
				.addPackage(IUnidadDeRedPersistence.class.getPackage())
                .addPackage(UnidadDeRedDTO.class.getPackage())
                .addPackage(UnidadDeRedConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IUnidadDeRedPersistence unidadDeRedPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from UnidadDeRedEntity").executeUpdate();
	}

	private List<UnidadDeRedEntity> data=new ArrayList<UnidadDeRedEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			UnidadDeRedEntity entity=new UnidadDeRedEntity();
			entity.setTipos(generateRandom(String.class));
			entity.setServidor(generateRandom(String.class));
			entity.setUrl(generateRandom(String.class));
			entity.setName(generateRandom(String.class));
			entity.setDescripcion(generateRandom(String.class));
			entity.setProposito(generateRandom(String.class));
			entity.setFechaCreacion(generateRandom(Date.class));
			entity.setDestruido(generateRandom(Boolean.class));
			entity.setCaracteristicas(generateRandom(String.class));
			entity.setEncargadoId(generateRandom(Long.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createUnidadDeRedTest(){
		UnidadDeRedDTO dto=new UnidadDeRedDTO();
		dto.setTipos(generateRandom(String.class));
		dto.setServidor(generateRandom(String.class));
		dto.setUrl(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		dto.setProposito(generateRandom(String.class));
                dto.setFechaCreacion(generateRandomDate());
		dto.setDestruido(generateRandom(Boolean.class));
		dto.setCaracteristicas(generateRandom(String.class));
		dto.setEncargadoId(generateRandom(Long.class));
		
		UnidadDeRedDTO result=unidadDeRedPersistence.createUnidadDeRed(dto);
		
		Assert.assertNotNull(result);
		
		UnidadDeRedEntity entity=em.find(UnidadDeRedEntity.class, result.getId());
		
		Assert.assertEquals(dto.getTipos(), entity.getTipos());
		Assert.assertEquals(dto.getServidor(), entity.getServidor());
		Assert.assertEquals(dto.getUrl(), entity.getUrl());
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getDescripcion(), entity.getDescripcion());
		Assert.assertEquals(dto.getProposito(), entity.getProposito());
                Assert.assertEquals(parseDate(dto.getFechaCreacion()), entity.getFechaCreacion());	
		Assert.assertEquals(dto.getDestruido(), entity.getDestruido());
		Assert.assertEquals(dto.getCaracteristicas(), entity.getCaracteristicas());
		Assert.assertEquals(dto.getEncargadoId(), entity.getEncargadoId());
	}
        
        @Test
	public void agregarEncargadoUnidadDeRedTest1(){
		UnidadDeRedDTO dto=new UnidadDeRedDTO();
		dto.setTipos(generateRandom(String.class));
		dto.setServidor(generateRandom(String.class));
		dto.setUrl(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		dto.setProposito(generateRandom(String.class));
                dto.setFechaCreacion(generateRandomDate());
		dto.setDestruido(generateRandom(Boolean.class));
		dto.setCaracteristicas(generateRandom(String.class));
		dto.setEncargadoId(generateRandom(Long.class));
		
		UnidadDeRedDTO result=unidadDeRedPersistence.createUnidadDeRed(dto);
		
		Assert.assertNotNull(result);
		
		UnidadDeRedEntity entity=em.find(UnidadDeRedEntity.class, result.getId());
		
		Assert.assertEquals(dto.getTipos(), entity.getTipos());
		Assert.assertEquals(dto.getServidor(), entity.getServidor());
		Assert.assertEquals(dto.getUrl(), entity.getUrl());
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getDescripcion(), entity.getDescripcion());
		Assert.assertEquals(dto.getProposito(), entity.getProposito());
                Assert.assertEquals(parseDate(dto.getFechaCreacion()), entity.getFechaCreacion());	
		Assert.assertEquals(dto.getDestruido(), entity.getDestruido());
		Assert.assertEquals(dto.getCaracteristicas(), entity.getCaracteristicas());
		Assert.assertEquals(dto.getEncargadoId(), entity.getEncargadoId());
                
                //Probar que exista el entity EncargadounidadDeRedEntity
                EncargadounidadDeRedEntity encargado1 = em.find(EncargadounidadDeRedEntity.class,dto.getEncargadoId());
                EncargadounidadDeRedEntity encargado2 = em.find(EncargadounidadDeRedEntity.class,dto.getId());
            
                Assert.assertNotNull(encargado1);
                Assert.assertNotNull(encargado2);
	}
        
        @Test
	public void agregarEncargadoUnidadDeRedTest2(){
		UnidadDeRedDTO dto=new UnidadDeRedDTO();
		dto.setTipos(generateRandom(String.class));
		dto.setServidor(generateRandom(String.class));
		dto.setUrl(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		dto.setProposito(generateRandom(String.class));
                dto.setFechaCreacion(generateRandomDate());
		dto.setDestruido(generateRandom(Boolean.class));
		dto.setCaracteristicas(generateRandom(String.class));
		//dto.setEncargadoId(generateRandom(Long.class));
		
		UnidadDeRedDTO result=unidadDeRedPersistence.createUnidadDeRed(dto);
		
		Assert.assertNotNull(result);
		
		UnidadDeRedEntity entity=em.find(UnidadDeRedEntity.class, result.getId());
		
		Assert.assertEquals(dto.getTipos(), entity.getTipos());
		Assert.assertEquals(dto.getServidor(), entity.getServidor());
		Assert.assertEquals(dto.getUrl(), entity.getUrl());
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getDescripcion(), entity.getDescripcion());
		Assert.assertEquals(dto.getProposito(), entity.getProposito());
                Assert.assertEquals(parseDate(dto.getFechaCreacion()), entity.getFechaCreacion());	
		Assert.assertEquals(dto.getDestruido(), entity.getDestruido());
		Assert.assertEquals(dto.getCaracteristicas(), entity.getCaracteristicas());
		//Assert.assertEquals(dto.getEncargadoId(), entity.getEncargadoId());
                
                //Probar que NO exista el entity EncargadounidadDeRedEntity
                EncargadounidadDeRedEntity encargado1 = em.find(EncargadounidadDeRedEntity.class,dto.getEncargadoId());
                EncargadounidadDeRedEntity encargado2 = em.find(EncargadounidadDeRedEntity.class,dto.getId());
            
                Assert.assertNull(encargado1);
                Assert.assertNull(encargado2);
	}
	
	@Test
	public void getUnidadDeRedsTest(){
		List<UnidadDeRedDTO> list=unidadDeRedPersistence.getUnidadDeReds();
		Assert.assertEquals(list.size(), data.size());
        for(UnidadDeRedDTO dto:list){
        	boolean found=false;
            for(UnidadDeRedEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getUnidadDeRedTest(){
		UnidadDeRedEntity entity=data.get(0);
		UnidadDeRedDTO dto=unidadDeRedPersistence.getUnidadDeRed(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getTipos(), dto.getTipos());
		Assert.assertEquals(entity.getServidor(), dto.getServidor());
		Assert.assertEquals(entity.getUrl(), dto.getUrl());
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getDescripcion(), dto.getDescripcion());
		Assert.assertEquals(entity.getProposito(), dto.getProposito());
		Assert.assertEquals(entity.getDestruido(), dto.getDestruido());
		Assert.assertEquals(entity.getCaracteristicas(), dto.getCaracteristicas());
		Assert.assertEquals(entity.getEncargadoId(), dto.getEncargadoId());
        
	}
	
	@Test
	public void deleteUnidadDeRedTest(){
		UnidadDeRedEntity entity=data.get(0);
		unidadDeRedPersistence.deleteUnidadDeRed(entity.getId());
        UnidadDeRedEntity deleted=em.find(UnidadDeRedEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateUnidadDeRedTest(){
		UnidadDeRedEntity entity=data.get(0);
		
		UnidadDeRedDTO dto=new UnidadDeRedDTO();
		dto.setId(entity.getId());
		dto.setTipos(generateRandom(String.class));
		dto.setServidor(generateRandom(String.class));
		dto.setUrl(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		dto.setProposito(generateRandom(String.class));
dto.setFechaCreacion(generateRandomDate());
		dto.setDestruido(generateRandom(Boolean.class));
		dto.setCaracteristicas(generateRandom(String.class));
		dto.setEncargadoId(generateRandom(Long.class));
		
		
		unidadDeRedPersistence.updateUnidadDeRed(dto);
		
		
		UnidadDeRedEntity resp=em.find(UnidadDeRedEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getTipos(), resp.getTipos());	
		Assert.assertEquals(dto.getServidor(), resp.getServidor());	
		Assert.assertEquals(dto.getUrl(), resp.getUrl());	
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getDescripcion(), resp.getDescripcion());	
		Assert.assertEquals(dto.getProposito(), resp.getProposito());	
Assert.assertEquals(parseDate(dto.getFechaCreacion()), resp.getFechaCreacion());
		Assert.assertEquals(dto.getDestruido(), resp.getDestruido());	
		Assert.assertEquals(dto.getCaracteristicas(), resp.getCaracteristicas());	
		Assert.assertEquals(dto.getEncargadoId(), resp.getEncargadoId());	
	}
	
	@Test
	public void getUnidadDeRedPaginationTest(){
		//Page 1
		UnidadDeRedPageDTO dto1=unidadDeRedPersistence.getUnidadDeReds(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        UnidadDeRedPageDTO dto2=unidadDeRedPersistence.getUnidadDeReds(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(UnidadDeRedDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(UnidadDeRedEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(UnidadDeRedDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(UnidadDeRedEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}