/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.sqldev.master.persistence;
import co.edu.uniandes.csw.grupo.estudiante.logic.dto.EstudianteDTO;
import co.edu.uniandes.csw.grupo.sqldev.master.persistence.entity.SQLDevestudiantesConAccesoEntity;
import co.edu.uniandes.csw.grupo.estudiante.persistence.converter.EstudianteConverter;
import co.edu.uniandes.csw.grupo.problema.logic.dto.ProblemaDTO;
import co.edu.uniandes.csw.grupo.sqldev.master.persistence.entity.SQLDevproblemaEntity;
import co.edu.uniandes.csw.grupo.problema.persistence.converter.ProblemaConverter;
import co.edu.uniandes.csw.grupo.sqldev.logic.dto.SQLDevDTO;
import co.edu.uniandes.csw.grupo.sqldev.master.logic.dto.SQLDevMasterDTO;
import co.edu.uniandes.csw.grupo.sqldev.master.persistence.api._ISQLDevMasterPersistence;
import co.edu.uniandes.csw.grupo.sqldev.persistence.api.ISQLDevPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _SQLDevMasterPersistence implements _ISQLDevMasterPersistence {

  	@PersistenceContext(unitName="RigitalAppPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected ISQLDevPersistence sqldevPersistence;  

    public SQLDevMasterDTO getSQLDev(Long sqldevId) {
        SQLDevMasterDTO sqldevMasterDTO = new SQLDevMasterDTO();
        SQLDevDTO sqldev = sqldevPersistence.getSQLDev(sqldevId);
        sqldevMasterDTO.setSQLDevEntity(sqldev);
        sqldevMasterDTO.setListestudiantesConAcceso(getSQLDevestudiantesConAccesoEntityList(sqldevId));
        sqldevMasterDTO.setListproblema(getSQLDevproblemaEntityList(sqldevId));
        return sqldevMasterDTO;
    }

    public SQLDevestudiantesConAccesoEntity createSQLDevestudiantesConAccesoEntity(SQLDevestudiantesConAccesoEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteSQLDevestudiantesConAccesoEntity(Long sQLDevId, Long estudiantesConAccesoId) {
        Query q = entityManager.createNamedQuery("SQLDevestudiantesConAccesoEntity.deleteSQLDevestudiantesConAccesoEntity");
        q.setParameter("sQLDevId", sQLDevId);
        q.setParameter("estudiantesConAccesoId", estudiantesConAccesoId);
        q.executeUpdate();
    }

    public List<EstudianteDTO> getSQLDevestudiantesConAccesoEntityList(Long sQLDevId) {
        ArrayList<EstudianteDTO> resp = new ArrayList<EstudianteDTO>();
        Query q = entityManager.createNamedQuery("SQLDevestudiantesConAccesoEntity.getByMasterId");
        q.setParameter("sQLDevId",sQLDevId);
        List<SQLDevestudiantesConAccesoEntity> qResult =  q.getResultList();
        for (SQLDevestudiantesConAccesoEntity entity : qResult) { 
            if(entity.getEstudiantesConAccesoIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(EstudianteConverter.entity2PersistenceDTO(entity.getEstudiantesConAccesoIdEntity()));
        }
        return resp;
    }
    public SQLDevproblemaEntity createSQLDevproblemaEntity(SQLDevproblemaEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteSQLDevproblemaEntity(Long sQLDevId, Long problemaId) {
        Query q = entityManager.createNamedQuery("SQLDevproblemaEntity.deleteSQLDevproblemaEntity");
        q.setParameter("sQLDevId", sQLDevId);
        q.setParameter("problemaId", problemaId);
        q.executeUpdate();
    }

    public List<ProblemaDTO> getSQLDevproblemaEntityList(Long sQLDevId) {
        ArrayList<ProblemaDTO> resp = new ArrayList<ProblemaDTO>();
        Query q = entityManager.createNamedQuery("SQLDevproblemaEntity.getByMasterId");
        q.setParameter("sQLDevId",sQLDevId);
        List<SQLDevproblemaEntity> qResult =  q.getResultList();
        for (SQLDevproblemaEntity entity : qResult) { 
            if(entity.getProblemaIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(ProblemaConverter.entity2PersistenceDTO(entity.getProblemaIdEntity()));
        }
        return resp;
    }

}
