/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.unidaddered.master.persistence.entity;

import co.edu.uniandes.csw.grupo.estudiante.persistence.entity.EstudianteEntity;
import co.edu.uniandes.csw.grupo.unidaddered.persistence.entity.UnidadDeRedEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(UnidadDeRedusuariosEntityId.class)
@NamedQueries({
    @NamedQuery(name = "UnidadDeRedusuariosEntity.getByMasterId", query = "SELECT  u FROM UnidadDeRedusuariosEntity u WHERE u.unidadDeRedId=:unidadDeRedId"),
    @NamedQuery(name = "UnidadDeRedusuariosEntity.deleteUnidadDeRedusuariosEntity", query = "DELETE FROM UnidadDeRedusuariosEntity u WHERE u.unidadDeRedId=:unidadDeRedId and  u.usuariosId=:usuariosId")
})
public class UnidadDeRedusuariosEntity implements Serializable {

    @Id
    @Column(name = "unidadDeRedId")
    private Long unidadDeRedId;
    @Id
    @Column(name = "usuariosId")
    private Long usuariosId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "unidadDeRedId", referencedColumnName = "id")
    @JoinFetch
    private EstudianteEntity unidadDeRedIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "usuariosId", referencedColumnName = "id")
    @JoinFetch
    private EstudianteEntity usuariosIdEntity; 

    public UnidadDeRedusuariosEntity() {
    }

    public UnidadDeRedusuariosEntity(Long unidadDeRedId, Long usuariosId) {
        this.unidadDeRedId =unidadDeRedId;
        this.usuariosId = usuariosId;
    }

    public Long getUnidadDeRedId() {
        return unidadDeRedId;
    }

    public void setUnidadDeRedId(Long unidadDeRedId) {
        this.unidadDeRedId = unidadDeRedId;
    }

    public Long getUsuariosId() {
        return usuariosId;
    }

    public void setUsuariosId(Long usuariosId) {
        this.usuariosId = usuariosId;
    }

    public EstudianteEntity getUnidadDeRedIdEntity() {
        return unidadDeRedIdEntity;
    }

    public void setUnidadDeRedIdEntity(EstudianteEntity unidadDeRedIdEntity) {
        this.unidadDeRedIdEntity = unidadDeRedIdEntity;
    }

    public EstudianteEntity getUsuariosIdEntity() {
        return usuariosIdEntity;
    }

    public void setUsuariosIdEntity(EstudianteEntity usuariosIdEntity) {
        this.usuariosIdEntity = usuariosIdEntity;
    }

}
