/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.unidaddered.master.persistence;
import co.edu.uniandes.csw.grupo.estudiante.logic.dto.EstudianteDTO;
import co.edu.uniandes.csw.grupo.unidaddered.master.persistence.entity.UnidadDeRedusuariosEntity;
import co.edu.uniandes.csw.grupo.estudiante.persistence.converter.EstudianteConverter;
import co.edu.uniandes.csw.grupo.problema.logic.dto.ProblemaDTO;
import co.edu.uniandes.csw.grupo.unidaddered.master.persistence.entity.UnidadDeRedproblemasEntity;
import co.edu.uniandes.csw.grupo.problema.persistence.converter.ProblemaConverter;
import co.edu.uniandes.csw.grupo.unidaddered.logic.dto.UnidadDeRedDTO;
import co.edu.uniandes.csw.grupo.unidaddered.master.logic.dto.UnidadDeRedMasterDTO;
import co.edu.uniandes.csw.grupo.unidaddered.master.persistence.api._IUnidadDeRedMasterPersistence;
import co.edu.uniandes.csw.grupo.unidaddered.persistence.api.IUnidadDeRedPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _UnidadDeRedMasterPersistence implements _IUnidadDeRedMasterPersistence {

  	@PersistenceContext(unitName="RigitalAppPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected IUnidadDeRedPersistence unidadderedPersistence;  

    public UnidadDeRedMasterDTO getUnidadDeRed(Long unidadderedId) {
        UnidadDeRedMasterDTO unidadderedMasterDTO = new UnidadDeRedMasterDTO();
        UnidadDeRedDTO unidaddered = unidadderedPersistence.getUnidadDeRed(unidadderedId);
        unidadderedMasterDTO.setUnidadDeRedEntity(unidaddered);
        unidadderedMasterDTO.setListusuarios(getUnidadDeRedusuariosEntityList(unidadderedId));
        unidadderedMasterDTO.setListproblemas(getUnidadDeRedproblemasEntityList(unidadderedId));
        return unidadderedMasterDTO;
    }

    public UnidadDeRedusuariosEntity createUnidadDeRedusuariosEntity(UnidadDeRedusuariosEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteUnidadDeRedusuariosEntity(Long unidadDeRedId, Long usuariosId) {
        Query q = entityManager.createNamedQuery("UnidadDeRedusuariosEntity.deleteUnidadDeRedusuariosEntity");
        q.setParameter("unidadDeRedId", unidadDeRedId);
        q.setParameter("usuariosId", usuariosId);
        q.executeUpdate();
    }

    public List<EstudianteDTO> getUnidadDeRedusuariosEntityList(Long unidadDeRedId) {
        ArrayList<EstudianteDTO> resp = new ArrayList<EstudianteDTO>();
        Query q = entityManager.createNamedQuery("UnidadDeRedusuariosEntity.getByMasterId");
        q.setParameter("unidadDeRedId",unidadDeRedId);
        List<UnidadDeRedusuariosEntity> qResult =  q.getResultList();
        for (UnidadDeRedusuariosEntity entity : qResult) { 
            if(entity.getUsuariosIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(EstudianteConverter.entity2PersistenceDTO(entity.getUsuariosIdEntity()));
        }
        return resp;
    }
    public UnidadDeRedproblemasEntity createUnidadDeRedproblemasEntity(UnidadDeRedproblemasEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteUnidadDeRedproblemasEntity(Long unidadDeRedId, Long problemasId) {
        Query q = entityManager.createNamedQuery("UnidadDeRedproblemasEntity.deleteUnidadDeRedproblemasEntity");
        q.setParameter("unidadDeRedId", unidadDeRedId);
        q.setParameter("problemasId", problemasId);
        q.executeUpdate();
    }

    public List<ProblemaDTO> getUnidadDeRedproblemasEntityList(Long unidadDeRedId) {
        ArrayList<ProblemaDTO> resp = new ArrayList<ProblemaDTO>();
        Query q = entityManager.createNamedQuery("UnidadDeRedproblemasEntity.getByMasterId");
        q.setParameter("unidadDeRedId",unidadDeRedId);
        List<UnidadDeRedproblemasEntity> qResult =  q.getResultList();
        for (UnidadDeRedproblemasEntity entity : qResult) { 
            if(entity.getProblemasIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(ProblemaConverter.entity2PersistenceDTO(entity.getProblemasIdEntity()));
        }
        return resp;
    }

}
