/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.sqldev.master.logic.ejb;

import co.edu.uniandes.csw.grupo.estudiante.logic.dto.EstudianteDTO;
import co.edu.uniandes.csw.grupo.estudiante.persistence.api.IEstudiantePersistence;
import co.edu.uniandes.csw.grupo.problema.logic.dto.ProblemaDTO;
import co.edu.uniandes.csw.grupo.problema.persistence.api.IProblemaPersistence;
import co.edu.uniandes.csw.grupo.sqldev.logic.dto.SQLDevDTO;
import co.edu.uniandes.csw.grupo.sqldev.master.logic.api._ISQLDevMasterLogicService;
import co.edu.uniandes.csw.grupo.sqldev.master.logic.dto.SQLDevMasterDTO;
import co.edu.uniandes.csw.grupo.sqldev.master.persistence.api.ISQLDevMasterPersistence;
import co.edu.uniandes.csw.grupo.sqldev.master.persistence.entity.SQLDevestudiantesConAccesoEntity;
import co.edu.uniandes.csw.grupo.sqldev.master.persistence.entity.SQLDevproblemaEntity;
import co.edu.uniandes.csw.grupo.sqldev.persistence.api.ISQLDevPersistence;
import javax.inject.Inject;

public abstract class _SQLDevMasterLogicService implements _ISQLDevMasterLogicService {

    @Inject
    protected ISQLDevPersistence sqldevPersistance;
    @Inject
    protected ISQLDevMasterPersistence sqldevMasterPersistance;
    @Inject
    protected IProblemaPersistence problemaPersistance;
    @Inject
    protected IEstudiantePersistence estudiantePersistance;

    public SQLDevMasterDTO createMasterSQLDev(SQLDevMasterDTO sqldev) {
        SQLDevDTO persistedSQLDevDTO = sqldevPersistance.createSQLDev(sqldev.getSQLDevEntity());
        if (sqldev.getCreateestudiantesConAcceso() != null) {
            for (EstudianteDTO estudianteDTO : sqldev.getCreateestudiantesConAcceso()) {
                EstudianteDTO createdEstudianteDTO = estudiantePersistance.createEstudiante(estudianteDTO);
                SQLDevestudiantesConAccesoEntity sqldevEstudianteEntity = new SQLDevestudiantesConAccesoEntity(persistedSQLDevDTO.getId(), createdEstudianteDTO.getId());
                sqldevMasterPersistance.createSQLDevestudiantesConAccesoEntity(sqldevEstudianteEntity);
            }
        }
        if (sqldev.getCreateproblema() != null) {
            for (ProblemaDTO problemaDTO : sqldev.getCreateproblema()) {
                ProblemaDTO createdProblemaDTO = problemaPersistance.createProblema(problemaDTO);
                SQLDevproblemaEntity sqldevProblemaEntity = new SQLDevproblemaEntity(persistedSQLDevDTO.getId(), createdProblemaDTO.getId());
                sqldevMasterPersistance.createSQLDevproblemaEntity(sqldevProblemaEntity);
            }
        }
        // update estudiante
        if (sqldev.getUpdateestudiantesConAcceso() != null) {
            for (EstudianteDTO estudianteDTO : sqldev.getUpdateestudiantesConAcceso()) {
                estudiantePersistance.updateEstudiante(estudianteDTO);
                SQLDevestudiantesConAccesoEntity sqldevEstudianteEntity = new SQLDevestudiantesConAccesoEntity(persistedSQLDevDTO.getId(), estudianteDTO.getId());
                sqldevMasterPersistance.createSQLDevestudiantesConAccesoEntity(sqldevEstudianteEntity);
            }
        }
        // update problema
        if (sqldev.getUpdateproblema() != null) {
            for (ProblemaDTO problemaDTO : sqldev.getUpdateproblema()) {
                problemaPersistance.updateProblema(problemaDTO);
                SQLDevproblemaEntity sqldevProblemaEntity = new SQLDevproblemaEntity(persistedSQLDevDTO.getId(), problemaDTO.getId());
                sqldevMasterPersistance.createSQLDevproblemaEntity(sqldevProblemaEntity);
            }
        }
        return sqldev;
    }

    public SQLDevMasterDTO getMasterSQLDev(Long id) {
        return sqldevMasterPersistance.getSQLDev(id);
    }

    public void deleteMasterSQLDev(Long id) {
        sqldevPersistance.deleteSQLDev(id);
    }

    public void updateMasterSQLDev(SQLDevMasterDTO sqldev) {
        sqldevPersistance.updateSQLDev(sqldev.getSQLDevEntity());

        //---- FOR RELATIONSHIP
        // delete estudiante
        if (sqldev.getDeleteestudiantesConAcceso() != null) {
            for (EstudianteDTO estudianteDTO : sqldev.getDeleteestudiantesConAcceso()) {
                sqldevMasterPersistance.deleteSQLDevestudiantesConAccesoEntity(sqldev.getSQLDevEntity().getId(), estudianteDTO.getId());
            }
        }
        // persist new estudiante
        if (sqldev.getCreateestudiantesConAcceso() != null) {
            for (EstudianteDTO estudianteDTO : sqldev.getCreateestudiantesConAcceso()) {
                SQLDevestudiantesConAccesoEntity sqldevEstudianteEntity = new SQLDevestudiantesConAccesoEntity(sqldev.getSQLDevEntity().getId(), estudianteDTO.getId());
                sqldevMasterPersistance.createSQLDevestudiantesConAccesoEntity(sqldevEstudianteEntity);
            }
        }
        // update estudiante
        if (sqldev.getUpdateestudiantesConAcceso() != null) {
            for (EstudianteDTO estudianteDTO : sqldev.getUpdateestudiantesConAcceso()) {
                sqldevMasterPersistance.deleteSQLDevestudiantesConAccesoEntity(sqldev.getSQLDevEntity().getId(), estudianteDTO.getId());
                estudiantePersistance.updateEstudiante(estudianteDTO);
                SQLDevestudiantesConAccesoEntity sqldevEstudianteEntity = new SQLDevestudiantesConAccesoEntity(sqldev.getId(), estudianteDTO.getId());
                sqldevMasterPersistance.createSQLDevestudiantesConAccesoEntity(sqldevEstudianteEntity);
                
            }
        }
        // delete problema
        if (sqldev.getDeleteproblema() != null) {
            for (ProblemaDTO problemaDTO : sqldev.getDeleteproblema()) {
                sqldevMasterPersistance.deleteSQLDevproblemaEntity(sqldev.getSQLDevEntity().getId(), problemaDTO.getId());
            }
        }
        // persist new problema
        if (sqldev.getCreateproblema() != null) {
            for (ProblemaDTO problemaDTO : sqldev.getCreateproblema()) {
                SQLDevproblemaEntity sqldevProblemaEntity = new SQLDevproblemaEntity(sqldev.getSQLDevEntity().getId(), problemaDTO.getId());
                sqldevMasterPersistance.createSQLDevproblemaEntity(sqldevProblemaEntity);
            }
        }
        // update problema
        if (sqldev.getUpdateproblema() != null) {
            for (ProblemaDTO problemaDTO : sqldev.getUpdateproblema()) {
                sqldevMasterPersistance.deleteSQLDevproblemaEntity(sqldev.getSQLDevEntity().getId(), problemaDTO.getId());
                problemaPersistance.updateProblema(problemaDTO);
                SQLDevproblemaEntity sqldevProblemaEntity = new SQLDevproblemaEntity(sqldev.getId(), problemaDTO.getId());
                sqldevMasterPersistance.createSQLDevproblemaEntity(sqldevProblemaEntity);
                
            }
        }
    }
}
