/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.repositorio.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.grupo.repositorio.logic.dto.RepositorioDTO;
import co.edu.uniandes.csw.grupo.repositorio.logic.api.IRepositorioLogicService;
import co.edu.uniandes.csw.grupo.repositorio.master.logic.api._IRepositorioMasterLogicService;
import co.edu.uniandes.csw.grupo.repositorio.master.logic.dto.RepositorioMasterDTO;
import co.edu.uniandes.csw.grupo.problema.logic.api.IProblemaLogicService;
import co.edu.uniandes.csw.grupo.estudiante.logic.api.IEstudianteLogicService;
import co.edu.uniandes.csw.grupo.problema.logic.dto.ProblemaDTO;
import co.edu.uniandes.csw.grupo.estudiante.logic.dto.EstudianteDTO;
import javax.inject.Inject;


public abstract class _RepositorioMasterMockLogicService implements _IRepositorioMasterLogicService {

    protected static ArrayList<RepositorioMasterDTO> repositorioMasterDtosList = new ArrayList<RepositorioMasterDTO>() ;
    @Inject
    protected IProblemaLogicService problemaPersistance;
    @Inject
    protected IEstudianteLogicService estudiantePersistance;
    @Inject
    protected IRepositorioLogicService repositorioPersistance;

    public RepositorioMasterDTO createMasterRepositorio(RepositorioMasterDTO repositorio) {

        repositorioPersistance.createRepositorio(repositorio.getRepositorioEntity());
        for (EstudianteDTO dto : repositorio.getCreateusuariosQueAcceden()) {
            estudiantePersistance.createEstudiante(dto);
        }
        for (ProblemaDTO dto : repositorio.getCreateproblemas()) {
            problemaPersistance.createProblema(dto);
        }
        repositorioMasterDtosList.add(repositorio);
        return repositorio;
    }

    public RepositorioMasterDTO getMasterRepositorio(Long id) {
        for (RepositorioMasterDTO repositorioMasterDTO : repositorioMasterDtosList) {
            if (repositorioMasterDTO.getRepositorioEntity().getId() == id) {
                return repositorioMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterRepositorio(Long id) {
        for (RepositorioMasterDTO repositorioMasterDTO : repositorioMasterDtosList) {
            if (repositorioMasterDTO.getRepositorioEntity().getId() == id) {

                for (EstudianteDTO dto : repositorioMasterDTO.getCreateusuariosQueAcceden()) {
                    estudiantePersistance.deleteEstudiante(dto.getId());
                }
                repositorioPersistance.deleteRepositorio(repositorioMasterDTO.getId());
                repositorioMasterDtosList.remove(repositorioMasterDTO);
                for (ProblemaDTO dto : repositorioMasterDTO.getCreateproblemas()) {
                    problemaPersistance.deleteProblema(dto.getId());
                }
                repositorioPersistance.deleteRepositorio(repositorioMasterDTO.getId());
                repositorioMasterDtosList.remove(repositorioMasterDTO);
            }
        }

    }

    public void updateMasterRepositorio(RepositorioMasterDTO repositorio) {

        // update Estudiante
        if (repositorio.getUpdateusuariosQueAcceden() != null) {
            for (EstudianteDTO dto : repositorio.getUpdateusuariosQueAcceden()) {
                estudiantePersistance.updateEstudiante(dto);
            }
        }
        // persist new Estudiante
        if (repositorio.getCreateusuariosQueAcceden() != null) {
            for (EstudianteDTO dto : repositorio.getCreateusuariosQueAcceden()) {
                EstudianteDTO persistedEstudianteDTO = estudiantePersistance.createEstudiante(dto);
                dto = persistedEstudianteDTO;
            }
        }
        // delete Estudiante
        if (repositorio.getDeleteusuariosQueAcceden() != null) {
            for (EstudianteDTO dto : repositorio.getDeleteusuariosQueAcceden()) {

                estudiantePersistance.deleteEstudiante(dto.getId());
            }
        }
        // update Problema
        if (repositorio.getUpdateproblemas() != null) {
            for (ProblemaDTO dto : repositorio.getUpdateproblemas()) {
                problemaPersistance.updateProblema(dto);
            }
        }
        // persist new Problema
        if (repositorio.getCreateproblemas() != null) {
            for (ProblemaDTO dto : repositorio.getCreateproblemas()) {
                ProblemaDTO persistedProblemaDTO = problemaPersistance.createProblema(dto);
                dto = persistedProblemaDTO;
            }
        }
        // delete Problema
        if (repositorio.getDeleteproblemas() != null) {
            for (ProblemaDTO dto : repositorio.getDeleteproblemas()) {

                problemaPersistance.deleteProblema(dto.getId());
            }
        }
    }
}