/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.workstation.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.grupo.workstation.logic.dto.WorkstationPageDTO;
import co.edu.uniandes.csw.grupo.workstation.logic.dto.WorkstationDTO;
import co.edu.uniandes.csw.grupo.workstation.persistence.api.IWorkstationPersistence;
import co.edu.uniandes.csw.grupo.workstation.persistence.entity.WorkstationEntity;
import co.edu.uniandes.csw.grupo.workstation.persistence.converter.WorkstationConverter;
import static co.edu.uniandes.csw.grupo.util._TestUtil.*;

@RunWith(Arquillian.class)
public class WorkstationPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(WorkstationPersistence.class.getPackage())
				.addPackage(WorkstationEntity.class.getPackage())
				.addPackage(IWorkstationPersistence.class.getPackage())
                .addPackage(WorkstationDTO.class.getPackage())
                .addPackage(WorkstationConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IWorkstationPersistence workstationPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from WorkstationEntity").executeUpdate();
	}

	private List<WorkstationEntity> data=new ArrayList<WorkstationEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			WorkstationEntity entity=new WorkstationEntity();
			entity.setName(generateRandom(String.class));
			entity.setDuenio(generateRandom(String.class));
			entity.setDestino(generateRandom(String.class));
			entity.setSistemaOperativo(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createWorkstationTest(){
		WorkstationDTO dto=new WorkstationDTO();
		dto.setName(generateRandom(String.class));
		dto.setDuenio(generateRandom(String.class));
		dto.setDestino(generateRandom(String.class));
		dto.setSistemaOperativo(generateRandom(String.class));
		
		WorkstationDTO result=workstationPersistence.createWorkstation(dto);
		
		Assert.assertNotNull(result);
		
		WorkstationEntity entity=em.find(WorkstationEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getDuenio(), entity.getDuenio());
		Assert.assertEquals(dto.getDestino(), entity.getDestino());
		Assert.assertEquals(dto.getSistemaOperativo(), entity.getSistemaOperativo());
	}
	
	@Test
	public void getWorkstationsTest(){
		List<WorkstationDTO> list=workstationPersistence.getWorkstations();
		Assert.assertEquals(list.size(), data.size());
        for(WorkstationDTO dto:list){
        	boolean found=false;
            for(WorkstationEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getWorkstationTest(){
		WorkstationEntity entity=data.get(0);
		WorkstationDTO dto=workstationPersistence.getWorkstation(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getDuenio(), dto.getDuenio());
		Assert.assertEquals(entity.getDestino(), dto.getDestino());
		Assert.assertEquals(entity.getSistemaOperativo(), dto.getSistemaOperativo());
        
	}
	
	@Test
	public void deleteWorkstationTest(){
		WorkstationEntity entity=data.get(0);
		workstationPersistence.deleteWorkstation(entity.getId());
        WorkstationEntity deleted=em.find(WorkstationEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateWorkstationTest(){
		WorkstationEntity entity=data.get(0);
		
		WorkstationDTO dto=new WorkstationDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setDuenio(generateRandom(String.class));
		dto.setDestino(generateRandom(String.class));
		dto.setSistemaOperativo(generateRandom(String.class));
		
		
		workstationPersistence.updateWorkstation(dto);
		
		
		WorkstationEntity resp=em.find(WorkstationEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getDuenio(), resp.getDuenio());	
		Assert.assertEquals(dto.getDestino(), resp.getDestino());	
		Assert.assertEquals(dto.getSistemaOperativo(), resp.getSistemaOperativo());	
	}
	
	@Test
	public void getWorkstationPaginationTest(){
		//Page 1
		WorkstationPageDTO dto1=workstationPersistence.getWorkstations(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        WorkstationPageDTO dto2=workstationPersistence.getWorkstations(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(WorkstationDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(WorkstationEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(WorkstationDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(WorkstationEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}