/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.grupo.sqldev.persistence;

import co.edu.uniandes.csw.grupo.encargado.master.persistence.entity.EncargadosQLDevEntity;
import co.edu.uniandes.csw.grupo.maquinavirtual.logic.dto.MaquinaVirtualPageDTO;
import co.edu.uniandes.csw.grupo.maquinavirtual.persistence.converter.MaquinaVirtualConverter;
import co.edu.uniandes.csw.grupo.sqldev.logic.dto.SQLDevDTO;
import co.edu.uniandes.csw.grupo.sqldev.logic.dto.SQLDevPageDTO;
import javax.ejb.Stateless;
import javax.enterprise.inject.Default;

import co.edu.uniandes.csw.grupo.sqldev.persistence.api.ISQLDevPersistence;
import co.edu.uniandes.csw.grupo.sqldev.persistence.converter.SQLDevConverter;
import co.edu.uniandes.csw.grupo.sqldev.persistence.entity.SQLDevEntity;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.ejb.LocalBean;
import javax.persistence.Query;

@Default
@Stateless 
@LocalBean
public class SQLDevPersistence extends _SQLDevPersistence  implements ISQLDevPersistence {

    @Override
    public SQLDevDTO createSQLDev(SQLDevDTO wiki) {
                SQLDevEntity entity=SQLDevConverter.persistenceDTO2Entity(wiki);
		entityManager.persist(entity);
                
                SQLDevDTO rta = SQLDevConverter.entity2PersistenceDTO(entity);
                Long id = rta.getId();
                Long idEncargado = rta.getEncargadoId();
                Long idPgWeb = rta.getPgwebId();
                
                if(idEncargado != 0)
                {
                    System.out.println("ID: " + id);
                    System.out.println("ID Encargado: " + idEncargado);

                    EncargadosQLDevEntity este = new EncargadosQLDevEntity(idEncargado, id);  
                    entityManager.persist(este);

                }                
                
		return rta;
    }
    
    @SuppressWarnings("unchecked")
    public SQLDevPageDTO getSQLDevsByParameters(String servidor ,String name ,String descripcion ,String proposito ,String caracteristicas ,String pgwebId ,String encargadoId ,String fechaCreacion1,String fechaCreacion2,String fechaVencimiento1,String fechaVencimiento2,String estaDestruido)
    {
        Query count = entityManager.createQuery("select count(u) from SQLDevEntity u");
        Long regCount = 0L;
        regCount = Long.parseLong(count.getSingleResult().toString());
                
        String sql = "SELECT u FROM SQLDevEntity u WHERE";
        if(!servidor.isEmpty())
            sql += " AND u.servidor like :servidor";
        if(!name.isEmpty())
            sql += " AND u.name like :name";
        if(!descripcion.isEmpty())
            sql += " AND u.descripcion like :descripcion";
        if(!proposito.isEmpty())
            sql  += " AND u.proposito like :proposito";
        if(!caracteristicas.isEmpty())
            sql += " AND u.caracteristicas like :caracteristicas";
        
        //------------------------------------------------------------------
        if(!pgwebId.isEmpty())
            sql += " AND  u.pgwebId = :pgwebId";
        //------------------------------------------------------------------
        if(!encargadoId.isEmpty())
            sql += " AND  u.encargadoId = :encargadoId";
        
        if(!estaDestruido.isEmpty())
            sql += " AND  u.destruido = :estaDestruido";
        
        if(!fechaCreacion1.isEmpty() && !fechaCreacion2.isEmpty())
            sql += " AND u.fechaCreacion BETWEEN :fechaCreacion1 and :fechaCreacion2";

        if(!fechaVencimiento1.isEmpty() && !fechaVencimiento1.isEmpty())
            sql += " AND u.fechaVencimiento BETWEEN :fechaVencimiento1 and :fechaVencimiento2";
        // Se limpia la sentencia sql
        
        if(sql.endsWith("WHERE"))
            sql = sql.replace("WHERE", "");
        if(sql.contains("WHERE AND"))
            sql = sql.replace("WHERE AND", "WHERE");
        
        System.out.println(sql);
        
        boolean destruido = false;
        
        if(estaDestruido.equals("1"))
            destruido = true;
        
        Query q = entityManager.createQuery(sql);
        
        if(!servidor.isEmpty())
            q.setParameter("servidor", "%"+servidor+"%");
        if(!name .isEmpty())
            q.setParameter("name", "%"+name +"%");
        if(!descripcion.isEmpty())
            q.setParameter("descripcion", "%"+descripcion+"%");
        if(!proposito.isEmpty())
            q.setParameter("proposito", "%"+proposito+"%");
        if(!caracteristicas.isEmpty())
            q.setParameter("caracteristicas", "%"+caracteristicas+"%");
               
        if(!encargadoId.isEmpty())
            q.setParameter("encargadoId", Long.parseLong(encargadoId));
        //----------------------------------------------------------
        if(!pgwebId.isEmpty())
            q.setParameter("pgwebId", Long.parseLong(pgwebId));
        //----------------------------------------------------------
        
        if(!estaDestruido.isEmpty())
            q.setParameter("estaDestruido", destruido);
        
        if(!fechaCreacion1.isEmpty() && !fechaCreacion2.isEmpty())
        {
            String[] a1 = fechaCreacion1.split("-");
            String[] a2 = fechaCreacion2.split("-");
            
            Date fecha1 = new Date(Integer.parseInt(a1[0])-1900, Integer.parseInt(a1[1]),Integer.parseInt(a1[2]));
            Date fecha2 = new Date(Integer.parseInt(a2[0])-1900, Integer.parseInt(a2[1]),Integer.parseInt(a2[2]));
            
            q.setParameter("fechaCreacion1", fecha1);
            q.setParameter("fechaCreacion2", fecha2);            
        }
        
        if(!fechaVencimiento1.isEmpty() && !fechaVencimiento2.isEmpty())
        {
            String[] a1 = fechaVencimiento1.split("-");
            String[] a2 = fechaVencimiento2.split("-");
            
            Date fecha1 = new Date(Integer.parseInt(a1[0])-1900, Integer.parseInt(a1[1]),Integer.parseInt(a1[2]));
            Date fecha2 = new Date(Integer.parseInt(a2[0])-1900, Integer.parseInt(a2[1]),Integer.parseInt(a2[2]));
            
            q.setParameter("fechaVencimiento1", fecha1);
            q.setParameter("fechaVencimiento2", fecha2);            
        }
        
        SQLDevPageDTO response = new SQLDevPageDTO();
        response.setTotalRecords(regCount);
        response.setRecords(SQLDevConverter.entity2PersistenceDTOList(q.getResultList()));
        return response;
        
            
    }
    
     public void desactivarRecurso(Long sqldev) {
        Query query= entityManager.createQuery("UPDATE SQLDevEntity s SET s.destruido='false' WHERE s.id = :sqldev");
        query.setParameter("sqldev", sqldev);
        query.executeUpdate();
    }
     
     public String mensajeVencidos(){
        
        String respuesta = "\n\n- BASES DE DATOS SQL DEVELOPER:";
        
        ArrayList<SQLDevEntity> proximas = new ArrayList();
        ArrayList<SQLDevEntity> vencidas = new ArrayList();
        
        List<SQLDevDTO> lista = getSQLDevs();
        
        for(int i = 0; i < lista.size(); i++)
        {
            SQLDevDTO actual = lista.get(i);
            SQLDevEntity entidad = SQLDevConverter.persistenceDTO2Entity(actual);
            
            boolean estaDestruido = entidad.getDestruido();
            
            Date fechaActual = new Date(System.currentTimeMillis());
            Date fechaVencimiento = entidad.getFechaVencimiento();
            
            System.out.println(fechaActual + " ---- " + fechaActual.getTime());
            System.out.println(fechaVencimiento + " ---- " + fechaVencimiento.getTime());
            
            Long diferencia =  fechaVencimiento.getTime() - fechaActual.getTime();
            
            // 1 semana es equivalente a 604800000 milisegundos
            
            if(estaDestruido)
            {
                if(diferencia < 0)
                    vencidas.add(entidad);
                else if(diferencia < 604800000 && diferencia > 0)
                    proximas.add(entidad);
            }
        }
        
        if(vencidas.size() > 0)
            respuesta += "\n\n      - VENCIDAS:";
        
        for(int i = 0; i < vencidas.size(); i++)
        {
            respuesta += "\n            - " + (i+1) + ": NOMBRE: " + vencidas.get(i).getName() + " , FECHA DE VENCIMIENTO: " + vencidas.get(i).getFechaVencimiento().getDate() + "/" + vencidas.get(i).getFechaVencimiento().getMonth()+ "/" + vencidas.get(i).getFechaVencimiento().getYear();
        }
        
        if(proximas.size() > 0)
            respuesta += "\n\n      - PRÓXIMAS A VENCER:";
        
        for(int i = 0; i < proximas.size(); i++)
        {
            respuesta += "\n            - " + (i+1) + ": NOMBRE: " + proximas.get(i).getName() + " , FECHA DE VENCIMIENTO: " + proximas.get(i).getFechaVencimiento().getDate() + "/" + proximas.get(i).getFechaVencimiento().getMonth()+ "/" + proximas.get(i).getFechaVencimiento().getYear();
        }
        
        if(respuesta.equals("\n\n- BASES DE DATOS SQL DEVELOPER:"))
            respuesta = "";
        
        return respuesta;
                
    }
}